/* ---------------------------------------------------------------
   LICENZA — filigrana discreta per acquirente.
   Prima di pubblicare una copia di questa app per un leader che l'ha
   acquistata, cambia il valore sotto con il suo nome (e opzionalmente il
   suo rango) e pubblica quella copia con un nome di progetto proprio su Vercel.
   Non è un blocco tecnico — è una firma visibile nell'app che rende
   chiaro di chi è quella copia se dovesse circolare fuori dal suo team.
   Lascialo su "" per una copia senza licenza assegnata (uso proprio, demo).
--------------------------------------------------------------- */
const LICENCIA_TITULAR = "";

/* ---------------------------------------------------------------
   CONTENUTO — Cumbre Master: Piano di Compensazione (Sales Master → Imperial Master)
   Fonte: documento ufficiale di distribuzione delle commissioni (Colombia, in COP).
   I valori in USD sono una conversione approssimata di riferimento (~4.000 COP = 1 USD),
   soggetta al tasso di cambio (TRM) reale di ogni momento.
--------------------------------------------------------------- */

const DISTRIBUCION = {
  intro: "Dell'importo totale generato dalle vendite dell'azienda, il 35% è riservato a commissioni e incentivi. Quel 35% diventa il 100% dei PV che si distribuiscono così:",
  partes: [
    { pct: "44%", nombre: "Commissione Generale", detalle: "Si distribuisce tra tutti i membri, in base al loro livello di grado e punteggio.", icon: "users" },
    { pct: "20%", nombre: "Commissione di Maestria", detalle: "Si distribuisce tra chi ha già raggiunto un rango di Maestria (da Sales Master in su).", icon: "mountain-flag" },
    { pct: "6%", nombre: "Commissione del Centro Educativo", detalle: "Va al centro educativo a cui appartieni, per coprire le sue spese operative.", icon: "book-open" },
    { pct: "30%", nombre: "Utile netto dell'azienda", detalle: "È la parte che resta per Atomy.", icon: "package" },
  ],
  notaPeriodo: "Il periodo di accumulo dei punti va sempre dall'1 al 15, e dal 16 alla fine del mese — cioè, due quindicine al mese.",
};

const COMISION_GENERAL = [
  { nivel: "8°", puntos: "5 punti", condicion: "Rappresentante di Vendita — accumulo da 10.000 a 299.999 PV personali.", piernaDebil: "≥ 300.000 PV" },
  { nivel: "7°", puntos: "15 punti", condicion: "Agente — minimo 300.000 PV personali, o gamba debole con 600.000 PV accumulati il mese precedente.", piernaDebil: "≥ 300.000 PV" },
  { nivel: "6°", puntos: "30 punti", condicion: "Agente Speciale — minimo 700.000 PV personali, o gamba debole con 1,4M PV il mese precedente.", piernaDebil: "≥ 700.000 PV" },
  { nivel: "5°", puntos: "60 punti", condicion: "Distributore — minimo 1,5M PV personali, o gamba debole con 3M PV il mese precedente.", piernaDebil: "≥ 1.500.000 PV" },
  { nivel: "4°", puntos: "90 punti", condicion: "Distributore Speciale — minimo 2,4M PV personali, o gamba debole con 4,8M PV il mese precedente.", piernaDebil: "≥ 2.400.000 PV" },
  { nivel: "3°", puntos: "150 punti", condicion: "Continua la scala di Distributore Speciale, con maggiore volume di gamba debole.", piernaDebil: "≥ 6.000.000 PV" },
  { nivel: "2°", puntos: "250 punti", condicion: "Continua la scala di Distributore Speciale, con maggiore volume di gamba debole.", piernaDebil: "≥ 20.000.000 PV" },
  { nivel: "1°", puntos: "300 punti", condicion: "Continua la scala di Distributore Speciale, con maggiore volume di gamba debole.", piernaDebil: "≥ 50.000.000 PV" },
];

const COMISION_GENERAL_NOTA = "Le commissioni si liquidano il martedì successivo, prendendo l'accumulato giornaliero dal mercoledì a quel martedì (la data esatta può variare in base alla banca locale). I tuoi PV personali si somminano sempre alla tua gamba debole.";

const RANGOS_MASTER = [
  {
    n: 0, nombre: "Sales Master", icon: "mountain-flag",
    prerrequisito: "Minimo 2.500.000 PV di gruppo in ciascuna gamba e 700.000 PV personali. Se il totale dei PV della tua gamba debole supera i 300.000 PV, i PV personali che generi durante il periodo possono aggiungersi a quella gamba per completare la Maestria.",
    comisionMaestria: "10% del totale dei PV dell'azienda, distribuito in parti uguali tra tutti i Sales Master.",
    promocion: "Bonus di $1.500.000 COP (≈ $375 USD) la prima volta che raggiungi il rango, trasferito direttamente sul tuo conto.",
    criterio: "Nessuna restrizione per salire di livello — devi solo soddisfare il prerequisito di questa quindicina.",
    montos: [{ etiqueta: "Bonus al raggiungimento del rango", cop: 1500000 }],
  },
  {
    n: 1, nombre: "Diamond Master", icon: "gem",
    prerrequisito: "Minimo 2 Sales Master in ciascuna gamba, e 1.500.000 PV personali.",
    comisionMaestria: "5% del totale dei PV, distribuito tra Diamond Master e le maestrie superiori.",
    promocion: "Bonus di $1.500.000 COP (≈ $375 USD) la prima volta, più un bonus di avanzamento di circa $3.000.000 COP (≈ $750 USD).",
    criterio: "Nessuna restrizione per salire di livello.",
    montos: [
      { etiqueta: "Bonus al raggiungimento del rango", cop: 1500000 },
      { etiqueta: "Bonus di avanzamento", cop: 3000000 },
    ],
  },
  {
    n: 2, nombre: "Sharon Rose Master", icon: "sparkles",
    prerrequisito: "Minimo 2 Diamond Master in ciascuna gamba, e 2.400.000 PV personali.",
    comisionMaestria: "2% del totale dei PV, distribuito tra Sharon Rose Master e le maestrie superiori.",
    promocion: "Circa $7.600.000 COP (≈ $1.900 USD) trasferiti sul tuo conto, più un viaggio per 2 persone.",
    criterio: "Nessuna restrizione per salire di livello.",
    montos: [{ etiqueta: "Bonus al raggiungimento del rango", cop: 7600000 }],
  },
  {
    n: 3, nombre: "Star Master", icon: "star",
    prerrequisito: "Minimo 2 Sharon Rose Master in ciascuna gamba.",
    comisionMaestria: "1,2% del totale dei PV, distribuito tra Star Master e le maestrie superiori.",
    promocion: "Circa $38.000.000 COP (≈ $9.500 USD) trasferiti sul tuo conto, più un viaggio per 4 persone.",
    criterio: "Devi esserti qualificato come Sharon Rose Master 3 volte prima di poter salire a Star Master.",
    montos: [{ etiqueta: "Bonus al raggiungimento del rango", cop: 38000000 }],
  },
  {
    n: 4, nombre: "Royal Master", icon: "crown",
    prerrequisito: "Minimo 2 Star Master in ciascuna gamba.",
    comisionMaestria: "1% del totale dei PV, distribuito tra Royal Master e le maestrie superiori.",
    promocion: "Circa $190.000.000 COP (≈ $47.500 USD) trasferiti sul tuo conto, un viaggio per 4 persone, una carta di debito di circa $7.600.000 COP (≈ $1.900 USD) e il noleggio di un'automobile.",
    criterio: "Devi esserti qualificato come Star Master 3 volte prima di poter salire a Royal Master.",
    montos: [
      { etiqueta: "Bonus al raggiungimento del rango", cop: 190000000 },
      { etiqueta: "Carta di debito", cop: 7600000 },
    ],
  },
  {
    n: 5, nombre: "Crown Master", icon: "award",
    prerrequisito: "Minimo 2 Royal Master in ciascuna gamba.",
    comisionMaestria: "0,5% del totale dei PV, distribuito tra Crown Master e Imperial Master.",
    promocion: "Circa $1.150.000.000 COP (≈ $287.500 USD) trasferiti sul tuo conto, un viaggio per 4 persone, una carta di debito di circa $19.000.000 COP (≈ $4.750 USD) e un'automobile di lusso propria.",
    criterio: "Devi esserti qualificato come Royal Master 3 volte prima di poter salire a Crown Master.",
    montos: [
      { etiqueta: "Bonus al raggiungimento del rango", cop: 1150000000 },
      { etiqueta: "Carta di debito", cop: 19000000 },
    ],
  },
  {
    n: 6, nombre: "Imperial Master", icon: "trophy",
    prerrequisito: "Minimo 2 Crown Master in ciascuna gamba.",
    comisionMaestria: "0,3% del totale dei PV, distribuito tra gli Imperial Master.",
    promocion: "Circa $3.800.000.000 COP (≈ $950.000 USD) trasferiti sul tuo conto, un viaggio per 4 persone, una carta di debito di circa $38.000.000 COP (≈ $9.500 USD), un'automobile di lusso propria con chauffeur, e un ufficio con assistente personale.",
    criterio: "Devi esserti qualificato come Crown Master 3 volte prima di poter salire a Imperial Master — il rango più alto del piano.",
    montos: [
      { etiqueta: "Bonus al raggiungimento del rango", cop: 3800000000 },
      { etiqueta: "Carta di debito", cop: 38000000 },
    ],
  },
];

/* ---------------------------------------------------------------
   CONVERSIONE VALUTARIA PER PAESE (per "Il Mio Rango")
   Tutti gli importi ufficiali di RANGOS_MASTER sono in COP. Questi tassi
   sono approssimati ~2024, solo per riferimento visivo a schermo — non sono
   dati finanziari esatti né si aggiornano con il mercato. La commissione
   reale si calcola e liquida sempre in base al valore del Won coreano
   (KRW) del momento, quindi l'importo che vede ogni leader nella sua valuta
   locale varia in base al tasso di cambio reale di ogni data.
--------------------------------------------------------------- */
const TASAS_COP_POR_MONEDA = {
  COP: 1,
  USD: 4000,
  EUR: 4300,
  MXN: 230,
  BRL: 720,
  CAD: 2900,
};

function convertirDesdeCOP(montoCOP, monedaDestino) {
  const tasa = TASAS_COP_POR_MONEDA[monedaDestino] || TASAS_COP_POR_MONEDA.COP;
  return Number(montoCOP || 0) / tasa;
}

const NOTA_MONEDA_APROX = "Gli importi sopra sono una stima (approssimata) convertita nella tua valuta locale — la commissione reale si calcola e si paga sempre in base al valore del Won coreano (KRW) del momento, e varia in base al tasso di cambio di ogni data.";

const CRITERIOS_GENERALES = [
  "Una volta raggiunto un rango di Maestria, lo conservi in modo permanente: non ci sono condizioni per mantenerlo.",
  "Non è possibile salire due livelli di Maestria in un solo periodo, tranne fino a Diamond Master; da Sharon Rose Master in su, l'avanzamento è sempre di un livello alla volta.",
  "Non c'è una scadenza per avanzare — devi solo mantenere una membership valida.",
  "La Commissione di Maestria si paga due volte al mese: il giorno 15, e anche il giorno 7 dopo la chiusura mensile.",
];

/* Gli importi ufficiali sono sempre in pesos colombiani (COP) e prima delle
   imposte — ogni etichetta viene convertita nella valuta del paese attivo con
   formatMonedaAprox() al momento del rendering (vedi NOTA_MONEDA_APROX). */
const NOTAS_VALORES = [
  { etiqueta: "Viaggio per Sharon Rose Master e Star Master", cop: 3817000, sufijo: "a persona" },
  { etiqueta: "Viaggio per Royal Master, Crown Master e Imperial Master", cop: 15286000, sufijo: "a persona" },
  { etiqueta: "Noleggio dell'automobile di Royal Master", cop: 3817000, sufijo: "mensili" },
  { etiqueta: "Automobile di lusso di Crown Master", cop: 244288000, sufijo: "" },
  { etiqueta: "Automobile di lusso di Imperial Master", cop: 297726000, sufijo: "" },
  { etiqueta: "Ufficio in affitto (Imperial Master)", cop: 9542500, sufijo: "mensili" },
  { etiqueta: "Assistente personale (Imperial Master)", cop: 5725500, sufijo: "mensili" },
  { etiqueta: "Chauffeur (Imperial Master)", cop: 7634000, sufijo: "mensili" },
];

const CLUBES_EXITO = [
  { nombre: "AutoSales Master", requisito: "Riqualificarsi come Sales Master 12 volte in un anno (una volta a quindicina, in media).", ingresoCopMin: 8000000, ingresoCopMax: 12000000, ingresoSufijo: "mensili" },
  { nombre: "Club dei Leader", ingresoAnualCop: 350000000 },
  { nombre: "Club dei Leader Royal", ingresoAnualCop: 700000000 },
  { nombre: "Club dei Leader Crown", ingresoAnualCop: 1500000000 },
  { nombre: "Club dei Leader Imperial", requisito: "Diventare Imperial Master." },
];

const PAISES_CATALOGO = [
  { id: "CO", label: "Colombia", moneda: "COP", simbolo: "$", locale: "es-CO", codigo: "+57" },
  { id: "EU", label: "Europa", moneda: "EUR", simbolo: "€", locale: "es-ES", codigo: "+34" },
  { id: "MX", label: "Messico", moneda: "MXN", simbolo: "$", locale: "es-MX", codigo: "+52" },
  { id: "BR", label: "Brasile", moneda: "BRL", simbolo: "R$", locale: "pt-BR", codigo: "+55" },
  { id: "CA", label: "Canada", moneda: "CAD", simbolo: "$", locale: "en-CA", codigo: "+1" },
  { id: "US", label: "Stati Uniti", moneda: "USD", simbolo: "$", locale: "en-US", codigo: "+1" },
];

const CATALOGO_PRODUCTOS_POR_PAIS = {
  CO: [
  { categoria: "Cura Personale", nombre: "Absolute Acondicionador - Paso 3", precio: 78000, pv: 8000 },
  { categoria: "Cura Personale", nombre: "Absolute Shampoo - Paso 1", precio: 78000, pv: 8000 },
  { categoria: "Cura Personale", nombre: "Absolute Tratamiento - Paso 2", precio: 53000, pv: 5000 },
  { categoria: "Cura Personale", nombre: "Acondicionador Herbal para Cabello", precio: 53800, pv: 5700 },
  { categoria: "Cura Personale", nombre: "Aidam Limpiador Íntimo Unisex", precio: 25000, pv: 2000 },
  { categoria: "Cura Personale", nombre: "Atomy Exfoliante Corporal a Base de Sal", precio: 75000, pv: 8300 },
  { categoria: "Cura Personale", nombre: "Atomy Homme All-in-One Wash", precio: 70600, pv: 7400 },
  { categoria: "Cura Personale", nombre: "Atomy Homme Multi-Action Cleanser", precio: 50000, pv: 5000 },
  { categoria: "Cura Personale", nombre: "Atomy Root Vital Hair Care Set", precio: 219000, pv: 22500 },
  { categoria: "Cura Personale", nombre: "Atomy Sculpture Acondicionador - Paso 2", precio: 62400, pv: 6200 },
  { categoria: "Cura Personale", nombre: "Atomy Sculpture Shampoo - Paso 1", precio: 62400, pv: 6200 },
  { categoria: "Cura Personale", nombre: "Atomy Shampoo de Proteína", precio: 80000, pv: 8000 },
  { categoria: "Cura Personale", nombre: "Atomy Tónico para Cabello", precio: 56600, pv: 5600 },
  { categoria: "Cura Personale", nombre: "Atomy Tratamiento Líquido de Proteína", precio: 60000, pv: 6500 },
  { categoria: "Cura Personale", nombre: "Cepillo Dental (8 unidades)", precio: 37000, pv: 5300 },
  { categoria: "Cura Personale", nombre: "Cepillo Dental Niños (8 unidades)", precio: 48300, pv: 4200 },
  { categoria: "Cura Personale", nombre: "Crema de Manos", precio: 53600, pv: 7400 },
  { categoria: "Cura Personale", nombre: "Esencia para Rizos", precio: 44000, pv: 5400 },
  { categoria: "Cura Personale", nombre: "Hand Balm Butter 50ml", precio: 24000, pv: 2800 },
  { categoria: "Cura Personale", nombre: "Hand Balm Marine 50ml", precio: 24000, pv: 2800 },
  { categoria: "Cura Personale", nombre: "Hand Balm Pure 50ml", precio: 24000, pv: 2800 },
  { categoria: "Cura Personale", nombre: "Jabón de Manos", precio: 15400, pv: 1100 },
  { categoria: "Cura Personale", nombre: "Kit de Viaje (6 piezas)", precio: 91000, pv: 5000 },
  { categoria: "Cura Personale", nombre: "Limpiador Herbal para Cuerpo", precio: 39800, pv: 3500 },
  { categoria: "Cura Personale", nombre: "Loción Corporal", precio: 42400, pv: 3520 },
  { categoria: "Cura Personale", nombre: "Óleo Esencial para el Cabello", precio: 49200, pv: 5600 },
  { categoria: "Cura Personale", nombre: "Pasta dental 200g (x5 unidades)", precio: 71200, pv: 3600 },
  { categoria: "Cura Personale", nombre: "Pasta dental 50g (x4 unidades)", precio: 23100, pv: 3300 },
  { categoria: "Cura Personale", nombre: "Pasta Dental Sensitive (x3 unidades)", precio: 48000, pv: 4800 },
  { categoria: "Cura Personale", nombre: "Root Vital Hair Shampoo", precio: 95000, pv: 9100 },
  { categoria: "Cura Personale", nombre: "Set de Ampolletas Para Cuero Cabelludo Root Vital (X3)", precio: 178000, pv: 24000 },
  { categoria: "Cura Personale", nombre: "Shampoo Herbal para Cabello", precio: 53800, pv: 5700 },
  { categoria: "Cura Personale", nombre: "Sistema de Cuidado Bucal (x4 kits)", precio: 55000, pv: 6500 },
  { categoria: "Cura Personale", nombre: "Spray de Propóleo Verde (x3 unidades)", precio: 110000, pv: 9500 },
  { categoria: "Cura Personale", nombre: "Terapia para Manos (x4 unidades)", precio: 63500, pv: 6600 },
  { categoria: "Cura Personale", nombre: "Tratamiento Herbal para Cabello", precio: 29700, pv: 2900 },
  { categoria: "Cura Personale", nombre: "Tratamiento Root Vital", precio: 72000, pv: 8000 },
  { categoria: "Casa", nombre: "Atomy Esponjillas de Acero Inoxidable (x2 unidades)", precio: 16900, pv: 750 },
  { categoria: "Casa", nombre: "Atomy Scratch Free Scrubber", precio: 20000, pv: 1400 },
  { categoria: "Casa", nombre: "Detergente en Polvo para Ropa (x2 unidades)", precio: 57700, pv: 4000 },
  { categoria: "Casa", nombre: "Detergente Lavatrastes", precio: 32700, pv: 3400 },
  { categoria: "Casa", nombre: "Detergente Líquido para Ropa", precio: 54000, pv: 4800 },
  { categoria: "Casa", nombre: "Guantes de Látex (M) *2 pares", precio: 23900, pv: 1300 },
  { categoria: "Casa", nombre: "Suavizante de Telas", precio: 46200, pv: 3700 },
  { categoria: "Alimenti", nombre: "Aceite de Aguacate Extra Virgen", precio: 90000, pv: 8000 },
  { categoria: "Alimenti", nombre: "Atomy Sí Puer (X 30 sobres)", precio: 122000, pv: 13600 },
  { categoria: "Alimenti", nombre: "Café Arábica Black (x80 sobres)", precio: 95000, pv: 5200 },
  { categoria: "Alimenti", nombre: "Café Arábica Zero Sugar X 100 Sobres", precio: 149000, pv: 5500 },
  { categoria: "Alimenti", nombre: "Crema no Láctea (x50 sobres)", precio: 53100, pv: 2200 },
  { categoria: "HemoHIM", nombre: "Atomy HemoHIM *4set", precio: 1700000, pv: 300000 },
  { categoria: "HemoHIM", nombre: "Bolsa de Regalo (20cm x 31cm)", precio: 1500, pv: 0 },
  { categoria: "HemoHIM", nombre: "Bolsa reutilizable HemoHIM", precio: 4200, pv: 0 },
  { categoria: "HemoHIM", nombre: "Combo HemoHIM x 2 set", precio: 880000, pv: 150000 },
  { categoria: "HemoHIM", nombre: "HemoHIM (x60 sobres)", precio: 440000, pv: 70000 },
  { categoria: "Cura della Pelle", nombre: "Absolute Ampolla - Paso 2", precio: 196000, pv: 28600 },
  { categoria: "Cura della Pelle", nombre: "Absolute CellActive (1 Set con 6 productos)", precio: 880000, pv: 130000 },
  { categoria: "Cura della Pelle", nombre: "Absolute Contorno de Ojos - Paso 5", precio: 163500, pv: 23400 },
  { categoria: "Cura della Pelle", nombre: "Absolute Crema Nutritiva - Paso 6", precio: 147800, pv: 20800 },
  { categoria: "Cura della Pelle", nombre: "Absolute Loción - Paso 4", precio: 147800, pv: 20800 },
  { categoria: "Cura della Pelle", nombre: "Absolute Suero - Paso 3", precio: 163500, pv: 23400 },
  { categoria: "Cura della Pelle", nombre: "Absolute Tónico - Paso 1", precio: 147800, pv: 20800 },
  { categoria: "Cura della Pelle", nombre: "Aceite Limpiador", precio: 79300, pv: 8100 },
  { categoria: "Cura della Pelle", nombre: "Adelica Máscara de Pestañas Long-Lash", precio: 64000, pv: 6800 },
  { categoria: "Cura della Pelle", nombre: "Adelica Máscara de Pestañas Volumen", precio: 64000, pv: 6800 },
  { categoria: "Cura della Pelle", nombre: "Aplicador Atomy Absolute", precio: 18000, pv: 2000 },
  { categoria: "Cura della Pelle", nombre: "Atomy Absolute Hydra Balm", precio: 62000, pv: 8800 },
  { categoria: "Cura della Pelle", nombre: "Atomy Absolute Protector Solar", precio: 53000, pv: 5000 },
  { categoria: "Cura della Pelle", nombre: "Atomy Absolute Snow Crema de Día - Paso 3", precio: 131000, pv: 18500 },
  { categoria: "Cura della Pelle", nombre: "Atomy Absolute Snow Crema de Noche - Paso 4", precio: 139000, pv: 19500 },
  { categoria: "Cura della Pelle", nombre: "Atomy Absolute Snow Dark Spot Corrector - Noche Paso 2", precio: 90000, pv: 12000 },
  { categoria: "Cura della Pelle", nombre: "Atomy Absolute Snow Protector Solar", precio: 78000, pv: 9000 },
  { categoria: "Cura della Pelle", nombre: "Atomy Absolute Snow Set (5 productos)", precio: 552000, pv: 92000 },
  { categoria: "Cura della Pelle", nombre: "Atomy Absolute Snow Suero - Día Paso 2 / Noche Paso 3", precio: 139000, pv: 18500 },
  { categoria: "Cura della Pelle", nombre: "Atomy Absolute Snow Tónico - Día/Noche Paso 1", precio: 106000, pv: 14600 },
  { categoria: "Cura della Pelle", nombre: "Atomy Loción de Protección Solar", precio: 130000, pv: 15000 },
  { categoria: "Cura della Pelle", nombre: "Atomy Mascarilla de Arcilla Hinoki", precio: 73000, pv: 9700 },
  { categoria: "Cura della Pelle", nombre: "Atomy Sun Stick", precio: 45500, pv: 4700 },
  { categoria: "Cura della Pelle", nombre: "Bálsamo Labial", precio: 21200, pv: 2200 },
  { categoria: "Cura della Pelle", nombre: "Brillo Labial", precio: 50700, pv: 5300 },
  { categoria: "Cura della Pelle", nombre: "Cream Mist", precio: 58000, pv: 8000 },
  { categoria: "Cura della Pelle", nombre: "Crema BB", precio: 38500, pv: 2800 },
  { categoria: "Cura della Pelle", nombre: "Cuidado Nocturno 4 Pasos (1 Set)", precio: 156600, pv: 14300 },
  { categoria: "Cura della Pelle", nombre: "Desmaquillante Bifásico", precio: 48000, pv: 5000 },
  { categoria: "Cura della Pelle", nombre: "Espuma Limpiadora - Paso 2", precio: 39600, pv: 3400 },
  { categoria: "Cura della Pelle", nombre: "Gel Exfoliante - Paso 3", precio: 39600, pv: 3400 },
  { categoria: "Cura della Pelle", nombre: "Hydra Brightening Care Set", precio: 170000, pv: 25000 },
  { categoria: "Cura della Pelle", nombre: "Kit de Viaje (6 piezas)", precio: 91000, pv: 5000 },
  { categoria: "Cura della Pelle", nombre: "Lápiz de Cejas (Café)", precio: 35000, pv: 4200 },
  { categoria: "Cura della Pelle", nombre: "Limpiador Profundo - Paso 1", precio: 39600, pv: 3400 },
  { categoria: "Cura della Pelle", nombre: "Marine Ampoule Mask Brightening & Firming (x10 unidades)", precio: 120000, pv: 18000 },
  { categoria: "Cura della Pelle", nombre: "Mascarilla de Oro 24K", precio: 160000, pv: 23000 },
  { categoria: "Cura della Pelle", nombre: "Mascarilla Diaria Expert (Hidratante) (x10 unidades)", precio: 46000, pv: 4500 },
  { categoria: "Cura della Pelle", nombre: "Mascarilla Peel-Off - Paso 4", precio: 39600, pv: 3400 },
  { categoria: "Cura della Pelle", nombre: "Parche para Ojos de Hidrogel (x60 Parches)", precio: 82000, pv: 10000 },
  { categoria: "Cura della Pelle", nombre: "Peeling Pad", precio: 53000, pv: 7000 },
  { categoria: "Cura della Pelle", nombre: "Protector Solar Beige (x1)", precio: 39800, pv: 3600 },
  { categoria: "Cura della Pelle", nombre: "Protector Solar Blanco (x1)", precio: 39800, pv: 3600 },
  { categoria: "Cura della Pelle", nombre: "Sistema Cuidado para la Piel The Fame (1 Set con 5 Productos)", precio: 400000, pv: 57200 },
  { categoria: "Cura della Pelle", nombre: "Sobre Individual Marine Ampoule Mask Brightening", precio: 13000, pv: 1200 },
  { categoria: "Cura della Pelle", nombre: "The Fame Crema Esencia - Paso 3", precio: 89400, pv: 12500 },
  { categoria: "Cura della Pelle", nombre: "The Fame Crema Nutritiva - Paso 5", precio: 84300, pv: 11700 },
  { categoria: "Cura della Pelle", nombre: "The Fame Crema para Ojos - Paso 2", precio: 84300, pv: 11700 },
  { categoria: "Cura della Pelle", nombre: "The Fame Loción - Paso 4", precio: 84300, pv: 11700 },
  { categoria: "Cura della Pelle", nombre: "The Fame Tónico - Paso 1", precio: 84300, pv: 11700 },
  { categoria: "Cura della Salute", nombre: "Atomy Fibra Psyllium Husk (x45 sobres)", precio: 135000, pv: 19100 },
  { categoria: "Cura della Salute", nombre: "Atomy Spirulina & SOD", precio: 147000, pv: 17000 },
  { categoria: "Cura della Salute", nombre: "Caja Individual Probióticos", precio: 81000, pv: 8000 },
  { categoria: "Cura della Salute", nombre: "E-Omega 3 (x180 Cápsulas)", precio: 110000, pv: 10000 },
  { categoria: "Cura della Salute", nombre: "Fermento de Noni Concentrado", precio: 270000, pv: 35000 },
  { categoria: "Cura della Salute", nombre: "Fermento de Noni Sachet (24 sobres)", precio: 295000, pv: 39500 },
  { categoria: "Cura della Salute", nombre: "Gel de Manzana Verde (x28 sobres)", precio: 128000, pv: 15000 },
  { categoria: "Cura della Salute", nombre: "Gomitas de Propóleo y Zinc", precio: 120000, pv: 11000 },
  { categoria: "Cura della Salute", nombre: "Hierro (x60 sobres)", precio: 138000, pv: 15000 },
  { categoria: "Cura della Salute", nombre: "Probióticos 10+ (4 Cajas x 30 sobres, total 120 sobres)", precio: 290000, pv: 30000 },
  { categoria: "Cura della Salute", nombre: "Rutina Detox + PVs", precio: 539000, pv: 75000 },
  { categoria: "Cura della Salute", nombre: "Rutina Fortalece + PVs", precio: 688000, pv: 110000 },
  { categoria: "Promozioni", nombre: "Absolute Recargado", precio: 1760000, pv: 300000 },
  { categoria: "Promozioni", nombre: "Combo Evolución Fitness", precio: 500000, pv: 55000 },
  { categoria: "Promozioni", nombre: "Combo Imperial 2026", precio: 2049000, pv: 300000 },
  { categoria: "Promozioni", nombre: "Combo San Valentín", precio: 261700, pv: 28100 },
  { categoria: "Promozioni", nombre: "Promo Noni 5+1", precio: 1350000, pv: 175000 },
  { categoria: "Promozioni", nombre: "Rutina Equilibrio + PVs", precio: 720000, pv: 100000 },
  { categoria: "Altro", nombre: "Balanza y Muñequera de Skincare", precio: 24000, pv: 0 },
  { categoria: "Altro", nombre: "Bolsa Laminada (x1)", precio: 1700, pv: 0 },
  { categoria: "Altro", nombre: "Bolsa Multiusos (x1)", precio: 2600, pv: 0 },
  { categoria: "Altro", nombre: "Cartilla Escenario de Vida (x10 unidades)", precio: 25000, pv: 0 },
  { categoria: "Altro", nombre: "Cosmetiquera Atomy Merch", precio: 24000, pv: 0 },
  { categoria: "Altro", nombre: "Cuaderno Oficial Atomy Colombia", precio: 24900, pv: 0 },
  { categoria: "Altro", nombre: "Gorra Oficial Atomy Colombia", precio: 34000, pv: 0 },
  { categoria: "Altro", nombre: "Maleta Oficial Atomy", precio: 99000, pv: 0 },
  { categoria: "Altro", nombre: "Muñequito Han Gil Park (Limitado)", precio: 42000, pv: 0 },
  { categoria: "Altro", nombre: "Pin Amplifica", precio: 14000, pv: 0 },
  { categoria: "Altro", nombre: "Pin Metálico Oficial Atomy Colombia", precio: 12000, pv: 0 },
  { categoria: "Altro", nombre: "Pin Metálico Oficial HemoHIM", precio: 12000, pv: 0 },
  ],
  EU: [
  { categoria: "Cura Personale", nombre: "Acondicionador Herbal", precio: 15, pv: 4000 },
  { categoria: "Cura Personale", nombre: "Atomy Cerakids Shampoo & Bath *1EA", precio: 13.5, pv: 6500 },
  { categoria: "Cura Personale", nombre: "Cepillo de Dientes (8 unidades)", precio: 7.99, pv: 5000 },
  { categoria: "Cura Personale", nombre: "Cera de Cabello & Anti-Yea", precio: 13.5, pv: 6000 },
  { categoria: "Cura Personale", nombre: "Champú Herbal", precio: 14.5, pv: 7000 },
  { categoria: "Cura Personale", nombre: "Complejo de Aceite Capilar", precio: 13.5, pv: 6000 },
  { categoria: "Cura Personale", nombre: "Crema Corporal Ultra Rich", precio: 14.5, pv: 7000 },
  { categoria: "Cura Personale", nombre: "Cuidado de Cuello Brazil (Kit)", precio: 14.5, pv: 7000 },
  { categoria: "Cura Personale", nombre: "Dental Sonic Herbal Head Bundle", precio: 85, pv: 67000 },
  { categoria: "Cura Personale", nombre: "Dental Sonic Refill Head", precio: 14.5, pv: 8000 },
  { categoria: "Cura Personale", nombre: "Foot Scrub Wash", precio: 11, pv: 6000 },
  { categoria: "Cura Personale", nombre: "Fresh Sun Lotion", precio: 25, pv: 16000 },
  { categoria: "Cura Personale", nombre: "Hand Therapy 4 Kit", precio: 16.5, pv: 6200 },
  { categoria: "Cura Personale", nombre: "Limpiador de Manos", precio: 15.5, pv: 5000 },
  { categoria: "Cura Personale", nombre: "Limpiador Multi-Acción Homme", precio: 12.5, pv: 5000 },
  { categoria: "Cura Personale", nombre: "Loción Corporal", precio: 12, pv: 6000 },
  { categoria: "Cura Personale", nombre: "Pasta de Dientes 200g x5 Tubos", precio: 18.5, pv: 6000 },
  { categoria: "Cura Personale", nombre: "Pasta de Dientes 50g x4", precio: 6.5, pv: 2000 },
  { categoria: "Cura Personale", nombre: "Proteína Intensiva Shampoo", precio: 20, pv: 10000 },
  { categoria: "Cura Personale", nombre: "Proteína Intensiva Tratamiento", precio: 16.5, pv: 9500 },
  { categoria: "Cura Personale", nombre: "Root Nourishing Lotion", precio: 12, pv: 7000 },
  { categoria: "Cura Personale", nombre: "Saengmodan Hair Tonic", precio: 14, pv: 7000 },
  { categoria: "Cura Personale", nombre: "Sal de Baño Ultra Rich", precio: 14, pv: 6000 },
  { categoria: "Cura Personale", nombre: "Scalpcare 2 Set", precio: 28, pv: 11000 },
  { categoria: "Cura Personale", nombre: "Scalpcare Acondicionador", precio: 14.5, pv: 6000 },
  { categoria: "Cura Personale", nombre: "Scalpcare Hair Champú", precio: 14.5, pv: 6000 },
  { categoria: "Cura Personale", nombre: "Silk & Protein Hair Essence", precio: 13.5, pv: 6000 },
  { categoria: "Cura Personale", nombre: "Sistema de Cuidado Bucal 1 Set (4 pcs)", precio: 14.5, pv: 7000 },
  { categoria: "Cura Personale", nombre: "Sun Stick", precio: 12, pv: 5000 },
  { categoria: "Cura Personale", nombre: "Travel Cleansing Kit Set", precio: 17, pv: 3800 },
  { categoria: "Cura Personale", nombre: "Ultra Fine Wash", precio: 17.5, pv: 7000 },
  { categoria: "Cura Personale", nombre: "Ultra Rich Body Set", precio: 27, pv: 13000 },
  { categoria: "Alimenti", nombre: "Cafe Arabica 3 in 1 (50 sticks)", precio: 12.5, pv: 2000 },
  { categoria: "Alimenti", nombre: "Cafe Arabica Black", precio: 16, pv: 5000 },
  { categoria: "Alimenti", nombre: "Fermented Noni Drink Pouch", precio: 56.5, pv: 37000 },
  { categoria: "Alimenti", nombre: "Noni Pouch x4 Set", precio: 226, pv: 150000 },
  { categoria: "Alimenti", nombre: "Té Pu'er", precio: 25, pv: 14000 },
  { categoria: "Integratori Alimentari", nombre: "Bióticos 10 Plus", precio: 29.5, pv: 15000 },
  { categoria: "Integratori Alimentari", nombre: "E-Omega 3", precio: 22.5, pv: 9000 },
  { categoria: "Integratori Alimentari", nombre: "Espirulina Pura 100%", precio: 24, pv: 10000 },
  { categoria: "Integratori Alimentari", nombre: "Eye Lutein", precio: 32, pv: 15000 },
  { categoria: "Integratori Alimentari", nombre: "Hemohim G (4 set)", precio: 420, pv: 300000 },
  { categoria: "Integratori Alimentari", nombre: "Hemohim G - EU", precio: 105, pv: 73000 },
  { categoria: "Integratori Alimentari", nombre: "Hongsdaman", precio: 77.5, pv: 55000 },
  { categoria: "Integratori Alimentari", nombre: "Inner Collagen", precio: 34, pv: 19000 },
  { categoria: "Integratori Alimentari", nombre: "Noni Bottle", precio: 49, pv: 35000 },
  { categoria: "Integratori Alimentari", nombre: "Pomegranate Mixed Fruit Jelly", precio: 67.5, pv: 30000 },
  { categoria: "Integratori Alimentari", nombre: "Vitamina C", precio: 22.5, pv: 9000 },
  { categoria: "Bellezza", nombre: "Absolute Ampolla", precio: 41, pv: 27000 },
  { categoria: "Bellezza", nombre: "Absolute Crema Nutritiva", precio: 37, pv: 23000 },
  { categoria: "Bellezza", nombre: "Absolute Crema Spot-Out", precio: 36, pv: 23000 },
  { categoria: "Bellezza", nombre: "Absolute Loción", precio: 37, pv: 23000 },
  { categoria: "Bellezza", nombre: "Absolute Mix 21 Saldito", precio: 17.5, pv: 6000 },
  { categoria: "Bellezza", nombre: "Absolute Protector Solar Esencia", precio: 12.5, pv: 6000 },
  { categoria: "Bellezza", nombre: "Absolute Skincare Set", precio: 195, pv: 115000 },
  { categoria: "Bellezza", nombre: "Absolute Suero", precio: 40, pv: 26000 },
  { categoria: "Bellezza", nombre: "Absolute Tónico", precio: 35.5, pv: 22000 },
  { categoria: "Bellezza", nombre: "Adelica Lip Color Glow", precio: 9.5, pv: 5250 },
  { categoria: "Bellezza", nombre: "Adelica Volume Mascara Black", precio: 11.5, pv: 6250 },
  { categoria: "Bellezza", nombre: "Adelica Waterproof Mascara", precio: 11.5, pv: 6250 },
  { categoria: "Bellezza", nombre: "Atomy Absolute BB 211 Unidad", precio: 17.5, pv: 8000 },
  { categoria: "Bellezza", nombre: "Atomy Absolute Complejo Cellactive para Ojos", precio: 40.5, pv: 26000 },
  { categoria: "Bellezza", nombre: "Atomy Absolute Urban Shield Cushion Solar", precio: 15, pv: 9000 },
  { categoria: "Bellezza", nombre: "Cuidado de Noche Set", precio: 37, pv: 14000 },
  { categoria: "Bellezza", nombre: "Deep Cleanser", precio: 9.5, pv: 3500 },
  { categoria: "Bellezza", nombre: "Derma Real Cica Gel Limpiador", precio: 13.5, pv: 8000 },
  { categoria: "Bellezza", nombre: "Derma Real Cica Set", precio: 62.5, pv: 43000 },
  { categoria: "Bellezza", nombre: "Foam Cleanser", precio: 9.5, pv: 3500 },
  { categoria: "Bellezza", nombre: "Homme Cuidado de la Piel Set", precio: 55, pv: 35000 },
  { categoria: "Bellezza", nombre: "Limpiador Multi-Acción Homme", precio: 12.5, pv: 5000 },
  { categoria: "Bellezza", nombre: "Lip Glow", precio: 12, pv: 6000 },
  { categoria: "Bellezza", nombre: "Marine Ampoule Eye Patch", precio: 19.5, pv: 10000 },
  { categoria: "Bellezza", nombre: "Marine Ampoule Gel Mask", precio: 32, pv: 22000 },
  { categoria: "Bellezza", nombre: "Mascarilla Diaria Especializada", precio: 12.5, pv: 5000 },
  { categoria: "Bellezza", nombre: "Mascarilla Nocturna de Oro 24K", precio: 28, pv: 21000 },
  { categoria: "Bellezza", nombre: "Mild Bubble Cleanser", precio: 10.5, pv: 5000 },
  { categoria: "Bellezza", nombre: "Peel-Off Mask", precio: 9.5, pv: 3500 },
  { categoria: "Bellezza", nombre: "Peeling Gel", precio: 9.5, pv: 3500 },
  { categoria: "Bellezza", nombre: "Peeling Pad", precio: 12, pv: 7000 },
  { categoria: "Bellezza", nombre: "Sistema Cuidado para la Piel The Fame", precio: 99.5, pv: 60000 },
  { categoria: "Bellezza", nombre: "Synergy Ampoule *1 Set", precio: 90, pv: 72000 },
  { categoria: "Bellezza", nombre: "Travel Cleansing Kit Set", precio: 17, pv: 3800 },
  { categoria: "Altro", nombre: "Adelica Make-Up Brush Set + 2 Free Waterproof Mascara", precio: 35, pv: 27000 },
  { categoria: "Altro", nombre: "Adelica Waterproof Mascara", precio: 11.5, pv: 6250 },
  { categoria: "Altro", nombre: "Airopass Line Coffee (4-piece pouch)", precio: 6, pv: 0 },
  { categoria: "Altro", nombre: "Atomy Acropass Line Lifter 5 Pouch", precio: 60, pv: 35000 },
  { categoria: "Altro", nombre: "Atomy Business Book", precio: 10.5, pv: 0 },
  { categoria: "Altro", nombre: "Atomy Medi-Cook 4SET (9pcs.)", precio: 550, pv: 280000 },
  { categoria: "Altro", nombre: "Atomy T-shirt", precio: 15, pv: 0 },
  { categoria: "Altro", nombre: "Atomy Thermal Tumbler", precio: 22, pv: 5000 },
  { categoria: "Altro", nombre: "Best of Atomy Bundle", precio: 455, pv: 300000 },
  { categoria: "Altro", nombre: "Detergente para Ropa en Láminas", precio: 11, pv: 6500 },
  { categoria: "Altro", nombre: "MediCook Ceramic Set", precio: 155, pv: 100000 },
  { categoria: "Altro", nombre: "Mino Knives Set of 2", precio: 150, pv: 70000 },
  { categoria: "Altro", nombre: "New 2026Ver01 Leaflet (Bundle 20pieces)", precio: 5, pv: 0 },
  { categoria: "Altro", nombre: "Sticker Bundle Set", precio: 25, pv: 0 },
  { categoria: "Altro", nombre: "Summer Wellness Bundle", precio: 150, pv: 100000 },
  ],
  MX: [
  { categoria: "Cura Personale", nombre: "Absolute Conditioner", precio: 360, pv: 8000 },
  { categoria: "Cura Personale", nombre: "Absolute Shampoo", precio: 360, pv: 8000 },
  { categoria: "Cura Personale", nombre: "Aceite Esencial para el Cabello *1pza", precio: 260, pv: 5200 },
  { categoria: "Cura Personale", nombre: "Acondicionador Herbal para Cabello *1pza", precio: 280, pv: 5200 },
  { categoria: "Cura Personale", nombre: "Aidam Limpiador 1pza", precio: 130, pv: 1800 },
  { categoria: "Cura Personale", nombre: "Atomy Absolute Feminine Wash", precio: 240, pv: 5500 },
  { categoria: "Cura Personale", nombre: "Atomy Cepillo Dental para Niños", precio: 200, pv: 4000 },
  { categoria: "Cura Personale", nombre: "Atomy Cepillo Dental Set (6pza)", precio: 200, pv: 5000 },
  { categoria: "Cura Personale", nombre: "Atomy Enjuague Bucal", precio: 190, pv: 4000 },
  { categoria: "Cura Personale", nombre: "Atomy Hand Cream", precio: 295, pv: 7000 },
  { categoria: "Cura Personale", nombre: "Atomy Protein Intensive Hair Care Set", precio: 800, pv: 21700 },
  { categoria: "Cura Personale", nombre: "Atomy Salón & Color Castaño 5G", precio: 240, pv: 5000 },
  { categoria: "Cura Personale", nombre: "Atomy Salón & Color Castaño Obscuro 6G", precio: 240, pv: 5000 },
  { categoria: "Cura Personale", nombre: "Atomy Salón & Color Negro 7G", precio: 240, pv: 5000 },
  { categoria: "Cura Personale", nombre: "Atomy Sculpture Conditioner", precio: 330, pv: 5720 },
  { categoria: "Cura Personale", nombre: "Atomy Sculpture Shampoo", precio: 330, pv: 5720 },
  { categoria: "Cura Personale", nombre: "Curling Essence", precio: 195, pv: 5400 },
  { categoria: "Cura Personale", nombre: "Green Propolis Spray", precio: 460, pv: 9500 },
  { categoria: "Cura Personale", nombre: "Homme All-in-One Wash", precio: 370, pv: 7000 },
  { categoria: "Cura Personale", nombre: "Homme Multi-Action Cleanser", precio: 250, pv: 4800 },
  { categoria: "Cura Personale", nombre: "Jabón para Manos *1pza", precio: 80, pv: 1000 },
  { categoria: "Cura Personale", nombre: "Limpiador Herbal para Cuerpo *1pza", precio: 210, pv: 3200 },
  { categoria: "Cura Personale", nombre: "Loción para el Cuerpo 1pza", precio: 220, pv: 3200 },
  { categoria: "Cura Personale", nombre: "Pasta dental 200g *1set", precio: 370, pv: 3250 },
  { categoria: "Cura Personale", nombre: "Pasta dental 50g *1set", precio: 120, pv: 3000 },
  { categoria: "Cura Personale", nombre: "Pasta Dental para Encías y Dientes Sensibles", precio: 230, pv: 5500 },
  { categoria: "Cura Personale", nombre: "Shampoo Herbal para Cabello *1pza", precio: 280, pv: 5200 },
  { categoria: "Cura Personale", nombre: "Sistema de Cuidado Bucal *1set", precio: 300, pv: 6250 },
  { categoria: "Cura Personale", nombre: "Terapia para Manos (4pzas) 1kit", precio: 330, pv: 6000 },
  { categoria: "Cura Personale", nombre: "Tratamiento Herbal para Cabello *1pza", precio: 170, pv: 2900 },
  { categoria: "Cura Personale", nombre: "Tratamiento Líquido para Cabello *1pza", precio: 300, pv: 5200 },
  { categoria: "Casa", nombre: "Atomy Fabric Detergent", precio: 300, pv: 3600 },
  { categoria: "Casa", nombre: "Atomy Mexico MediCook Set", precio: 16000, pv: 300000 },
  { categoria: "Casa", nombre: "Atomy Scratch Free Scrubber", precio: 100, pv: 1500 },
  { categoria: "Casa", nombre: "Detergente Lavatrastes *1pza", precio: 170, pv: 3100 },
  { categoria: "Casa", nombre: "Detergente Multisuperficies para Baño", precio: 280, pv: 6000 },
  { categoria: "Casa", nombre: "Detergente Multisuperficies para Cocina", precio: 280, pv: 6000 },
  { categoria: "Casa", nombre: "Detergente para Ropa 1pza", precio: 280, pv: 4400 },
  { categoria: "Casa", nombre: "Fibra de Acero Inoxidable", precio: 70, pv: 1100 },
  { categoria: "Casa", nombre: "Guantes de Látex (M)", precio: 130, pv: 2000 },
  { categoria: "Casa", nombre: "MediCook 32cm Wok", precio: 5700, pv: 100000 },
  { categoria: "Casa", nombre: "MediCook Olla 1.8 L", precio: 3200, pv: 56000 },
  { categoria: "Casa", nombre: "MediCook Olla 5.5 L", precio: 5200, pv: 91000 },
  { categoria: "Casa", nombre: "MediCook Sartén 22 cm", precio: 2400, pv: 42000 },
  { categoria: "Casa", nombre: "O2 Bubble Power", precio: 220, pv: 5000 },
  { categoria: "Casa", nombre: "Suavizante de Telas 1pza", precio: 240, pv: 3400 },
  { categoria: "Alimenti", nombre: "Atomy Café Arábica 0 Azúcar 50T", precio: 520, pv: 4000 },
  { categoria: "Alimenti", nombre: "Atomy Potato Ramen", precio: 210, pv: 1300 },
  { categoria: "Alimenti", nombre: "Café Arábica 50T", precio: 350, pv: 3000 },
  { categoria: "Alimenti", nombre: "Probiotics", precio: 750, pv: 16000 },
  { categoria: "Cura della Salute", nombre: "Alaska E-Omega 3 *1pza", precio: 470, pv: 8300 },
  { categoria: "Cura della Salute", nombre: "Applephenon Jelly Stick", precio: 560, pv: 15000 },
  { categoria: "Cura della Salute", nombre: "Atomy Bitter Melon", precio: 790, pv: 22000 },
  { categoria: "Cura della Salute", nombre: "Atomy Color B", precio: 460, pv: 9000 },
  { categoria: "Cura della Salute", nombre: "Atomy Color C *1set", precio: 440, pv: 7800 },
  { categoria: "Cura della Salute", nombre: "Atomy Finezyme", precio: 350, pv: 9000 },
  { categoria: "Cura della Salute", nombre: "Atomy Greencera F", precio: 720, pv: 20000 },
  { categoria: "Cura della Salute", nombre: "Atomy Inner Collagen Powder", precio: 770, pv: 22000 },
  { categoria: "Cura della Salute", nombre: "Atomy Kids Vegan Gummy Multivitamin", precio: 420, pv: 11000 },
  { categoria: "Cura della Salute", nombre: "Atomy Luxanthin", precio: 950, pv: 28000 },
  { categoria: "Cura della Salute", nombre: "Atomy Pro Packed-Tamin", precio: 600, pv: 18000 },
  { categoria: "Cura della Salute", nombre: "Atomy Pure Spirulina 100%", precio: 540, pv: 9100 },
  { categoria: "Cura della Salute", nombre: "Atomy Rhubarb Queen", precio: 580, pv: 16000 },
  { categoria: "Cura della Salute", nombre: "Atomy Tea", precio: 660, pv: 13000 },
  { categoria: "Cura della Salute", nombre: "Atomy Tri-Active Calcium", precio: 490, pv: 13000 },
  { categoria: "Cura della Salute", nombre: "Atomy TURMACIN MSM", precio: 900, pv: 21000 },
  { categoria: "Cura della Salute", nombre: "Combo 5+1 Noni Challenge", precio: 6000, pv: 170000 },
  { categoria: "Cura della Salute", nombre: "Combo Pequeños Impulsos", precio: 840, pv: 22000 },
  { categoria: "Cura della Salute", nombre: "Organic Fermented Noni Concentrate (Bottle)", precio: 1200, pv: 34000 },
  { categoria: "Cura della Salute", nombre: "Organic Noni Concentrate (Pouch)", precio: 1200, pv: 34000 },
  { categoria: "Cura della Salute", nombre: "Rhodiola Milk Thistle", precio: 750, pv: 15000 },
  { categoria: "Him", nombre: "Him 4 Set PV's Up", precio: 8140, pv: 250000 },
  { categoria: "Him", nombre: "Him PV's Up", precio: 2150, pv: 65000 },
  { categoria: "Bellezza", nombre: "4 Pasos PV's Up", precio: 830, pv: 16000 },
  { categoria: "Bellezza", nombre: "Absolute 24K Gold Night Mask", precio: 730, pv: 19000 },
  { categoria: "Bellezza", nombre: "Absolute Ampolla", precio: 1020, pv: 26000 },
  { categoria: "Bellezza", nombre: "Absolute Contorno de Ojos", precio: 940, pv: 23400 },
  { categoria: "Bellezza", nombre: "Absolute Crema Nutritiva", precio: 850, pv: 20800 },
  { categoria: "Bellezza", nombre: "Absolute Hydra Balm", precio: 280, pv: 8000 },
  { categoria: "Bellezza", nombre: "Absolute Loción", precio: 850, pv: 20800 },
  { categoria: "Bellezza", nombre: "Absolute Oil Serum Mist", precio: 370, pv: 9000 },
  { categoria: "Bellezza", nombre: "Absolute PV's Up", precio: 5060, pv: 170000 },
  { categoria: "Bellezza", nombre: "Absolute Suero", precio: 940, pv: 23400 },
  { categoria: "Bellezza", nombre: "Absoluto Tónico Facial", precio: 850, pv: 20800 },
  { categoria: "Bellezza", nombre: "Adelica Lip Rouge Matt M01 True Red", precio: 290, pv: 9000 },
  { categoria: "Bellezza", nombre: "Adelica Lip Rouge Matt M02 Neutral Pink", precio: 290, pv: 9000 },
  { categoria: "Bellezza", nombre: "Adelica Lip Rouge Matt M03 Rose Flare", precio: 290, pv: 9000 },
  { categoria: "Bellezza", nombre: "Adelica Lip Rouge Satin 02 Sweet Pink", precio: 290, pv: 9000 },
  { categoria: "Bellezza", nombre: "Adelica Lip Rouge Satin 03 Raspberry", precio: 290, pv: 9000 },
  { categoria: "Bellezza", nombre: "Adelica The New Gold Collagen Ampoule Cushion 02", precio: 590, pv: 16000 },
  { categoria: "Bellezza", nombre: "Adelica The New Gold Collagen Ampoule Cushion 03", precio: 590, pv: 16000 },
  { categoria: "Bellezza", nombre: "Adelica The New Gold Collagen Ampoule Cushion 04", precio: 590, pv: 16000 },
  { categoria: "Bellezza", nombre: "Atomy Absolute BB 21*1EA", precio: 360, pv: 10000 },
  { categoria: "Bellezza", nombre: "Atomy Absolute BB 23*1EA", precio: 360, pv: 10000 },
  { categoria: "Bellezza", nombre: "Atomy Absolute Essence Sunscreen", precio: 250, pv: 5100 },
  { categoria: "Bellezza", nombre: "Atomy Absolute Snow Dark Spot Corrector", precio: 340, pv: 9000 },
  { categoria: "Bellezza", nombre: "Atomy Absolute Snow Day Cream", precio: 540, pv: 14000 },
  { categoria: "Bellezza", nombre: "Atomy Absolute Snow Night Cream", precio: 640, pv: 17000 },
  { categoria: "Bellezza", nombre: "Atomy Absolute Snow Serum", precio: 750, pv: 20000 },
  { categoria: "Bellezza", nombre: "Atomy Absolute Snow Set", precio: 2900, pv: 90000 },
  { categoria: "Bellezza", nombre: "Atomy Absolute Snow Tone-Up Essence Sun", precio: 280, pv: 7500 },
  { categoria: "Bellezza", nombre: "Atomy Absolute Snow Toner", precio: 550, pv: 15000 },
  { categoria: "Bellezza", nombre: "Atomy ACNE Clear Expert System", precio: 1520, pv: 40200 },
  { categoria: "Bellezza", nombre: "Atomy Adelica Delineador de Cejas - Café Claro", precio: 170, pv: 4200 },
  { categoria: "Bellezza", nombre: "Atomy Adelica Delineador de Cejas - Café Obscuro", precio: 170, pv: 4200 },
  { categoria: "Bellezza", nombre: "Atomy Adelica Mascara para Pestañas a Prueba de Agua", precio: 280, pv: 6800 },
  { categoria: "Bellezza", nombre: "Atomy Brush Pen Eyeliner (Black)", precio: 230, pv: 3600 },
  { categoria: "Bellezza", nombre: "Atomy Fresh Sun Lotion", precio: 480, pv: 9500 },
  { categoria: "Bellezza", nombre: "Atomy Homme Skincare Set", precio: 1200, pv: 29000 },
  { categoria: "Bellezza", nombre: "Atomy Hydra Brightening Care Set", precio: 1000, pv: 27000 },
  { categoria: "Bellezza", nombre: "Atomy Lip & Eye Remover", precio: 220, pv: 5000 },
  { categoria: "Bellezza", nombre: "Atomy Marine Ampoule Eye Patch", precio: 400, pv: 10000 },
  { categoria: "Bellezza", nombre: "Atomy Mascara para Pestañas - Volumen/Negro", precio: 280, pv: 6800 },
  { categoria: "Bellezza", nombre: "Atomy Peeling Pad", precio: 250, pv: 6000 },
  { categoria: "Bellezza", nombre: "Atomy Rose Rain Mist", precio: 270, pv: 5500 },
  { categoria: "Bellezza", nombre: "Atomy Sun Stick", precio: 240, pv: 4500 },
  { categoria: "Bellezza", nombre: "Atomy Synergy Ampoule Program", precio: 2600, pv: 68000 },
  { categoria: "Bellezza", nombre: "Bálsamo Labial *1pza", precio: 110, pv: 2000 },
  { categoria: "Bellezza", nombre: "Brillo Labial *1pza", precio: 290, pv: 5300 },
  { categoria: "Bellezza", nombre: "Crema BB 1pza", precio: 200, pv: 2500 },
  { categoria: "Bellezza", nombre: "Daily Expert Mask Brightening", precio: 265, pv: 4500 },
  { categoria: "Bellezza", nombre: "Daily Expert Mask Firming", precio: 265, pv: 4500 },
  { categoria: "Bellezza", nombre: "Daily Expert Mask Moisture", precio: 265, pv: 4500 },
  { categoria: "Bellezza", nombre: "Deep Pure Cleansing Oil", precio: 420, pv: 7500 },
  { categoria: "Bellezza", nombre: "Derma Calming Sun Stick", precio: 240, pv: 5100 },
  { categoria: "Bellezza", nombre: "Derma Real Cica Gel Cleanser", precio: 260, pv: 8000 },
  { categoria: "Bellezza", nombre: "Espuma Limpiadora 1pza", precio: 210, pv: 3250 },
  { categoria: "Bellezza", nombre: "Gel Exfoliante 1pza", precio: 210, pv: 3250 },
  { categoria: "Bellezza", nombre: "Homme All-in-One Wash", precio: 370, pv: 7000 },
  { categoria: "Bellezza", nombre: "Homme Multi-Action Cleanser", precio: 250, pv: 4800 },
  { categoria: "Bellezza", nombre: "Limpiador Profundo 1pza", precio: 210, pv: 3250 },
  { categoria: "Bellezza", nombre: "Limpieza Profunda Kit de Viaje (6pzas) 1kit", precio: 350, pv: 5000 },
  { categoria: "Bellezza", nombre: "Mascarilla en Gel - 7 Soluciones 1kit", precio: 720, pv: 13000 },
  { categoria: "Bellezza", nombre: "Mascarilla Peel-Off 1pza", precio: 210, pv: 3250 },
  { categoria: "Bellezza", nombre: "Protector Solar Beige 1pza", precio: 200, pv: 3250 },
  { categoria: "Bellezza", nombre: "Protector Solar Blanco 1pza", precio: 200, pv: 3250 },
  { categoria: "Bellezza", nombre: "Sistema Cuidado para la Piel The Fame", precio: 2370, pv: 57200 },
  { categoria: "Bellezza", nombre: "The Fame Crema Esencia", precio: 530, pv: 12500 },
  { categoria: "Bellezza", nombre: "The Fame Crema Nutritiva", precio: 500, pv: 11700 },
  { categoria: "Bellezza", nombre: "The Fame Crema para Ojos", precio: 500, pv: 11700 },
  { categoria: "Bellezza", nombre: "The Fame Loción", precio: 500, pv: 11700 },
  { categoria: "Bellezza", nombre: "The Fame Tónico", precio: 500, pv: 11700 },
  { categoria: "Altro", nombre: "Bolsa de Plástico 1pza", precio: 15, pv: 0 },
  { categoria: "Altro", nombre: "Bolsa Laminada (S) 1pza", precio: 10, pv: 0 },
  { categoria: "Altro", nombre: "Folleto de productos *1set (20pzas)", precio: 190, pv: 0 },
  ],
  BR: [
  { categoria: "Cura Personale", nombre: "Atomy Absolute Feminine Wash 160mL", precio: 134, pv: 13000 },
  { categoria: "Cura Personale", nombre: "Atomy Absolute Hair Conditioner 500mL", precio: 145, pv: 14000 },
  { categoria: "Cura Personale", nombre: "Atomy Absolute Hair Shampoo 500mL", precio: 127, pv: 12000 },
  { categoria: "Cura Personale", nombre: "Atomy Absolute Haircare Set", precio: 346, pv: 36000 },
  { categoria: "Cura Personale", nombre: "Atomy Body Lotion 300mL", precio: 108, pv: 9000 },
  { categoria: "Cura Personale", nombre: "Atomy Cerakidz Cream 100mL", precio: 143, pv: 14000 },
  { categoria: "Cura Personale", nombre: "Atomy Cerakidz Lotion 200mL", precio: 168, pv: 16000 },
  { categoria: "Cura Personale", nombre: "Atomy Hair Essential Oil 100mL", precio: 135, pv: 14000 },
  { categoria: "Cura Personale", nombre: "Atomy Hand Balm Butter 50ml", precio: 59, pv: 6000 },
  { categoria: "Cura Personale", nombre: "Atomy Hand Balm Pure 50ml", precio: 59, pv: 6000 },
  { categoria: "Cura Personale", nombre: "Atomy Hand Soap 300mL", precio: 40, pv: 2500 },
  { categoria: "Cura Personale", nombre: "Atomy Herbal Body Cleanser 500mL", precio: 90, pv: 8000 },
  { categoria: "Cura Personale", nombre: "Atomy Herbal Conditioner 500mL", precio: 107, pv: 11000 },
  { categoria: "Cura Personale", nombre: "Atomy Herbal Hair Treatment 200mL", precio: 67, pv: 7000 },
  { categoria: "Cura Personale", nombre: "Atomy Herbal Shampoo 500mL", precio: 105, pv: 11000 },
  { categoria: "Cura Personale", nombre: "Atomy Homme All-in-One Wash 500mL", precio: 152, pv: 17000 },
  { categoria: "Cura Personale", nombre: "Atomy Kids Toothbrush (8 unidades)", precio: 80, pv: 7500 },
  { categoria: "Cura Personale", nombre: "Atomy Oral Care System", precio: 120, pv: 15000 },
  { categoria: "Cura Personale", nombre: "Atomy Protein Hair Repair Set", precio: 345, pv: 35000 },
  { categoria: "Cura Personale", nombre: "Atomy Protein Intensive Shampoo", precio: 198, pv: 20000 },
  { categoria: "Cura Personale", nombre: "Atomy Protein Intensive Treatment", precio: 158, pv: 16000 },
  { categoria: "Cura Personale", nombre: "Atomy Scalpcare Conditioner 500ml", precio: 125, pv: 12000 },
  { categoria: "Cura Personale", nombre: "Atomy Scalpcare Set", precio: 220, pv: 25000 },
  { categoria: "Cura Personale", nombre: "Atomy Scalpcare Shampoo 500ml", precio: 110, pv: 12000 },
  { categoria: "Cura Personale", nombre: "Atomy Sensitive Toothpaste Set", precio: 118, pv: 15000 },
  { categoria: "Cura Personale", nombre: "Atomy Toothbrush (8 unidades)", precio: 80, pv: 11000 },
  { categoria: "Cura Personale", nombre: "Atomy Toothpaste 4X50g", precio: 48, pv: 2200 },
  { categoria: "Cura Personale", nombre: "Atomy Toothpaste 5X200g", precio: 155, pv: 8000 },
  { categoria: "Cura Personale", nombre: "Atomy Travel Cleansing Kit", precio: 159, pv: 10000 },
  { categoria: "Cura Personale", nombre: "Atomy Ultra Rich Body Cream 200mL", precio: 130, pv: 11500 },
  { categoria: "Casa", nombre: "Atomy Sheet Laundry Detergent (30 folhas)", precio: 116, pv: 8000 },
  { categoria: "Alimenti", nombre: "Atomy Alaska E-Omega 3", precio: 176, pv: 17000 },
  { categoria: "Alimenti", nombre: "Atomy Café Arábica Black", precio: 152, pv: 6000 },
  { categoria: "Alimenti", nombre: "Atomy Café Arábica T50", precio: 72, pv: 3200 },
  { categoria: "Alimenti", nombre: "Atomy Puer Tea", precio: 199, pv: 24000 },
  { categoria: "Alimenti", nombre: "Atomy Vitamin C", precio: 162, pv: 17000 },
  { categoria: "Beleza", nombre: "Atomy Absolute Ampoule Total", precio: 310, pv: 45000 },
  { categoria: "Beleza", nombre: "Atomy Absolute CellActive Nutrition", precio: 1540, pv: 130000 },
  { categoria: "Beleza", nombre: "Atomy Absolute Evening Foam Balm", precio: 130, pv: 7000 },
  { categoria: "Beleza", nombre: "Atomy Absolute Gel Serum Mist", precio: 179, pv: 17000 },
  { categoria: "Beleza", nombre: "Atomy Absolute HTA Complex", precio: 249, pv: 30000 },
  { categoria: "Beleza", nombre: "Atomy Absolute Lotion", precio: 239, pv: 30000 },
  { categoria: "Beleza", nombre: "Atomy Absolute Skincare Set", precio: 1540, pv: 130000 },
  { categoria: "Beleza", nombre: "Atomy Absolute Snow Dark Spot Corrector", precio: 162, pv: 27000 },
  { categoria: "Beleza", nombre: "Atomy Absolute Snow Lotion", precio: 1250, pv: 170000 },
  { categoria: "Beleza", nombre: "Atomy Absolute Toner", precio: 269, pv: 30000 },
  { categoria: "Beleza", nombre: "Atomy Ceramide Cream", precio: 143, pv: 15000 },
  { categoria: "Beleza", nombre: "Atomy Daily Expert Mask Brightening", precio: 106, pv: 15000 },
  { categoria: "Beleza", nombre: "Atomy Daily Expert Mask Firming", precio: 106, pv: 15000 },
  { categoria: "Beleza", nombre: "Atomy Daily Expert Mask Moisturizing", precio: 159, pv: 7000 },
  { categoria: "Beleza", nombre: "Atomy Deep Pure Cleansing Toner", precio: 159, pv: 7000 },
  { categoria: "Beleza", nombre: "Atomy Evening Care Deep Cleanser", precio: 79, pv: 7000 },
  { categoria: "Beleza", nombre: "Atomy Evening Care Foam Cleanser", precio: 79, pv: 7000 },
  { categoria: "Beleza", nombre: "Atomy Evening Care Peeling Gel", precio: 239, pv: 30000 },
  { categoria: "Beleza", nombre: "Atomy Evening Care Set", precio: 310, pv: 35000 },
  { categoria: "Beleza", nombre: "Atomy Homme All-in-One", precio: 178, pv: 15000 },
  { categoria: "Beleza", nombre: "Atomy Homme Essence", precio: 144, pv: 15000 },
  { categoria: "Beleza", nombre: "Atomy Homme Lotion", precio: 169, pv: 21000 },
  { categoria: "Beleza", nombre: "Atomy Homme Multi-Action Moisturizing", precio: 99, pv: 15000 },
  { categoria: "Beleza", nombre: "Atomy Homme Nutrition Cream", precio: 169, pv: 21000 },
  { categoria: "Beleza", nombre: "Atomy Lip Gel Balm", precio: 104, pv: 5300 },
  { categoria: "Beleza", nombre: "Atomy Lip Treatment", precio: 51, pv: 7000 },
  { categoria: "Beleza", nombre: "Atomy Lotion", precio: 124, pv: 15000 },
  { categoria: "Beleza", nombre: "Atomy Mineral Sunscreen", precio: 76, pv: 11500 },
  { categoria: "Beleza", nombre: "Atomy The Fame Absolute Serum", precio: 169, pv: 27000 },
  { categoria: "Beleza", nombre: "Atomy The Fame Nutrition Cream", precio: 169, pv: 21000 },
  { categoria: "Beleza", nombre: "Atomy The Fame Toner", precio: 124, pv: 27000 },
  { categoria: "Beleza", nombre: "Atomy Ultra Rich Body Cream", precio: 130, pv: 15000 },
  { categoria: "Promozioni", nombre: "Atomy Maestria 300K PV", precio: 2155, pv: 300000 },
  { categoria: "Altro", nombre: "Atomy Catálogo Produtos 20 Unidades", precio: 40, pv: 0 },
  { categoria: "Altro", nombre: "Atomy Cenário de Vida", precio: 15, pv: 0 },
  ],
  CA: [
  { categoria: "Personal Care", nombre: "Absolute Conditioner (500ml)", precio: 24, pv: 8000 },
  { categoria: "Personal Care", nombre: "Absolute Feminine Wash (160ml)", precio: 16, pv: 5500 },
  { categoria: "Personal Care", nombre: "Absolute Homme Wash (400ml)", precio: 16, pv: 6300 },
  { categoria: "Personal Care", nombre: "Absolute Shampoo (500ml)", precio: 24, pv: 8000 },
  { categoria: "Personal Care", nombre: "Aidam Cleanser (200ml)", precio: 8, pv: 2000 },
  { categoria: "Personal Care", nombre: "Body Lotion (300ml)", precio: 12, pv: 3200 },
  { categoria: "Personal Care", nombre: "Hair Essential Oil (100ml)", precio: 18, pv: 5500 },
  { categoria: "Personal Care", nombre: "Hand Cream (300ml)", precio: 18, pv: 7000 },
  { categoria: "Personal Care", nombre: "Hand Lotion (400ml)", precio: 18, pv: 7000 },
  { categoria: "Personal Care", nombre: "Hand Soap (300ml)", precio: 4.5, pv: 1000 },
  { categoria: "Personal Care", nombre: "Hand Therapy 4 Kit (30ml x4 Tubes)", precio: 20, pv: 7000 },
  { categoria: "Personal Care", nombre: "Herbal Body Cleanser (500ml)", precio: 13, pv: 4000 },
  { categoria: "Personal Care", nombre: "Herbal Hair Conditioner (500ml)", precio: 17, pv: 6000 },
  { categoria: "Personal Care", nombre: "Herbal Hair Shampoo (500ml)", precio: 17, pv: 6000 },
  { categoria: "Personal Care", nombre: "Herbday (Large) (10 Pads x4 Packs)", precio: 19, pv: 4500 },
  { categoria: "Personal Care", nombre: "Herbday (Medium) (10 Pads x4 Packs)", precio: 18, pv: 4000 },
  { categoria: "Personal Care", nombre: "Herbday (Panty Liner) (20 Pads x4 Packs)", precio: 18, pv: 4000 },
  { categoria: "Personal Care", nombre: "Kids Toothbrush (8 Brushes)", precio: 13, pv: 4500 },
  { categoria: "Personal Care", nombre: "Oral Care System (4 Sets)", precio: 19, pv: 7000 },
  { categoria: "Personal Care", nombre: "Root Vital Hair Care Set", precio: 75, pv: 32000 },
  { categoria: "Personal Care", nombre: "Root Vital Hair Shampoo (500ml)", precio: 28, pv: 9500 },
  { categoria: "Personal Care", nombre: "Root Vital Scalp & Hair Pack (200ml)", precio: 24, pv: 8500 },
  { categoria: "Personal Care", nombre: "Root Vital Scalp Ampoule (15ml)", precio: 24, pv: 9000 },
  { categoria: "Personal Care", nombre: "Saengmodan Hair Tonic (200ml)", precio: 18, pv: 6000 },
  { categoria: "Personal Care", nombre: "Scalpcare Conditioner (500ml)", precio: 19, pv: 5720 },
  { categoria: "Personal Care", nombre: "Scalpcare Shampoo (500ml)", precio: 19, pv: 5720 },
  { categoria: "Personal Care", nombre: "Sensitive Teeth and Gums Toothpaste (100g x3 Tubes)", precio: 16, pv: 5500 },
  { categoria: "Personal Care", nombre: "Toothbrush (8 Brushes)", precio: 13, pv: 5500 },
  { categoria: "Personal Care", nombre: "Toothpaste (200g x 5 Tubes)", precio: 25, pv: 4000 },
  { categoria: "Personal Care", nombre: "Toothpaste (50g x4 Tubes)", precio: 9, pv: 3000 },
  { categoria: "Home", nombre: "(L) Eco Zipper Bag (22 Bags)", precio: 3.5, pv: 520 },
  { categoria: "Home", nombre: "(S) Eco Zipper Bag (22 Bags)", precio: 3, pv: 455 },
  { categoria: "Home", nombre: "Dishwasher Tablet 12 (14g x60 Tablets)", precio: 25, pv: 7500 },
  { categoria: "Home", nombre: "Eco Glove (120 Pieces)", precio: 5, pv: 1000 },
  { categoria: "Home", nombre: "Hand Soap (400ml)", precio: 4.5, pv: 1000 },
  { categoria: "Home", nombre: "Latex Gloves (M 2 Set)", precio: 6.5, pv: 1300 },
  { categoria: "Home", nombre: "Laundry Detergent Pods (7.25g x100 Pods)", precio: 30, pv: 9000 },
  { categoria: "Home", nombre: "Liquid Detergent (67.43 FL Oz)", precio: 18, pv: 4400 },
  { categoria: "Home", nombre: "MediCook 5.4L Wok", precio: 270, pv: 110000 },
  { categoria: "Home", nombre: "Scratch Free Scrubber (4 Packs)", precio: 6, pv: 1500 },
  { categoria: "Home", nombre: "Sheet Laundry Detergent (30 Sheets)", precio: 16, pv: 5000 },
  { categoria: "Home", nombre: "Stainless Scrubber (2 Packs)", precio: 5, pv: 750 },
  { categoria: "Home", nombre: "Tape Cleaner (1 Roller + 3 Refills)", precio: 22, pv: 4500 },
  { categoria: "Home", nombre: "Tape Cleaner Refill (3 Refills)", precio: 15, pv: 3000 },
  { categoria: "Food", nombre: "(36-Pack) Olive Oil Grilled Laver (5g x36 Packs)", precio: 28, pv: 3200 },
  { categoria: "Food", nombre: "[4 Set] Organic Coconut Sugar (250g x4)", precio: 30, pv: 7500 },
  { categoria: "Food", nombre: "[4 Sets] Fermented Noni Concentrate (38ml x24 Pouches)", precio: 320, pv: 130000 },
  { categoria: "Food", nombre: "[5+1 CHALLENGE] Fermented Noni Concentrate (947ml x6 Bottles)", precio: 400, pv: 160000 },
  { categoria: "Food", nombre: "Apple Jelly Stick (15g x28 Sachets)", precio: 40, pv: 18000 },
  { categoria: "Food", nombre: "Cafe Arabica (12.1g x50 Packets)", precio: 18, pv: 1800 },
  { categoria: "Food", nombre: "Cafe Arabica Black (1.6g x80 Packets)", precio: 20, pv: 3900 },
  { categoria: "Food", nombre: "Cafe Arabica Zero Sugar 100T", precio: 47, pv: 5000 },
  { categoria: "Food", nombre: "Fermented Noni Concentrate (38ml x24 Pouches)", precio: 85, pv: 35000 },
  { categoria: "Food", nombre: "Fermented Noni Concentrate (947ml x1 Bottle)", precio: 80, pv: 32000 },
  { categoria: "Food", nombre: "Organic Coconut Sugar (250g)", precio: 9, pv: 2200 },
  { categoria: "Food", nombre: "Potato Ramen (114g x4 packs)", precio: 9, pv: 1000 },
  { categoria: "Food", nombre: "Potato Ramen Mild (113g x4 packs)", precio: 9, pv: 1000 },
  { categoria: "Food", nombre: "Potato Spicy Cold Noodles (4 packs)", precio: 9, pv: 1000 },
  { categoria: "Food", nombre: "Puer Tea (1g x30 Sachets)", precio: 40, pv: 14000 },
  { categoria: "Food", nombre: "Triple Up Protein (25g x30 Sachets)", precio: 69, pv: 26000 },
  { categoria: "Health", nombre: "100% Pure Spirulina (120 Tablets)", precio: 30, pv: 12000 },
  { categoria: "Health", nombre: "[1 Set] Mordant Collagen (x10 Bottles per set)", precio: 112, pv: 112000 },
  { categoria: "Health", nombre: "[4 Set] Bitter Melon Capsule (60 Capsules x4)", precio: 352, pv: 150000 },
  { categoria: "Health", nombre: "Bitter Melon Capsule (60 Capsules)", precio: 99, pv: 30000 },
  { categoria: "Health", nombre: "Derma Calming Sun Stick (19g)", precio: 16, pv: 6500 },
  { categoria: "Health", nombre: "Eye Lutein (90 Softgels)", precio: 43, pv: 51000 },
  { categoria: "Health", nombre: "Kbeka Omega 3 (180 Softgels)", precio: 29, pv: 20000 },
  { categoria: "Health", nombre: "Mineral Gel Patch (65 Patches)", precio: 48, pv: 53000 },
  { categoria: "Health", nombre: "Mineral Sunscreen (Tube)", precio: 22, pv: 6000 },
  { categoria: "Health", nombre: "Mordant Collagen (30 Sachets)", precio: 30, pv: 12000 },
  { categoria: "Health", nombre: "Pomegranate Beauty (10g x30 Sachets)", precio: 93, pv: 30000 },
  { categoria: "Health", nombre: "Probiotics 10 Plus (2g x60 Sachets)", precio: 43, pv: 58000 },
  { categoria: "Health", nombre: "Psyllium Husk (5g x30 Sachets)", precio: 38, pv: 16000 },
  { categoria: "Health", nombre: "Pure Tea (10g x40 Sachets)", precio: 40, pv: 16000 },
  { categoria: "Health", nombre: "Rhodiola Milk Thistle (600mg x90 Tablets)", precio: 33, pv: 12000 },
  { categoria: "Health", nombre: "Vital Mega Vitamin C 2000 (2g x90 Sachets)", precio: 45, pv: 21000 },
  { categoria: "Health", nombre: "Vitamin C (2g x90 Sachets)", precio: 27, pv: 15000 },
  { categoria: "HemoHIM", nombre: "[4 Sets] HemoHIM (30 Sachets per Set)", precio: 440, pv: 300000 },
  { categoria: "HemoHIM", nombre: "[4 Sets] HemoHIM (60 Sachets per Set)", precio: 500, pv: 240000 },
  { categoria: "HemoHIM", nombre: "HemoHIM (30 Sachets)", precio: 106, pv: 70000 },
  { categoria: "HemoHIM", nombre: "HemoHIM (60 Sachets)", precio: 130, pv: 60000 },
  { categoria: "Beauty", nombre: "Absolute Ampoule (40ml)", precio: 59, pv: 29000 },
  { categoria: "Beauty", nombre: "Absolute Eye-Complex (40ml)", precio: 55, pv: 26000 },
  { categoria: "Beauty", nombre: "Absolute Lotion (135ml)", precio: 50, pv: 23000 },
  { categoria: "Beauty", nombre: "Absolute Nutrition Cream (50ml)", precio: 50, pv: 23000 },
  { categoria: "Beauty", nombre: "Absolute Oil Serum Mist (80ml)", precio: 27, pv: 13000 },
  { categoria: "Beauty", nombre: "Absolute Serum (50ml)", precio: 55, pv: 26000 },
  { categoria: "Beauty", nombre: "Absolute Skincare Set (6 Pieces)", precio: 305, pv: 150000 },
  { categoria: "Beauty", nombre: "Absolute Toner (150ml)", precio: 50, pv: 23000 },
  { categoria: "Beauty", nombre: "Adelica Soft Brow Pencil (0.3g Brown)", precio: 11, pv: 4000 },
  { categoria: "Beauty", nombre: "BB Cream (40ml)", precio: 15, pv: 4000 },
  { categoria: "Beauty", nombre: "Cleansing Essential Mini Kit (6pcs)", precio: 15, pv: 3500 },
  { categoria: "Beauty", nombre: "Daily Expert Mask Brightening (10 Sheets)", precio: 16, pv: 4500 },
  { categoria: "Beauty", nombre: "Daily Expert Mask Firming (10 Sheets)", precio: 16, pv: 4500 },
  { categoria: "Beauty", nombre: "Daily Expert Mask Moisturizing (10 Sheets)", precio: 16, pv: 4500 },
  { categoria: "Beauty", nombre: "Deep Cleanser (150ml)", precio: 14, pv: 4000 },
  { categoria: "Beauty", nombre: "Deep Pure Cleansing Oil (150ml)", precio: 25, pv: 7500 },
  { categoria: "Beauty", nombre: "Derma Calming Sun Stick (16g)", precio: 16, pv: 5000 },
  { categoria: "Beauty", nombre: "Derma Real Cica Set (3 Pieces)", precio: 90, pv: 42000 },
  { categoria: "Beauty", nombre: "Evening Care 4 Set", precio: 50, pv: 16000 },
  { categoria: "Beauty", nombre: "Foam Cleanser (150ml)", precio: 14, pv: 4000 },
  { categoria: "Beauty", nombre: "Healthy Glow Base (33ml)", precio: 17, pv: 5000 },
  { categoria: "Beauty", nombre: "Homme Energizing All in One (80ml)", precio: 29, pv: 14000 },
  { categoria: "Beauty", nombre: "Lip Glow (3.3g)", precio: 14, pv: 5300 },
  { categoria: "Beauty", nombre: "Lip Treatment (3.9g)", precio: 7.5, pv: 2200 },
  { categoria: "Beauty", nombre: "Mineral Sunscreen (75ml)", precio: 22, pv: 8000 },
  { categoria: "Beauty", nombre: "Peel-Off Mask (120ml)", precio: 14, pv: 4000 },
  { categoria: "Beauty", nombre: "Peeling Gel (120ml)", precio: 14, pv: 4000 },
  { categoria: "Beauty", nombre: "Rose Rain Mist (130ml)", precio: 17, pv: 4800 },
  { categoria: "Beauty", nombre: "The Fame Essence (50ml)", precio: 31, pv: 14000 },
  { categoria: "Beauty", nombre: "The Fame Eye Cream (40ml)", precio: 29, pv: 13000 },
  { categoria: "Beauty", nombre: "The Fame Lotion (135ml)", precio: 29, pv: 13000 },
  { categoria: "Beauty", nombre: "The Fame Nutrition Cream (50ml)", precio: 29, pv: 13000 },
  { categoria: "Beauty", nombre: "The Fame Set (Individual Packaging)", precio: 138, pv: 66000 },
  { categoria: "Beauty", nombre: "The Fame Toner (150ml)", precio: 29, pv: 13000 },
  { categoria: "Altro", nombre: "Best Kit", precio: 595, pv: 300000 },
  { categoria: "Altro", nombre: "Essential Kit", precio: 235, pv: 100000 },
  { categoria: "Altro", nombre: "Starter Kit", precio: 128, pv: 50000 },
  { categoria: "Altro", nombre: "Tarpaulin Bag (1EA)", precio: 6, pv: 1500 },
  ],
  US: [
  { categoria: "Cura Personale", nombre: "Absolute Conditioner - Step 3", precio: 21, pv: 10000 },
  { categoria: "Cura Personale", nombre: "Absolute Hair Care Set", precio: 55, pv: 28000 },
  { categoria: "Cura Personale", nombre: "Absolute Shampoo - Step 1", precio: 21, pv: 10000 },
  { categoria: "Cura Personale", nombre: "Absolute Treatment - Step 2", precio: 15, pv: 6000 },
  { categoria: "Cura Personale", nombre: "Aidam Cleanser", precio: 7, pv: 2500 },
  { categoria: "Cura Personale", nombre: "Body Lotion", precio: 12.5, pv: 4500 },
  { categoria: "Cura Personale", nombre: "Curling Essence", precio: 10, pv: 6500 },
  { categoria: "Cura Personale", nombre: "Ethereal Patches", precio: 36, pv: 16000 },
  { categoria: "Cura Personale", nombre: "Fluoride-Free Toothpaste", precio: 13, pv: 7000 },
  { categoria: "Cura Personale", nombre: "Foot Nourishing Cream", precio: 17.5, pv: 10000 },
  { categoria: "Cura Personale", nombre: "Foot Scrub Wash", precio: 16.5, pv: 9000 },
  { categoria: "Cura Personale", nombre: "Hair & Body Set", precio: 50, pv: 25000 },
  { categoria: "Cura Personale", nombre: "Hair Essential Oil", precio: 14, pv: 6500 },
  { categoria: "Cura Personale", nombre: "Hand Cream", precio: 17, pv: 8000 },
  { categoria: "Cura Personale", nombre: "Hand Lotion", precio: 17, pv: 6600 },
  { categoria: "Cura Personale", nombre: "Hand Soap", precio: 6, pv: 2000 },
  { categoria: "Cura Personale", nombre: "Hand Therapy", precio: 18.5, pv: 8500 },
  { categoria: "Cura Personale", nombre: "Herb Day (Large)", precio: 17, pv: 5700 },
  { categoria: "Cura Personale", nombre: "Herb Day (Liner)", precio: 16, pv: 5000 },
  { categoria: "Cura Personale", nombre: "Herb Day (Medium)", precio: 16, pv: 5000 },
  { categoria: "Cura Personale", nombre: "Herbal Body Cleanser", precio: 12, pv: 5000 },
  { categoria: "Cura Personale", nombre: "Herbal Hair Conditioner", precio: 16, pv: 8000 },
  { categoria: "Cura Personale", nombre: "Herbal Hair Shampoo", precio: 14, pv: 7000 },
  { categoria: "Cura Personale", nombre: "Herbal Hair Treatment", precio: 9, pv: 4000 },
  { categoria: "Cura Personale", nombre: "Homme All-in-One Wash", precio: 18, pv: 8000 },
  { categoria: "Cura Personale", nombre: "Homme Multi-Action Cleanser", precio: 18, pv: 5000 },
  { categoria: "Cura Personale", nombre: "Kids Toothbrush (8ea)", precio: 12, pv: 6000 },
  { categoria: "Cura Personale", nombre: "Oral Care System", precio: 16, pv: 8000 },
  { categoria: "Cura Personale", nombre: "Root Vital Hair Care Set", precio: 59, pv: 33000 },
  { categoria: "Cura Personale", nombre: "Root Vital Hair Shampoo", precio: 23, pv: 10000 },
  { categoria: "Cura Personale", nombre: "Root Vital Scalp Ampoule", precio: 20, pv: 9500 },
  { categoria: "Cura Personale", nombre: "Root Vital Scalp Ampoule *3ea", precio: 55, pv: 30000 },
  { categoria: "Cura Personale", nombre: "Saengmodan Hair Tonic", precio: 17, pv: 8000 },
  { categoria: "Cura Personale", nombre: "Scalpcare Conditioner", precio: 16.5, pv: 6200 },
  { categoria: "Cura Personale", nombre: "Scalpcare Hair Care Set", precio: 55, pv: 22500 },
  { categoria: "Cura Personale", nombre: "Scalpcare Set", precio: 32, pv: 15000 },
  { categoria: "Cura Personale", nombre: "Scalpcare Shampoo", precio: 16.5, pv: 7000 },
  { categoria: "Cura Personale", nombre: "Silk Protein Hair Essence", precio: 18, pv: 8000 },
  { categoria: "Cura Personale", nombre: "Sugar Body Scrub", precio: 20, pv: 11000 },
  { categoria: "Cura Personale", nombre: "Toothbrush (8pk)", precio: 12, pv: 7000 },
  { categoria: "Cura Personale", nombre: "Toothpaste", precio: 22, pv: 6000 },
  { categoria: "Cura Personale", nombre: "Toothpaste 50g", precio: 6, pv: 4000 },
  { categoria: "Cura Personale", nombre: "Ultra Rich Body Cream", precio: 16.5, pv: 7500 },
  { categoria: "Cura Personale", nombre: "Ultra Rich Body Wash", precio: 14, pv: 6000 },
  { categoria: "Casa", nombre: "Dishwashing Liquid", precio: 12, pv: 5000 },
  { categoria: "Casa", nombre: "Fabric Detergent", precio: 17, pv: 5000 },
  { categoria: "Casa", nombre: "Fabric Softener", precio: 14, pv: 5000 },
  { categoria: "Casa", nombre: "Latex Gloves (L) *2 sets", precio: 8, pv: 3000 },
  { categoria: "Casa", nombre: "Latex Gloves (M) *2 sets", precio: 6, pv: 2000 },
  { categoria: "Casa", nombre: "Liquid Laundry Detergent", precio: 17, pv: 6000 },
  { categoria: "Casa", nombre: "MediCook 28cm Fry Pan", precio: 140, pv: 75000 },
  { categoria: "Casa", nombre: "MediCook 3.3L", precio: 200, pv: 110000 },
  { categoria: "Casa", nombre: "MediCook 5.4L Wok", precio: 260, pv: 140000 },
  { categoria: "Casa", nombre: "MediCook 5.5L", precio: 240, pv: 130000 },
  { categoria: "Casa", nombre: "O2 Bubble Power", precio: 14, pv: 6000 },
  { categoria: "Casa", nombre: "Scratch Free Scrubber", precio: 6.5, pv: 2000 },
  { categoria: "Casa", nombre: "Sheet Laundry Detergent", precio: 13, pv: 6000 },
  { categoria: "Comida", nombre: "Avocado 100% Extra Virgin Avocado Oil", precio: 18, pv: 6000 },
  { categoria: "Comida", nombre: "Cafe Arabica 50", precio: 12, pv: 4000 },
  { categoria: "Comida", nombre: "Cafe Arabica 50T *16ea", precio: 192, pv: 64000 },
  { categoria: "Comida", nombre: "Cafe Arabica Black", precio: 21, pv: 5500 },
  { categoria: "Comida", nombre: "Cafe Arabica Zero Sugar 100T", precio: 39, pv: 5000 },
  { categoria: "Comida", nombre: "Health Best Kit", precio: 150, pv: 100000 },
  { categoria: "Comida", nombre: "Manuka Honey 830+", precio: 78, pv: 35000 },
  { categoria: "Comida", nombre: "Olive Oil Grilled Laver", precio: 19, pv: 4000 },
  { categoria: "Comida", nombre: "Olive Oil Grilled Laver (36 Packs)", precio: 20, pv: 3000 },
  { categoria: "Comida", nombre: "Potato Ramen *4 pack", precio: 9, pv: 1300 },
  { categoria: "Comida", nombre: "Puer Tea", precio: 35, pv: 16000 },
  { categoria: "Cura della Salute", nombre: "Applena Queen", precio: 39, pv: 15000 },
  { categoria: "Cura della Salute", nombre: "Applephenon Jelly Stick", precio: 32, pv: 15000 },
  { categoria: "Cura della Salute", nombre: "Bitter Melon", precio: 46, pv: 22000 },
  { categoria: "Cura della Salute", nombre: "Eye Health Luteanthin", precio: 45, pv: 28000 },
  { categoria: "Cura della Salute", nombre: "Eye Lutein", precio: 35, pv: 11000 },
  { categoria: "Cura della Salute", nombre: "Green Propolis Spray", precio: 26, pv: 11000 },
  { categoria: "Cura della Salute", nombre: "HemoHIM", precio: 105, pv: 66000 },
  { categoria: "Cura della Salute", nombre: "HemoHIM *4 Sets", precio: 405, pv: 300000 },
  { categoria: "Cura della Salute", nombre: "Insect Memory Up", precio: 40, pv: 21000 },
  { categoria: "Cura della Salute", nombre: "Iron", precio: 17, pv: 15000 },
  { categoria: "Cura della Salute", nombre: "ITG Omega 3", precio: 35, pv: 8900 },
  { categoria: "Cura della Salute", nombre: "Korean Red Ginseng Jelly Stick", precio: 47, pv: 27000 },
  { categoria: "Cura della Salute", nombre: "Mangosteen", precio: 95, pv: 34000 },
  { categoria: "Cura della Salute", nombre: "Organic Fermented Noni Concentrate (Bottle)", precio: 57, pv: 34000 },
  { categoria: "Cura della Salute", nombre: "Organic Fermented Noni Concentrate (Pouch)", precio: 62, pv: 34000 },
  { categoria: "Cura della Salute", nombre: "Plant Calcium", precio: 32, pv: 13000 },
  { categoria: "Cura della Salute", nombre: "Pomegranate Beauty", precio: 77, pv: 37000 },
  { categoria: "Cura della Salute", nombre: "Power Vits Energizer", precio: 39, pv: 22000 },
  { categoria: "Cura della Salute", nombre: "Psyllium Husk", precio: 32, pv: 21000 },
  { categoria: "Cura della Salute", nombre: "Pure Spirulina 100%", precio: 26, pv: 12000 },
  { categoria: "Cura della Salute", nombre: "Rhodiola Milk Thistle", precio: 35, pv: 15000 },
  { categoria: "Cura della Salute", nombre: "Saw Palmetto", precio: 38, pv: 15000 },
  { categoria: "Cura della Salute", nombre: "US Probiotics", precio: 40, pv: 22000 },
  { categoria: "Cura della Salute", nombre: "Vital Color Vitamin C", precio: 24, pv: 11000 },
  { categoria: "Cura della Salute", nombre: "Vital Mega Vitamin C 2000", precio: 39, pv: 22000 },
  { categoria: "Cura della Salute", nombre: "Vitamin B Complex", precio: 22, pv: 10000 },
  { categoria: "Cura della Salute", nombre: "Vitamin D3", precio: 32, pv: 12000 },
  { categoria: "HemoHIM", nombre: "HemoHIM 30 Pack", precio: 80, pv: 75000 },
  { categoria: "HemoHIM", nombre: "HemoHIM Manual (English) *1ea", precio: 0.4, pv: 0 },
  { categoria: "Bellezza", nombre: "3-Seconds Beauty Water", precio: 16, pv: 7500 },
  { categoria: "Bellezza", nombre: "A.C. Expert Foam Cleanser", precio: 17.5, pv: 11000 },
  { categoria: "Bellezza", nombre: "A.C. Expert Serum", precio: 25, pv: 15000 },
  { categoria: "Bellezza", nombre: "A.C. Expert Spot Solution", precio: 22, pv: 12000 },
  { categoria: "Bellezza", nombre: "A.C. Expert System Set", precio: 84, pv: 55000 },
  { categoria: "Bellezza", nombre: "A.C. Expert Toner", precio: 24, pv: 15000 },
  { categoria: "Bellezza", nombre: "Absolute Ampoule", precio: 50, pv: 33000 },
  { categoria: "Bellezza", nombre: "Absolute Eye-Complex", precio: 48, pv: 30000 },
  { categoria: "Bellezza", nombre: "Absolute Lotion", precio: 45, pv: 27000 },
  { categoria: "Bellezza", nombre: "Absolute Nutrition Cream", precio: 45, pv: 27000 },
  { categoria: "Bellezza", nombre: "Absolute Oil Serum Mist", precio: 26, pv: 17000 },
  { categoria: "Bellezza", nombre: "Absolute Serum", precio: 48, pv: 30000 },
  { categoria: "Bellezza", nombre: "Absolute Skincare Set", precio: 260, pv: 175000 },
  { categoria: "Bellezza", nombre: "Absolute Spot-Out Cream", precio: 39, pv: 22000 },
  { categoria: "Bellezza", nombre: "Absolute Spot-Out Essence", precio: 45, pv: 26000 },
  { categoria: "Bellezza", nombre: "Absolute Toner", precio: 45, pv: 27000 },
  { categoria: "Bellezza", nombre: "Adelica Long-Lash Mascara", precio: 15.5, pv: 9000 },
  { categoria: "Bellezza", nombre: "Adelica Loose Setting Powder", precio: 30.5, pv: 19000 },
  { categoria: "Bellezza", nombre: "Adelica Mood on Eye Palette", precio: 25, pv: 15000 },
  { categoria: "Bellezza", nombre: "Adelica Volume Mascara", precio: 15.5, pv: 9000 },
  { categoria: "Bellezza", nombre: "BB Cream", precio: 10, pv: 3000 },
  { categoria: "Bellezza", nombre: "Cream Mist", precio: 17, pv: 10000 },
  { categoria: "Bellezza", nombre: "Daily Expert Mask Brightening", precio: 12.5, pv: 6000 },
  { categoria: "Bellezza", nombre: "Daily Expert Mask Firming", precio: 12.5, pv: 6000 },
  { categoria: "Bellezza", nombre: "Daily Expert Mask Moisturizing", precio: 12.5, pv: 6000 },
  { categoria: "Bellezza", nombre: "Deep Cleanser", precio: 12, pv: 5000 },
  { categoria: "Bellezza", nombre: "Deep Pure Cleansing Oil", precio: 20, pv: 8000 },
  { categoria: "Bellezza", nombre: "Derma Calming Sun Stick", precio: 13, pv: 6000 },
  { categoria: "Bellezza", nombre: "Derma Real Cica Ampoule", precio: 36, pv: 22000 },
  { categoria: "Bellezza", nombre: "Derma Real Cica Cream", precio: 25, pv: 16000 },
  { categoria: "Bellezza", nombre: "Derma Real Cica Gel Cleanser", precio: 15.5, pv: 10000 },
  { categoria: "Bellezza", nombre: "Derma Real Cica Set", precio: 76, pv: 51000 },
  { categoria: "Bellezza", nombre: "Derma Real Cica Toner", precio: 18.5, pv: 12000 },
  { categoria: "Bellezza", nombre: "Evening Care 4 Set", precio: 45, pv: 21000 },
  { categoria: "Bellezza", nombre: "Foam Cleanser", precio: 12, pv: 5000 },
  { categoria: "Bellezza", nombre: "Healthy Glow Base", precio: 16, pv: 6000 },
  { categoria: "Bellezza", nombre: "Homme Energizing All in One", precio: 25, pv: 14000 },
  { categoria: "Bellezza", nombre: "Homme Essence", precio: 20, pv: 12000 },
  { categoria: "Bellezza", nombre: "Homme Lotion", precio: 21, pv: 12000 },
  { categoria: "Bellezza", nombre: "Homme Multi-Action Cleanser", precio: 12, pv: 5500 },
  { categoria: "Bellezza", nombre: "Homme Skincare Set", precio: 58, pv: 37000 },
  { categoria: "Bellezza", nombre: "Homme Toner", precio: 21, pv: 12000 },
  { categoria: "Bellezza", nombre: "Hydra Brightening Care Set", precio: 50, pv: 32000 },
  { categoria: "Bellezza", nombre: "Hydra Brightening Cream", precio: 25, pv: 15000 },
  { categoria: "Bellezza", nombre: "Hydra Brightening Essence", precio: 26, pv: 16000 },
  { categoria: "Bellezza", nombre: "Lip Glow", precio: 14, pv: 7000 },
  { categoria: "Bellezza", nombre: "Lip Treatment", precio: 6.5, pv: 3000 },
  { categoria: "Bellezza", nombre: "Marine Ampoule Eye Patch", precio: 19, pv: 11000 },
  { categoria: "Bellezza", nombre: "Peel-Off Mask", precio: 12, pv: 5000 },
  { categoria: "Bellezza", nombre: "Peeling Gel", precio: 12, pv: 5000 },
  { categoria: "Bellezza", nombre: "Peeling Pad", precio: 12, pv: 6500 },
  { categoria: "Bellezza", nombre: "Rose Rain Mist", precio: 13, pv: 5000 },
  { categoria: "Bellezza", nombre: "Sun Stick", precio: 12, pv: 6000 },
  { categoria: "Bellezza", nombre: "Sunscreen (Beige)", precio: 12, pv: 6000 },
  { categoria: "Bellezza", nombre: "Sunscreen (White)", precio: 12, pv: 6000 },
  { categoria: "Bellezza", nombre: "Synergy Ampoule *1 Set", precio: 135, pv: 90000 },
  { categoria: "Bellezza", nombre: "Synergy Ampoule *3 Sets", precio: 400, pv: 320000 },
  { categoria: "Bellezza", nombre: "The Fame Essence", precio: 27, pv: 16000 },
  { categoria: "Bellezza", nombre: "The Fame Eye Cream", precio: 26, pv: 15000 },
  { categoria: "Bellezza", nombre: "The Fame Lotion", precio: 26, pv: 15000 },
  { categoria: "Bellezza", nombre: "The Fame Nutrition Cream", precio: 26, pv: 15000 },
  { categoria: "Bellezza", nombre: "The Fame Set", precio: 120, pv: 77000 },
  { categoria: "Bellezza", nombre: "The Fame Toner", precio: 26, pv: 15000 },
  { categoria: "Bellezza", nombre: "The Fame Travel Kit", precio: 40, pv: 15000 },
  { categoria: "Bellezza", nombre: "Travel Cleansing Kit", precio: 15, pv: 4000 },
  { categoria: "Altro", nombre: "[CHALLENGE] Noni 5+1", precio: 285, pv: 175000 },
  { categoria: "Altro", nombre: "Beauty & Personal Care Best Kit", precio: 300, pv: 200000 },
  { categoria: "Altro", nombre: "HemoBlend Kit", precio: 150, pv: 50000 },
  { categoria: "Altro", nombre: "Leaflet *50ea", precio: 15, pv: 0 },
  { categoria: "Altro", nombre: "Life Scenario (English) *10ea", precio: 10, pv: 0 },
  { categoria: "Altro", nombre: "Life Scenario (Spanish) *10ea", precio: 10, pv: 0 },
  { categoria: "Altro", nombre: "Non-Woven Fabric Shopping Bag *1ea", precio: 10, pv: 0 },
  { categoria: "Altro", nombre: "Plastic Bag *1ea", precio: 2, pv: 0 },
  { categoria: "Altro", nombre: "Shopping Bag (Blue) *1ea", precio: 1, pv: 0 },
  { categoria: "Altro", nombre: "Shopping Bag (White) *1ea", precio: 1, pv: 0 },
  ],
};

const CATALOGO_PRODUCTOS_NOTA = "Catalogo di riferimento a partire dalla tua stessa lista — Atomy aggiorna i suoi prodotti con frequenza e ogni paese ha un catalogo diverso, quindi può essere non aggiornato. Modifica, aggiungi o elimina prodotti qui per mantenerlo al passo.";

const CATALOGO_PRODUCTOS_NOTA_VACIO = "Non abbiamo ancora caricato il catalogo di questo paese. Tocca \"+ Aggiungi prodotto\" per iniziare a costruirlo (oppure invia al tuo assistente delle schermate dei prezzi/PV del tuo paese per caricarlo completo).";

const META_PV_QUINCENA = 2500000;

const MENSAJE_BIENVENIDA =
  "Hai già conquistato Sales Master — questa è la tua prossima montagna. Qui capirai come funziona il piano di compensazione completo, e pianificherai quindicina dopo quindicina con il tuo team per sfruttare ogni punto e non perdere nessun ciclaggio.";

const IDIOMAS_INFORME = [
  { id: "es", label: "Español" },
  { id: "en", label: "English" },
  { id: "fr", label: "Français" },
  { id: "it", label: "Italiano" },
  { id: "ro", label: "Română" },
  { id: "pt", label: "Português" },
];

const INFORME_I18N = {
  es: { llamadas: "Llamadas", mensajes: "Mensajes de invitación", presentaciones: "Presentaciones (Show the Plan)", reuniones: "Reuniones / consultorías",
    tituloPersonal: "📊 Mi informe semanal de actividad (Cumbre Master):", cierrePersonal: "¿Qué te parece? ¿En qué puedo mejorar esta semana?",
    tituloEquipo: "👥 Informe semanal de mi equipo (Cumbre Master):", personasRed: "Personas en mi red esta quincena", verificados: "Verificados (ya pidieron sus puntos)", pendientes: "Pendientes por verificar", pvPlaneado: "PV total planeado", pvVerificado: "PV verificado", cierreEquipo: "Aquí va el resumen de mi equipo — ¿me ayudas a revisarlo?" },
  en: { llamadas: "Calls", mensajes: "Invitation messages", presentaciones: "Presentations (Show the Plan)", reuniones: "Meetings / consultations",
    tituloPersonal: "📊 My weekly activity report (Cumbre Master):", cierrePersonal: "What do you think? How can I improve this week?",
    tituloEquipo: "👥 My team's weekly report (Cumbre Master):", personasRed: "People in my network this period", verificados: "Verified (already ordered their points)", pendientes: "Pending verification", pvPlaneado: "Total planned PV", pvVerificado: "Verified PV", cierreEquipo: "Here's my team's summary — can you help me review it?" },
  fr: { llamadas: "Appels", mensajes: "Messages d'invitation", presentaciones: "Présentations (Show the Plan)", reuniones: "Réunions / consultations",
    tituloPersonal: "📊 Mon rapport d'activité hebdomadaire (Cumbre Master) :", cierrePersonal: "Qu'en penses-tu ? Comment puis-je m'améliorer cette semaine ?",
    tituloEquipo: "👥 Rapport hebdomadaire de mon équipe (Cumbre Master) :", personasRed: "Personnes dans mon réseau cette période", verificados: "Vérifiés (ont déjà commandé leurs points)", pendientes: "En attente de vérification", pvPlaneado: "PV total prévu", pvVerificado: "PV vérifié", cierreEquipo: "Voici le résumé de mon équipe — peux-tu m'aider à le revoir ?" },
  it: { llamadas: "Chiamate", mensajes: "Messaggi di invito", presentaciones: "Presentazioni (Show the Plan)", reuniones: "Riunioni / consulenze",
    tituloPersonal: "📊 Il mio report settimanale di attività (Cumbre Master):", cierrePersonal: "Cosa ne pensi? Come posso migliorare questa settimana?",
    tituloEquipo: "👥 Report settimanale del mio team (Cumbre Master):", personasRed: "Persone nella mia rete questo periodo", verificados: "Verificati (hanno già ordinato i loro punti)", pendientes: "In attesa di verifica", pvPlaneado: "PV totale pianificato", pvVerificado: "PV verificato", cierreEquipo: "Ecco il riepilogo del mio team — mi aiuti a rivederlo?" },
  ro: { llamadas: "Apeluri", mensajes: "Mesaje de invitație", presentaciones: "Prezentări (Show the Plan)", reuniones: "Întâlniri / consultații",
    tituloPersonal: "📊 Raportul meu săptămânal de activitate (Cumbre Master):", cierrePersonal: "Ce părere ai? Cum pot îmbunătăți săptămâna asta?",
    tituloEquipo: "👥 Raportul săptămânal al echipei mele (Cumbre Master):", personasRed: "Persoane în rețeaua mea în această perioadă", verificados: "Verificați (și-au comandat deja punctele)", pendientes: "În așteptarea verificării", pvPlaneado: "PV total planificat", pvVerificado: "PV verificat", cierreEquipo: "Iată rezumatul echipei mele — mă ajuți să-l revizuim?" },
  pt: { llamadas: "Chamadas", mensajes: "Mensagens de convite", presentaciones: "Apresentações (Show the Plan)", reuniones: "Reuniões / consultorias",
    tituloPersonal: "📊 Meu relatório semanal de atividade (Cumbre Master):", cierrePersonal: "O que você acha? Como posso melhorar esta semana?",
    tituloEquipo: "👥 Relatório semanal da minha equipe (Cumbre Master):", personasRed: "Pessoas na minha rede neste período", verificados: "Verificados (já pediram seus pontos)", pendientes: "Pendentes de verificação", pvPlaneado: "PV total planejado", pvVerificado: "PV verificado", cierreEquipo: "Aqui está o resumo da minha equipe — pode me ajudar a revisar?" },
};

function informeI18n(idioma) {
  return INFORME_I18N[idioma] || INFORME_I18N.es;
}

/* ---------------------------------------------------------------
   AGENDA SETTIMANALE — routine di lavoro di un leader: chiamate e riunioni
   con affiliati, formazioni di team, riunioni di leader e Zoom.
--------------------------------------------------------------- */

const DIAS_SEMANA = [
  { id: "lunes", label: "Lunedì" },
  { id: "martes", label: "Martedì" },
  { id: "miercoles", label: "Mercoledì" },
  { id: "jueves", label: "Giovedì" },
  { id: "viernes", label: "Venerdì" },
  { id: "sabado", label: "Sabato" },
  { id: "domingo", label: "Domenica" },
];

const AGENDA_TIPOS = [
  { id: "llamada", label: "Chiamata a un socio", icon: "phone-call" },
  { id: "reunion-afiliado", label: "Riunione con un affiliato", icon: "users" },
  { id: "consultoria", label: "Consulenza / follow-up", icon: "target" },
  { id: "formacion", label: "Formazione del team", icon: "book-open" },
  { id: "reunion-lideres", label: "Riunione di leader", icon: "crown" },
];

/* ---------------------------------------------------------------
   STRUMENTI DI PIANIFICAZIONE — Gran Plan 3, Diario del mio io futuro,
   Valutazione mensile Gli 8 Passi e Piano commerciale mensile, incorporati
   in Planeador de Quincena.
--------------------------------------------------------------- */

const DIARIO_FUTURO_INTRO =
  "Scrivi una lettera o un diario dal punto di vista del tuo “io futuro” — la persona di successo in cui ti trasformerai. Racconta al tuo io di oggi come ci sei riuscito, cosa hai imparato lungo il percorso e cosa gli diresti per incoraggiarlo a continuare.";

const DIARIO_FUTURO_EJEMPLO =
  "Es.: “Oggi mi sono diplomato alla Scuola del Successo di Atomy... Tempo fa avevo un sogno e ho lavorato duramente per realizzarlo. Non è stato facile, ma ogni passo è valso la pena. Se stai leggendo questo, continua ad andare avanti — la persona che diventerai te ne sarà grata.”";

const GRAN_PLAN_3_INTRO =
  "Disegna vividamente il tuo piano a 3 anni: in che data raggiungerai ogni livello di maestria, con quanti PV di gruppo e quali entrate. Non serve compilarlo mese per mese — aggiungi le tappe che hanno senso per te, nell'anno corrispondente.";

const EVALUACION_8PASOS_CATEGORIAS = [
  { id: "metas", label: "Definizione degli obiettivi", pregunta: "Ha stabilito obiettivi di rendimento aziendale specifici per una vita equilibrata?" },
  { id: "propositos", label: "Propositi", pregunta: "Si è coinvolto attivamente negli affari e ha preso l'iniziativa di esprimere le sue opinioni agli altri con un'atteggiamento positivo?" },
  { id: "lista", label: "Fare una lista", pregunta: "Ha fatto una lista di tutte le persone che conosce intorno a sé?" },
  { id: "contacto", label: "Contatto", pregunta: "Ha dedicato un tempo specifico ogni giorno e ha comunicato con loro regolarmente?" },
  { id: "descripcion", label: "Descrizione dell'attività", pregunta: "Ha spiegato quanto segue? ① Filosofia dell'azienda ② Prodotti ③ Piano di compensazione ④ Visione aziendale" },
  { id: "seguimiento", label: "Gestione del follow-up", pregunta: "Si è preso il tempo per rispondere a qualsiasi reclamo o incomprensione su prodotti/affari entro 48 ore?" },
  { id: "consulta", label: "Consulenza", pregunta: "Ha trovato una soluzione a qualche problema grazie alle consulenze con i soci?" },
  { id: "replicacion", label: "Replicazione", pregunta: "Ha imparato dal successo del suo sponsor e condiviso la sua conoscenza con i suoi soci?" },
];

/* ---------------------------------------------------------------
   LISTA DE CONTACTOS — nivel de interés y estado (consumidor/socio)
--------------------------------------------------------------- */

const CONTACTO_NIVELES = ["Caldo", "Tiepido", "Freddo"];
const CONTACTO_ESTADOS = ["Da contattare", "Contattato", "Presentazione", "Socio", "Consumatore", "Scartato"];

/* ---------------------------------------------------------------
   RETO 7×7 — ciclo settimanale di 7 giorni per far crescere l'attività
   (contattare → presentare → raccomandare → seguire → chiudere → duplicare → ripetere)
--------------------------------------------------------------- */

const RETO_7X7_INTRO =
  "Il Reto 7×7 è il tuo lavoro quotidiano per far crescere l'attività: 7 giorni, un ciclo completo. Completalo ogni settimana, durante queste 4 settimane, e poi ripetilo per sempre — questa è la chiave della duplicazione.";

const RETO_7X7_DIAS = [
  {
    id: 1,
    icono: "flame",
    titulo: "Definisci e preparati",
    frase: "“Se non ho un obiettivo, non ho una direzione.”",
    contenido: [
      "1. Definisci il tuo obiettivo dei prossimi 7 giorni (quante conversazioni, presentazioni o iscrizioni vuoi ottenere).",
      "2. Fai una lista di 30 persone.",
      "3. Classifica i tuoi contatti: clienti potenziali, persone interessate al benessere, persone interessate a generare reddito.",
      "4. Scegli i tuoi primi 10 contatti per iniziare domani.",
      "Non vendere ancora nulla: prima costruiamo la lista.",
      "Missione del giorno: 30 nomi prima di dormire.",
    ],
    checklist: [
      "Ho definito il mio obiettivo dei prossimi 7 giorni.",
      "Ho fatto la mia lista di 30 persone e ho classificato i miei contatti.",
      "Ho scelto i miei primi 10 contatti — missione: 30 nomi prima di dormire.",
    ],
    quiz: {
      pregunta: "Quanti nomi è la missione di oggi, prima di dormire?",
      opciones: ["10", "30", "100"],
      correcta: 1,
    },
  },
  {
    id: 2,
    icono: "phone-call",
    titulo: "Apri conversazioni",
    frase: "“10 conversazioni vere.”",
    contenido: [
      "Contatta personalmente 10 persone della tua lista. Non inviare subito un catalogo: prima conversa.",
      "Esempio di copione: “Ciao, sto partecipando a una sfida di 7 giorni per sviluppare il mio progetto di benessere ed economia. Sto cercando alcune persone a cui poter mostrare come funziona. Ti andrebbe che te ne parlassi?”",
      "Se risponde di sì: “Perfetto 😊. Ti faccio una spiegazione molto breve e tu mi dici se può interessarti.”",
      "Regola d'oro: chiedi → ascolta → identifica il bisogno → presenta.",
      "Missione del giorno: 10 conversazioni.",
    ],
    checklist: [
      "Ho contattato personalmente 10 persone della mia lista.",
      "Ho usato il copione di conversazione invece di inviare un catalogo diretto.",
    ],
    quiz: {
      pregunta: "Prima di presentare prodotti o l'attività, cosa devi fare per primo?",
      opciones: ["Inviare un catalogo", "Conversare e ascoltare", "Niente, andare direttamente alla vendita"],
      correcta: 1,
    },
  },
  {
    id: 3,
    icono: "presentation",
    titulo: "Raccomandare",
    frase: "“Non vendo prodotti. Scopro bisogni.”",
    contenido: [
      "Oggi conversi per scoprire: quale prodotto usano attualmente?, quale bisogno vogliono soddisfare?, quali prodotti comprano regolarmente?, sono interessati a conoscere un'alternativa d'acquisto?",
      "Dopo aver ascoltato, segui la sequenza: Raccomanda → Spiega → Invita.",
      "Esempio: “Dimmi, quali prodotti usi normalmente per la cura personale o il benessere?” Dopo aver ascoltato: “Ho proprio un'alternativa che potrebbe interessarti. Vuoi che ti mostri come funziona?”",
      "Missione del giorno: presentare prodotti a persone con un bisogno reale.",
    ],
    checklist: [
      "Ho conversato per scoprire bisogni reali, senza vendere alla cieca.",
      "Ho presentato prodotti a persone con un bisogno reale individuato.",
    ],
    quiz: {
      pregunta: "Qual è la sequenza corretta del Giorno 3?",
      opciones: ["Raccomanda → Spiega → Invita", "Vendi → Incassa → Spedisci", "Invita → Vendi → Dimentica"],
      correcta: 0,
    },
  },
  {
    id: 4,
    icono: "users",
    titulo: "Presentare l'opportunità",
    frase: "“Non tutti vogliono comprare. Alcuni vogliono costruire.”",
    contenido: [
      "Cerca persone che vogliono: generare entrate aggiuntive, comprare in modo intelligente, raccomandare prodotti o costruire un'attività.",
      "Mini presentazione in 4 domande: Cos'è Atomy? Un'azienda internazionale di vendita diretta. Cosa troviamo? Prodotti di diverse categorie. Come funziona? Consumare → Raccomandare → Sviluppare clienti e team. Cosa cerchiamo? Costruire un'attività attraverso un sistema che possiamo ripetere e insegnare.",
      "Missione del giorno: presentare l'opportunità ad almeno 3 persone.",
    ],
    checklist: ["Ho presentato l'opportunità di business ad almeno 3 persone."],
    quiz: {
      pregunta: "Cosa cerchiamo secondo la mini presentazione in 4 domande?",
      opciones: ["Vendere il più rapidamente possibile", "Costruire un'attività con un sistema che possiamo ripetere e insegnare", "Convincere senza ascoltare"],
      correcta: 1,
    },
  },
  {
    id: 5,
    icono: "clipboard-list",
    titulo: "Follow-up",
    frase: "La fortuna è nel follow-up.",
    contenido: [
      "Oggi ricontatti: persone che hanno chiesto, persone che hanno visto la presentazione, persone che hanno detto “fammi pensare”, persone che hanno mostrato interesse.",
      "Esempio — riprendere il contatto: “Ciao 😊. Volevo sapere cosa ne pensi di quello di cui abbiamo parlato l'altro giorno. C'è stato qualcosa che ti ha colpito in particolare?”",
      "Esempio — se dice “ci devo pensare”: “Certo, prenditi il tuo tempo. Quale parte è quella che vuoi pensare: il prodotto, l'investimento o come funziona l'attività?”",
      "Esempio — se dice “non ho soldi”: “Ti capisco. Non voglio che tu faccia qualcosa che non è nelle tue possibilità. Possiamo iniziare parlando del modello e di come approfittare degli acquisti che già fai abitualmente.”",
      "Un messaggio al momento giusto può aprire una grande opportunità.",
      "Missione del giorno: fare follow-up su tutte le conversazioni aperte.",
    ],
    checklist: [
      "Ho fatto follow-up su tutte le mie conversazioni aperte.",
      "Ho ripreso contatto con chi ha detto “fammi pensare”.",
      "Ho ripreso contatto con chi ha mostrato interesse o ha visto la mia presentazione.",
    ],
    quiz: {
      pregunta: "Secondo il Reto 7×7, dove sta la fortuna?",
      opciones: ["Nel parlare solo con gente nuova", "Nel follow-up", "Nell'inviare un catalogo e basta"],
      correcta: 1,
    },
  },
  {
    id: 6,
    icono: "repeat",
    titulo: "Duplicare",
    frase: "“Non farlo da solo.”",
    contenido: [
      "Il ciclo della duplicazione: Io lo faccio → Ti insegno → Tu lo fai → Tu lo insegni.",
      "Invita una persona interessata a fare insieme a te: la sua lista di contatti, le sue prime conversazioni, la sua prima presentazione, il suo primo follow-up.",
      "Ogni azione conta. La sfida non finisce: inizia il ciclo! Insieme arriviamo più lontano.",
      "Missione del giorno: aiutare una persona a iniziare il processo.",
    ],
    checklist: [
      "Ho invitato una persona interessata a percorrere il processo con me.",
      "Ho aiutato quella persona a iniziare la propria lista, conversazioni, presentazione o follow-up.",
    ],
    quiz: {
      pregunta: "Qual è il ciclo della duplicazione del Reto 7×7?",
      opciones: [
        "Io lo faccio → Ti insegno → Tu lo fai → Tu lo insegni",
        "Io vendo → Tu compri → Fine",
        "Io decido → Tu obbedisci",
      ],
      correcta: 0,
    },
  },
  {
    id: 7,
    icono: "check",
    titulo: "Valutare, chiudere e ripetere",
    frase: "“I risultati si misurano.”",
    contenido: [
      "Oggi rivediamo: quante persone ho contattato?, quante hanno risposto?, quante presentazioni ho fatto?, quanti acquisti ho ottenuto?, quante persone sono interessate all'attività?, chi devo continuare ad accompagnare?",
      "La sfida non finisce qui: inizia il ciclo! Contattare → Presentare → Raccomandare → Seguire → Chiudere → Duplicare → Ripetere.",
      "Cosa succederebbe alla tua attività se nelle prossime settimane facessi questo processo ancora e ancora? Non devi farlo alla perfezione. Devi farlo.",
      "Registra i tuoi risultati della settimana qui sotto e condividili con il tuo sponsor.",
    ],
    checklist: [
      "Ho contato quante persone ho contattato, quante hanno risposto e quante presentazioni ho fatto.",
      "Ho identificato chi devo continuare ad accompagnare.",
      "Ho capito che il ciclo Contattare → Presentare → Raccomandare → Seguire → Chiudere → Duplicare → Ripetere non finisce, si ripete.",
    ],
    quiz: {
      pregunta: "Alla fine del Reto 7×7, cosa bisogna fare?",
      opciones: ["Fermarsi, è già finito", "Ripetere il ciclo", "Aspettare che altri ti contattino"],
      correcta: 1,
    },
  },
];

const EVALUACION_8PASOS_BANDAS = [
  { min: 0, max: 10, texto: "Sta appena iniziando. Guardi i video di formazione sugli otto passi verso il successo mentre avanza." },
  { min: 11, max: 20, texto: "È possibile che la sua attività avanzi lentamente. Provi ad aumentare la sua passione e il suo impegno." },
  { min: 21, max: 30, texto: "È impegnato a stare in testa. Presti attenzione al suo ambiente per non trascurare nulla." },
  { min: 31, max: 40, texto: "Sta perfezionando gli otto passi verso il successo e serve da modello per il suo sponsor e i suoi soci commerciali." },
];
