/* ---------------------------------------------------------------
   LICENCIA — marca de agua sutil por comprador.
   Antes de desplegar una copia de esta app para un líder que la haya
   comprado, cambia el valor de abajo con su nombre (y opcionalmente su
   rango) y despliega esa copia con un nombre de proyecto propio en Vercel.
   No es un candado técnico — es una firma visible en la app que deja
   claro de quién es esa copia si alguna vez circula fuera de su equipo.
   Déjalo en "" para una copia sin licencia asignada (uso propio, demos).
--------------------------------------------------------------- */
const LICENCIA_TITULAR = "";

/* ---------------------------------------------------------------
   CONTENIDO — Cumbre Master: Plan de Compensación (Sales Master → Imperial Master)
   Fuente: documento oficial de distribución de comisiones (Colombia, en COP).
   Los valores en USD son una conversión aproximada de referencia (~4.000 COP = 1 USD),
   sujeta a la tasa de cambio (TRM) real de cada momento.
--------------------------------------------------------------- */

const DISTRIBUCION = {
  intro: "Del monto total generado por las ventas de la compañía, el 35% se reserva para comisiones e incentivos. Ese 35% se convierte en el 100% de los PV que se reparten así:",
  partes: [
    { pct: "44%", nombre: "Comisión General", detalle: "Se reparte entre todos los miembros, según su nivel de grado y puntaje.", icon: "users" },
    { pct: "20%", nombre: "Comisión de Maestría", detalle: "Se reparte entre quienes ya alcanzaron un rango de Maestría (Sales Master en adelante).", icon: "mountain-flag" },
    { pct: "6%", nombre: "Comisión de Centro de Educación", detalle: "Va al centro educativo al que perteneces, para cubrir sus gastos operativos.", icon: "book-open" },
    { pct: "30%", nombre: "Utilidad neta de la compañía", detalle: "Es la parte que queda para Atomy.", icon: "package" },
  ],
  notaPeriodo: "El período de acumulación de puntos es siempre del 1 al 15, y del 16 al fin de mes — es decir, dos quincenas por mes.",
};

const COMISION_GENERAL = [
  { nivel: "8.º", puntos: "5 puntos", condicion: "Representante de Ventas — acumulado de 10.000 a 299.999 PV personales.", piernaDebil: "≥ 300.000 PV" },
  { nivel: "7.º", puntos: "15 puntos", condicion: "Agente — mínimo 300.000 PV personales, o pierna débil con 600.000 PV acumulados el mes anterior.", piernaDebil: "≥ 300.000 PV" },
  { nivel: "6.º", puntos: "30 puntos", condicion: "Agente Especial — mínimo 700.000 PV personales, o pierna débil con 1,4M PV el mes anterior.", piernaDebil: "≥ 700.000 PV" },
  { nivel: "5.º", puntos: "60 puntos", condicion: "Distribuidor — mínimo 1,5M PV personales, o pierna débil con 3M PV el mes anterior.", piernaDebil: "≥ 1.500.000 PV" },
  { nivel: "4.º", puntos: "90 puntos", condicion: "Distribuidor Especial — mínimo 2,4M PV personales, o pierna débil con 4,8M PV el mes anterior.", piernaDebil: "≥ 2.400.000 PV" },
  { nivel: "3.º", puntos: "150 puntos", condicion: "Continúa la escala de Distribuidor Especial, con mayor volumen de pierna débil.", piernaDebil: "≥ 6.000.000 PV" },
  { nivel: "2.º", puntos: "250 puntos", condicion: "Continúa la escala de Distribuidor Especial, con mayor volumen de pierna débil.", piernaDebil: "≥ 20.000.000 PV" },
  { nivel: "1.º", puntos: "300 puntos", condicion: "Continúa la escala de Distribuidor Especial, con mayor volumen de pierna débil.", piernaDebil: "≥ 50.000.000 PV" },
];

const COMISION_GENERAL_NOTA = "Las comisiones se liquidan el martes siguiente, tomando el acumulado diario desde el miércoles hasta ese martes (la fecha exacta puede variar según el banco local). Tus PV personales siempre se suman a tu pierna débil.";

const RANGOS_MASTER = [
  {
    n: 0, nombre: "Sales Master", icon: "mountain-flag",
    prerrequisito: "Mínimo 2.500.000 PV grupales en cada pierna y 700.000 PV personales. Si el total de PV de tu pierna débil supera los 300.000 PV, los PV personales que generes durante el período pueden sumarse a esa pierna para completar la Maestría.",
    comisionMaestria: "10% del total de PV de la compañía, repartido en partes iguales entre todos los Sales Master.",
    promocion: "Bono de $1.500.000 COP (≈ $375 USD) la primera vez que alcanzas el rango, transferido directamente a tu cuenta.",
    criterio: "Sin restricciones para ascender — solo debes cumplir el prerrequisito de esta quincena.",
    montos: [{ etiqueta: "Bono al alcanzar el rango", cop: 1500000 }],
  },
  {
    n: 1, nombre: "Diamond Master", icon: "gem",
    prerrequisito: "Mínimo 2 Sales Master en cada pierna, y 1.500.000 PV personales.",
    comisionMaestria: "5% del total de PV, repartido entre Diamond Master y las maestrías superiores.",
    promocion: "Bono de $1.500.000 COP (≈ $375 USD) la primera vez, más un bono de ascenso de aproximadamente $3.000.000 COP (≈ $750 USD).",
    criterio: "Sin restricciones para ascender.",
    montos: [
      { etiqueta: "Bono al alcanzar el rango", cop: 1500000 },
      { etiqueta: "Bono de ascenso", cop: 3000000 },
    ],
  },
  {
    n: 2, nombre: "Sharon Rose Master", icon: "sparkles",
    prerrequisito: "Mínimo 2 Diamond Master en cada pierna, y 2.400.000 PV personales.",
    comisionMaestria: "2% del total de PV, repartido entre Sharon Rose Master y las maestrías superiores.",
    promocion: "Aproximadamente $7.600.000 COP (≈ $1.900 USD) transferidos a tu cuenta, más un viaje para 2 personas.",
    criterio: "Sin restricciones para ascender.",
    montos: [{ etiqueta: "Bono al alcanzar el rango", cop: 7600000 }],
  },
  {
    n: 3, nombre: "Star Master", icon: "star",
    prerrequisito: "Mínimo 2 Sharon Rose Master en cada pierna.",
    comisionMaestria: "1,2% del total de PV, repartido entre Star Master y las maestrías superiores.",
    promocion: "Aproximadamente $38.000.000 COP (≈ $9.500 USD) transferidos a tu cuenta, más un viaje para 4 personas.",
    criterio: "Debes haber calificado como Sharon Rose Master 3 veces antes de poder ascender a Star Master.",
    montos: [{ etiqueta: "Bono al alcanzar el rango", cop: 38000000 }],
  },
  {
    n: 4, nombre: "Royal Master", icon: "crown",
    prerrequisito: "Mínimo 2 Star Master en cada pierna.",
    comisionMaestria: "1% del total de PV, repartido entre Royal Master y las maestrías superiores.",
    promocion: "Aproximadamente $190.000.000 COP (≈ $47.500 USD) transferidos a tu cuenta, un viaje para 4 personas, una tarjeta débito de aproximadamente $7.600.000 COP (≈ $1.900 USD) y el alquiler de un automóvil.",
    criterio: "Debes haber calificado como Star Master 3 veces antes de poder ascender a Royal Master.",
    montos: [
      { etiqueta: "Bono al alcanzar el rango", cop: 190000000 },
      { etiqueta: "Tarjeta débito", cop: 7600000 },
    ],
  },
  {
    n: 5, nombre: "Crown Master", icon: "award",
    prerrequisito: "Mínimo 2 Royal Master en cada pierna.",
    comisionMaestria: "0,5% del total de PV, repartido entre Crown Master e Imperial Master.",
    promocion: "Aproximadamente $1.150.000.000 COP (≈ $287.500 USD) transferidos a tu cuenta, un viaje para 4 personas, una tarjeta débito de aproximadamente $19.000.000 COP (≈ $4.750 USD) y un automóvil de lujo propio.",
    criterio: "Debes haber calificado como Royal Master 3 veces antes de poder ascender a Crown Master.",
    montos: [
      { etiqueta: "Bono al alcanzar el rango", cop: 1150000000 },
      { etiqueta: "Tarjeta débito", cop: 19000000 },
    ],
  },
  {
    n: 6, nombre: "Imperial Master", icon: "trophy",
    prerrequisito: "Mínimo 2 Crown Master en cada pierna.",
    comisionMaestria: "0,3% del total de PV, repartido entre los Imperial Master.",
    promocion: "Aproximadamente $3.800.000.000 COP (≈ $950.000 USD) transferidos a tu cuenta, un viaje para 4 personas, una tarjeta débito de aproximadamente $38.000.000 COP (≈ $9.500 USD), un automóvil de lujo propio con chofer, y una oficina con asistente personal.",
    criterio: "Debes haber calificado como Crown Master 3 veces antes de poder ascender a Imperial Master — el rango más alto del plan.",
    montos: [
      { etiqueta: "Bono al alcanzar el rango", cop: 3800000000 },
      { etiqueta: "Tarjeta débito", cop: 38000000 },
    ],
  },
];

/* ---------------------------------------------------------------
   CONVERSIÓN DE MONEDA POR PAÍS (para "Mi Rango")
   Todos los montos oficiales de RANGOS_MASTER están en COP. Estas tasas
   son aproximadas ~2024, solo para referencia visual en pantalla — no son
   datos financieros exactos ni se actualizan con el mercado. La comisión
   real siempre se calcula y liquida con base en el valor del Won coreano
   (KRW) del momento, así que el monto que ve cada líder en su moneda local
   varía según la tasa de cambio real de cada fecha.
--------------------------------------------------------------- */
const TASAS_COP_POR_MONEDA = {
  COP: 1,
  USD: 4000,
  EUR: 4300,
  MXN: 230,
  BRL: 720,
  CAD: 2900,
};

function convertirDesdeCOP(montoCOP, monedaDestino) {
  const tasa = TASAS_COP_POR_MONEDA[monedaDestino] || TASAS_COP_POR_MONEDA.COP;
  return Number(montoCOP || 0) / tasa;
}

const NOTA_MONEDA_APROX = "Los montos de arriba son un estimado (aprox.) convertido a tu moneda local — la comisión real siempre se calcula y se paga con base en el valor del Won coreano (KRW) del momento, y varía según la tasa de cambio de cada fecha.";

const CRITERIOS_GENERALES = [
  "Una vez alcanzas un rango de Maestría, lo conservas de forma permanente: no hay condiciones para mantenerlo.",
  "No es posible ascender dos niveles de Maestría en un solo período, salvo hasta Diamond Master; de Sharon Rose Master en adelante, el ascenso es siempre de un nivel a la vez.",
  "No hay plazo límite para avanzar — solo necesitas conservar una membresía válida.",
  "La Comisión de Maestría se paga dos veces al mes: el día 15, y también el día 7 después del cierre mensual.",
];

/* Los montos oficiales siempre están en pesos colombianos (COP) y antes de
   impuestos — cada etiqueta se convierte a la moneda del país activo con
   formatMonedaAprox() al momento de renderizar (ver NOTA_MONEDA_APROX). */
const NOTAS_VALORES = [
  { etiqueta: "Viaje para Sharon Rose Master y Star Master", cop: 3817000, sufijo: "por persona" },
  { etiqueta: "Viaje para Royal Master, Crown Master e Imperial Master", cop: 15286000, sufijo: "por persona" },
  { etiqueta: "Alquiler del automóvil de Royal Master", cop: 3817000, sufijo: "mensuales" },
  { etiqueta: "Automóvil de lujo de Crown Master", cop: 244288000, sufijo: "" },
  { etiqueta: "Automóvil de lujo de Imperial Master", cop: 297726000, sufijo: "" },
  { etiqueta: "Oficina en renta (Imperial Master)", cop: 9542500, sufijo: "mensuales" },
  { etiqueta: "Asistente personal (Imperial Master)", cop: 5725500, sufijo: "mensuales" },
  { etiqueta: "Chofer (Imperial Master)", cop: 7634000, sufijo: "mensuales" },
];

const CLUBES_EXITO = [
  { nombre: "AutoSales Master", requisito: "Recalificar como Sales Master 12 veces en un año (una vez por quincena, en promedio).", ingresoCopMin: 8000000, ingresoCopMax: 12000000, ingresoSufijo: "mensuales" },
  { nombre: "Club de Líderes", ingresoAnualCop: 350000000 },
  { nombre: "Club de Líderes Royal", ingresoAnualCop: 700000000 },
  { nombre: "Club de Líderes Crown", ingresoAnualCop: 1500000000 },
  { nombre: "Club de Líderes Imperial", requisito: "Llegar a ser Imperial Master." },
];

const PAISES_CATALOGO = [
  { id: "CO", label: "Colombia", moneda: "COP", simbolo: "$", locale: "es-CO", codigo: "+57" },
  { id: "EU", label: "Europa", moneda: "EUR", simbolo: "€", locale: "es-ES", codigo: "+34" },
  { id: "MX", label: "México", moneda: "MXN", simbolo: "$", locale: "es-MX", codigo: "+52" },
  { id: "BR", label: "Brasil", moneda: "BRL", simbolo: "R$", locale: "pt-BR", codigo: "+55" },
  { id: "CA", label: "Canadá", moneda: "CAD", simbolo: "$", locale: "en-CA", codigo: "+1" },
  { id: "US", label: "Estados Unidos", moneda: "USD", simbolo: "$", locale: "en-US", codigo: "+1" },
];

const CATALOGO_PRODUCTOS_POR_PAIS = {
  CO: [
  { categoria: "Cuidado Personal", nombre: "Absolute Acondicionador - Paso 3", precio: 78000, pv: 8000 },
  { categoria: "Cuidado Personal", nombre: "Absolute Shampoo - Paso 1", precio: 78000, pv: 8000 },
  { categoria: "Cuidado Personal", nombre: "Absolute Tratamiento - Paso 2", precio: 53000, pv: 5000 },
  { categoria: "Cuidado Personal", nombre: "Acondicionador Herbal para Cabello", precio: 53800, pv: 5700 },
  { categoria: "Cuidado Personal", nombre: "Aidam Limpiador Íntimo Unisex", precio: 25000, pv: 2000 },
  { categoria: "Cuidado Personal", nombre: "Atomy Exfoliante Corporal a Base de Sal", precio: 75000, pv: 8300 },
  { categoria: "Cuidado Personal", nombre: "Atomy Homme All-in-One Wash", precio: 70600, pv: 7400 },
  { categoria: "Cuidado Personal", nombre: "Atomy Homme Multi-Action Cleanser", precio: 50000, pv: 5000 },
  { categoria: "Cuidado Personal", nombre: "Atomy Root Vital Hair Care Set", precio: 219000, pv: 22500 },
  { categoria: "Cuidado Personal", nombre: "Atomy Sculpture Acondicionador - Paso 2", precio: 62400, pv: 6200 },
  { categoria: "Cuidado Personal", nombre: "Atomy Sculpture Shampoo - Paso 1", precio: 62400, pv: 6200 },
  { categoria: "Cuidado Personal", nombre: "Atomy Shampoo de Proteína", precio: 80000, pv: 8000 },
  { categoria: "Cuidado Personal", nombre: "Atomy Tónico para Cabello", precio: 56600, pv: 5600 },
  { categoria: "Cuidado Personal", nombre: "Atomy Tratamiento Líquido de Proteína", precio: 60000, pv: 6500 },
  { categoria: "Cuidado Personal", nombre: "Cepillo Dental (8 unidades)", precio: 37000, pv: 5300 },
  { categoria: "Cuidado Personal", nombre: "Cepillo Dental Niños (8 unidades)", precio: 48300, pv: 4200 },
  { categoria: "Cuidado Personal", nombre: "Crema de Manos", precio: 53600, pv: 7400 },
  { categoria: "Cuidado Personal", nombre: "Esencia para Rizos", precio: 44000, pv: 5400 },
  { categoria: "Cuidado Personal", nombre: "Hand Balm Butter 50ml", precio: 24000, pv: 2800 },
  { categoria: "Cuidado Personal", nombre: "Hand Balm Marine 50ml", precio: 24000, pv: 2800 },
  { categoria: "Cuidado Personal", nombre: "Hand Balm Pure 50ml", precio: 24000, pv: 2800 },
  { categoria: "Cuidado Personal", nombre: "Jabón de Manos", precio: 15400, pv: 1100 },
  { categoria: "Cuidado Personal", nombre: "Kit de Viaje (6 piezas)", precio: 91000, pv: 5000 },
  { categoria: "Cuidado Personal", nombre: "Limpiador Herbal para Cuerpo", precio: 39800, pv: 3500 },
  { categoria: "Cuidado Personal", nombre: "Loción Corporal", precio: 42400, pv: 3520 },
  { categoria: "Cuidado Personal", nombre: "Óleo Esencial para el Cabello", precio: 49200, pv: 5600 },
  { categoria: "Cuidado Personal", nombre: "Pasta dental 200g (x5 unidades)", precio: 71200, pv: 3600 },
  { categoria: "Cuidado Personal", nombre: "Pasta dental 50g (x4 unidades)", precio: 23100, pv: 3300 },
  { categoria: "Cuidado Personal", nombre: "Pasta Dental Sensitive (x3 unidades)", precio: 48000, pv: 4800 },
  { categoria: "Cuidado Personal", nombre: "Root Vital Hair Shampoo", precio: 95000, pv: 9100 },
  { categoria: "Cuidado Personal", nombre: "Set de Ampolletas Para Cuero Cabelludo Root Vital (X3)", precio: 178000, pv: 24000 },
  { categoria: "Cuidado Personal", nombre: "Shampoo Herbal para Cabello", precio: 53800, pv: 5700 },
  { categoria: "Cuidado Personal", nombre: "Sistema de Cuidado Bucal (x4 kits)", precio: 55000, pv: 6500 },
  { categoria: "Cuidado Personal", nombre: "Spray de Propóleo Verde (x3 unidades)", precio: 110000, pv: 9500 },
  { categoria: "Cuidado Personal", nombre: "Terapia para Manos (x4 unidades)", precio: 63500, pv: 6600 },
  { categoria: "Cuidado Personal", nombre: "Tratamiento Herbal para Cabello", precio: 29700, pv: 2900 },
  { categoria: "Cuidado Personal", nombre: "Tratamiento Root Vital", precio: 72000, pv: 8000 },
  { categoria: "Hogar", nombre: "Atomy Esponjillas de Acero Inoxidable (x2 unidades)", precio: 16900, pv: 750 },
  { categoria: "Hogar", nombre: "Atomy Scratch Free Scrubber", precio: 20000, pv: 1400 },
  { categoria: "Hogar", nombre: "Detergente en Polvo para Ropa (x2 unidades)", precio: 57700, pv: 4000 },
  { categoria: "Hogar", nombre: "Detergente Lavatrastes", precio: 32700, pv: 3400 },
  { categoria: "Hogar", nombre: "Detergente Líquido para Ropa", precio: 54000, pv: 4800 },
  { categoria: "Hogar", nombre: "Guantes de Látex (M) *2 pares", precio: 23900, pv: 1300 },
  { categoria: "Hogar", nombre: "Suavizante de Telas", precio: 46200, pv: 3700 },
  { categoria: "Alimentos", nombre: "Aceite de Aguacate Extra Virgen", precio: 90000, pv: 8000 },
  { categoria: "Alimentos", nombre: "Atomy Sí Puer (X 30 sobres)", precio: 122000, pv: 13600 },
  { categoria: "Alimentos", nombre: "Café Arábica Black (x80 sobres)", precio: 95000, pv: 5200 },
  { categoria: "Alimentos", nombre: "Café Arábica Zero Sugar X 100 Sobres", precio: 149000, pv: 5500 },
  { categoria: "Alimentos", nombre: "Crema no Láctea (x50 sobres)", precio: 53100, pv: 2200 },
  { categoria: "HemoHIM", nombre: "Atomy HemoHIM *4set", precio: 1700000, pv: 300000 },
  { categoria: "HemoHIM", nombre: "Bolsa de Regalo (20cm x 31cm)", precio: 1500, pv: 0 },
  { categoria: "HemoHIM", nombre: "Bolsa reutilizable HemoHIM", precio: 4200, pv: 0 },
  { categoria: "HemoHIM", nombre: "Combo HemoHIM x 2 set", precio: 880000, pv: 150000 },
  { categoria: "HemoHIM", nombre: "HemoHIM (x60 sobres)", precio: 440000, pv: 70000 },
  { categoria: "Cuidado de la Piel", nombre: "Absolute Ampolla - Paso 2", precio: 196000, pv: 28600 },
  { categoria: "Cuidado de la Piel", nombre: "Absolute CellActive (1 Set con 6 productos)", precio: 880000, pv: 130000 },
  { categoria: "Cuidado de la Piel", nombre: "Absolute Contorno de Ojos - Paso 5", precio: 163500, pv: 23400 },
  { categoria: "Cuidado de la Piel", nombre: "Absolute Crema Nutritiva - Paso 6", precio: 147800, pv: 20800 },
  { categoria: "Cuidado de la Piel", nombre: "Absolute Loción - Paso 4", precio: 147800, pv: 20800 },
  { categoria: "Cuidado de la Piel", nombre: "Absolute Suero - Paso 3", precio: 163500, pv: 23400 },
  { categoria: "Cuidado de la Piel", nombre: "Absolute Tónico - Paso 1", precio: 147800, pv: 20800 },
  { categoria: "Cuidado de la Piel", nombre: "Aceite Limpiador", precio: 79300, pv: 8100 },
  { categoria: "Cuidado de la Piel", nombre: "Adelica Máscara de Pestañas Long-Lash", precio: 64000, pv: 6800 },
  { categoria: "Cuidado de la Piel", nombre: "Adelica Máscara de Pestañas Volumen", precio: 64000, pv: 6800 },
  { categoria: "Cuidado de la Piel", nombre: "Aplicador Atomy Absolute", precio: 18000, pv: 2000 },
  { categoria: "Cuidado de la Piel", nombre: "Atomy Absolute Hydra Balm", precio: 62000, pv: 8800 },
  { categoria: "Cuidado de la Piel", nombre: "Atomy Absolute Protector Solar", precio: 53000, pv: 5000 },
  { categoria: "Cuidado de la Piel", nombre: "Atomy Absolute Snow Crema de Día - Paso 3", precio: 131000, pv: 18500 },
  { categoria: "Cuidado de la Piel", nombre: "Atomy Absolute Snow Crema de Noche - Paso 4", precio: 139000, pv: 19500 },
  { categoria: "Cuidado de la Piel", nombre: "Atomy Absolute Snow Dark Spot Corrector - Noche Paso 2", precio: 90000, pv: 12000 },
  { categoria: "Cuidado de la Piel", nombre: "Atomy Absolute Snow Protector Solar", precio: 78000, pv: 9000 },
  { categoria: "Cuidado de la Piel", nombre: "Atomy Absolute Snow Set (5 productos)", precio: 552000, pv: 92000 },
  { categoria: "Cuidado de la Piel", nombre: "Atomy Absolute Snow Suero - Día Paso 2 / Noche Paso 3", precio: 139000, pv: 18500 },
  { categoria: "Cuidado de la Piel", nombre: "Atomy Absolute Snow Tónico - Día/Noche Paso 1", precio: 106000, pv: 14600 },
  { categoria: "Cuidado de la Piel", nombre: "Atomy Loción de Protección Solar", precio: 130000, pv: 15000 },
  { categoria: "Cuidado de la Piel", nombre: "Atomy Mascarilla de Arcilla Hinoki", precio: 73000, pv: 9700 },
  { categoria: "Cuidado de la Piel", nombre: "Atomy Sun Stick", precio: 45500, pv: 4700 },
  { categoria: "Cuidado de la Piel", nombre: "Bálsamo Labial", precio: 21200, pv: 2200 },
  { categoria: "Cuidado de la Piel", nombre: "Brillo Labial", precio: 50700, pv: 5300 },
  { categoria: "Cuidado de la Piel", nombre: "Cream Mist", precio: 58000, pv: 8000 },
  { categoria: "Cuidado de la Piel", nombre: "Crema BB", precio: 38500, pv: 2800 },
  { categoria: "Cuidado de la Piel", nombre: "Cuidado Nocturno 4 Pasos (1 Set)", precio: 156600, pv: 14300 },
  { categoria: "Cuidado de la Piel", nombre: "Desmaquillante Bifásico", precio: 48000, pv: 5000 },
  { categoria: "Cuidado de la Piel", nombre: "Espuma Limpiadora - Paso 2", precio: 39600, pv: 3400 },
  { categoria: "Cuidado de la Piel", nombre: "Gel Exfoliante - Paso 3", precio: 39600, pv: 3400 },
  { categoria: "Cuidado de la Piel", nombre: "Hydra Brightening Care Set", precio: 170000, pv: 25000 },
  { categoria: "Cuidado de la Piel", nombre: "Kit de Viaje (6 piezas)", precio: 91000, pv: 5000 },
  { categoria: "Cuidado de la Piel", nombre: "Lápiz de Cejas (Café)", precio: 35000, pv: 4200 },
  { categoria: "Cuidado de la Piel", nombre: "Limpiador Profundo - Paso 1", precio: 39600, pv: 3400 },
  { categoria: "Cuidado de la Piel", nombre: "Marine Ampoule Mask Brightening & Firming (x10 unidades)", precio: 120000, pv: 18000 },
  { categoria: "Cuidado de la Piel", nombre: "Mascarilla de Oro 24K", precio: 160000, pv: 23000 },
  { categoria: "Cuidado de la Piel", nombre: "Mascarilla Diaria Expert (Hidratante) (x10 unidades)", precio: 46000, pv: 4500 },
  { categoria: "Cuidado de la Piel", nombre: "Mascarilla Peel-Off - Paso 4", precio: 39600, pv: 3400 },
  { categoria: "Cuidado de la Piel", nombre: "Parche para Ojos de Hidrogel (x60 Parches)", precio: 82000, pv: 10000 },
  { categoria: "Cuidado de la Piel", nombre: "Peeling Pad", precio: 53000, pv: 7000 },
  { categoria: "Cuidado de la Piel", nombre: "Protector Solar Beige (x1)", precio: 39800, pv: 3600 },
  { categoria: "Cuidado de la Piel", nombre: "Protector Solar Blanco (x1)", precio: 39800, pv: 3600 },
  { categoria: "Cuidado de la Piel", nombre: "Sistema Cuidado para la Piel The Fame (1 Set con 5 Productos)", precio: 400000, pv: 57200 },
  { categoria: "Cuidado de la Piel", nombre: "Sobre Individual Marine Ampoule Mask Brightening", precio: 13000, pv: 1200 },
  { categoria: "Cuidado de la Piel", nombre: "The Fame Crema Esencia - Paso 3", precio: 89400, pv: 12500 },
  { categoria: "Cuidado de la Piel", nombre: "The Fame Crema Nutritiva - Paso 5", precio: 84300, pv: 11700 },
  { categoria: "Cuidado de la Piel", nombre: "The Fame Crema para Ojos - Paso 2", precio: 84300, pv: 11700 },
  { categoria: "Cuidado de la Piel", nombre: "The Fame Loción - Paso 4", precio: 84300, pv: 11700 },
  { categoria: "Cuidado de la Piel", nombre: "The Fame Tónico - Paso 1", precio: 84300, pv: 11700 },
  { categoria: "Cuidado de la Salud", nombre: "Atomy Fibra Psyllium Husk (x45 sobres)", precio: 135000, pv: 19100 },
  { categoria: "Cuidado de la Salud", nombre: "Atomy Spirulina & SOD", precio: 147000, pv: 17000 },
  { categoria: "Cuidado de la Salud", nombre: "Caja Individual Probióticos", precio: 81000, pv: 8000 },
  { categoria: "Cuidado de la Salud", nombre: "E-Omega 3 (x180 Cápsulas)", precio: 110000, pv: 10000 },
  { categoria: "Cuidado de la Salud", nombre: "Fermento de Noni Concentrado", precio: 270000, pv: 35000 },
  { categoria: "Cuidado de la Salud", nombre: "Fermento de Noni Sachet (24 sobres)", precio: 295000, pv: 39500 },
  { categoria: "Cuidado de la Salud", nombre: "Gel de Manzana Verde (x28 sobres)", precio: 128000, pv: 15000 },
  { categoria: "Cuidado de la Salud", nombre: "Gomitas de Propóleo y Zinc", precio: 120000, pv: 11000 },
  { categoria: "Cuidado de la Salud", nombre: "Hierro (x60 sobres)", precio: 138000, pv: 15000 },
  { categoria: "Cuidado de la Salud", nombre: "Probióticos 10+ (4 Cajas x 30 sobres, total 120 sobres)", precio: 290000, pv: 30000 },
  { categoria: "Cuidado de la Salud", nombre: "Rutina Detox + PVs", precio: 539000, pv: 75000 },
  { categoria: "Cuidado de la Salud", nombre: "Rutina Fortalece + PVs", precio: 688000, pv: 110000 },
  { categoria: "Promociones", nombre: "Absolute Recargado", precio: 1760000, pv: 300000 },
  { categoria: "Promociones", nombre: "Combo Evolución Fitness", precio: 500000, pv: 55000 },
  { categoria: "Promociones", nombre: "Combo Imperial 2026", precio: 2049000, pv: 300000 },
  { categoria: "Promociones", nombre: "Combo San Valentín", precio: 261700, pv: 28100 },
  { categoria: "Promociones", nombre: "Promo Noni 5+1", precio: 1350000, pv: 175000 },
  { categoria: "Promociones", nombre: "Rutina Equilibrio + PVs", precio: 720000, pv: 100000 },
  { categoria: "Otros", nombre: "Balanza y Muñequera de Skincare", precio: 24000, pv: 0 },
  { categoria: "Otros", nombre: "Bolsa Laminada (x1)", precio: 1700, pv: 0 },
  { categoria: "Otros", nombre: "Bolsa Multiusos (x1)", precio: 2600, pv: 0 },
  { categoria: "Otros", nombre: "Cartilla Escenario de Vida (x10 unidades)", precio: 25000, pv: 0 },
  { categoria: "Otros", nombre: "Cosmetiquera Atomy Merch", precio: 24000, pv: 0 },
  { categoria: "Otros", nombre: "Cuaderno Oficial Atomy Colombia", precio: 24900, pv: 0 },
  { categoria: "Otros", nombre: "Gorra Oficial Atomy Colombia", precio: 34000, pv: 0 },
  { categoria: "Otros", nombre: "Maleta Oficial Atomy", precio: 99000, pv: 0 },
  { categoria: "Otros", nombre: "Muñequito Han Gil Park (Limitado)", precio: 42000, pv: 0 },
  { categoria: "Otros", nombre: "Pin Amplifica", precio: 14000, pv: 0 },
  { categoria: "Otros", nombre: "Pin Metálico Oficial Atomy Colombia", precio: 12000, pv: 0 },
  { categoria: "Otros", nombre: "Pin Metálico Oficial HemoHIM", precio: 12000, pv: 0 },
  ],
  EU: [
  { categoria: "Cuidado Personal", nombre: "Acondicionador Herbal", precio: 15, pv: 4000 },
  { categoria: "Cuidado Personal", nombre: "Atomy Cerakids Shampoo & Bath *1EA", precio: 13.5, pv: 6500 },
  { categoria: "Cuidado Personal", nombre: "Cepillo de Dientes (8 unidades)", precio: 7.99, pv: 5000 },
  { categoria: "Cuidado Personal", nombre: "Cera de Cabello & Anti-Yea", precio: 13.5, pv: 6000 },
  { categoria: "Cuidado Personal", nombre: "Champú Herbal", precio: 14.5, pv: 7000 },
  { categoria: "Cuidado Personal", nombre: "Complejo de Aceite Capilar", precio: 13.5, pv: 6000 },
  { categoria: "Cuidado Personal", nombre: "Crema Corporal Ultra Rich", precio: 14.5, pv: 7000 },
  { categoria: "Cuidado Personal", nombre: "Cuidado de Cuello Brazil (Kit)", precio: 14.5, pv: 7000 },
  { categoria: "Cuidado Personal", nombre: "Dental Sonic Herbal Head Bundle", precio: 85, pv: 67000 },
  { categoria: "Cuidado Personal", nombre: "Dental Sonic Refill Head", precio: 14.5, pv: 8000 },
  { categoria: "Cuidado Personal", nombre: "Foot Scrub Wash", precio: 11, pv: 6000 },
  { categoria: "Cuidado Personal", nombre: "Fresh Sun Lotion", precio: 25, pv: 16000 },
  { categoria: "Cuidado Personal", nombre: "Hand Therapy 4 Kit", precio: 16.5, pv: 6200 },
  { categoria: "Cuidado Personal", nombre: "Limpiador de Manos", precio: 15.5, pv: 5000 },
  { categoria: "Cuidado Personal", nombre: "Limpiador Multi-Acción Homme", precio: 12.5, pv: 5000 },
  { categoria: "Cuidado Personal", nombre: "Loción Corporal", precio: 12, pv: 6000 },
  { categoria: "Cuidado Personal", nombre: "Pasta de Dientes 200g x5 Tubos", precio: 18.5, pv: 6000 },
  { categoria: "Cuidado Personal", nombre: "Pasta de Dientes 50g x4", precio: 6.5, pv: 2000 },
  { categoria: "Cuidado Personal", nombre: "Proteína Intensiva Shampoo", precio: 20, pv: 10000 },
  { categoria: "Cuidado Personal", nombre: "Proteína Intensiva Tratamiento", precio: 16.5, pv: 9500 },
  { categoria: "Cuidado Personal", nombre: "Root Nourishing Lotion", precio: 12, pv: 7000 },
  { categoria: "Cuidado Personal", nombre: "Saengmodan Hair Tonic", precio: 14, pv: 7000 },
  { categoria: "Cuidado Personal", nombre: "Sal de Baño Ultra Rich", precio: 14, pv: 6000 },
  { categoria: "Cuidado Personal", nombre: "Scalpcare 2 Set", precio: 28, pv: 11000 },
  { categoria: "Cuidado Personal", nombre: "Scalpcare Acondicionador", precio: 14.5, pv: 6000 },
  { categoria: "Cuidado Personal", nombre: "Scalpcare Hair Champú", precio: 14.5, pv: 6000 },
  { categoria: "Cuidado Personal", nombre: "Silk & Protein Hair Essence", precio: 13.5, pv: 6000 },
  { categoria: "Cuidado Personal", nombre: "Sistema de Cuidado Bucal 1 Set (4 pcs)", precio: 14.5, pv: 7000 },
  { categoria: "Cuidado Personal", nombre: "Sun Stick", precio: 12, pv: 5000 },
  { categoria: "Cuidado Personal", nombre: "Travel Cleansing Kit Set", precio: 17, pv: 3800 },
  { categoria: "Cuidado Personal", nombre: "Ultra Fine Wash", precio: 17.5, pv: 7000 },
  { categoria: "Cuidado Personal", nombre: "Ultra Rich Body Set", precio: 27, pv: 13000 },
  { categoria: "Alimentos", nombre: "Cafe Arabica 3 in 1 (50 sticks)", precio: 12.5, pv: 2000 },
  { categoria: "Alimentos", nombre: "Cafe Arabica Black", precio: 16, pv: 5000 },
  { categoria: "Alimentos", nombre: "Fermented Noni Drink Pouch", precio: 56.5, pv: 37000 },
  { categoria: "Alimentos", nombre: "Noni Pouch x4 Set", precio: 226, pv: 150000 },
  { categoria: "Alimentos", nombre: "Té Pu'er", precio: 25, pv: 14000 },
  { categoria: "Suplementos Alimenticios", nombre: "Bióticos 10 Plus", precio: 29.5, pv: 15000 },
  { categoria: "Suplementos Alimenticios", nombre: "E-Omega 3", precio: 22.5, pv: 9000 },
  { categoria: "Suplementos Alimenticios", nombre: "Espirulina Pura 100%", precio: 24, pv: 10000 },
  { categoria: "Suplementos Alimenticios", nombre: "Eye Lutein", precio: 32, pv: 15000 },
  { categoria: "Suplementos Alimenticios", nombre: "Hemohim G (4 set)", precio: 420, pv: 300000 },
  { categoria: "Suplementos Alimenticios", nombre: "Hemohim G - EU", precio: 105, pv: 73000 },
  { categoria: "Suplementos Alimenticios", nombre: "Hongsdaman", precio: 77.5, pv: 55000 },
  { categoria: "Suplementos Alimenticios", nombre: "Inner Collagen", precio: 34, pv: 19000 },
  { categoria: "Suplementos Alimenticios", nombre: "Noni Bottle", precio: 49, pv: 35000 },
  { categoria: "Suplementos Alimenticios", nombre: "Pomegranate Mixed Fruit Jelly", precio: 67.5, pv: 30000 },
  { categoria: "Suplementos Alimenticios", nombre: "Vitamina C", precio: 22.5, pv: 9000 },
  { categoria: "Belleza", nombre: "Absolute Ampolla", precio: 41, pv: 27000 },
  { categoria: "Belleza", nombre: "Absolute Crema Nutritiva", precio: 37, pv: 23000 },
  { categoria: "Belleza", nombre: "Absolute Crema Spot-Out", precio: 36, pv: 23000 },
  { categoria: "Belleza", nombre: "Absolute Loción", precio: 37, pv: 23000 },
  { categoria: "Belleza", nombre: "Absolute Mix 21 Saldito", precio: 17.5, pv: 6000 },
  { categoria: "Belleza", nombre: "Absolute Protector Solar Esencia", precio: 12.5, pv: 6000 },
  { categoria: "Belleza", nombre: "Absolute Skincare Set", precio: 195, pv: 115000 },
  { categoria: "Belleza", nombre: "Absolute Suero", precio: 40, pv: 26000 },
  { categoria: "Belleza", nombre: "Absolute Tónico", precio: 35.5, pv: 22000 },
  { categoria: "Belleza", nombre: "Adelica Lip Color Glow", precio: 9.5, pv: 5250 },
  { categoria: "Belleza", nombre: "Adelica Volume Mascara Black", precio: 11.5, pv: 6250 },
  { categoria: "Belleza", nombre: "Adelica Waterproof Mascara", precio: 11.5, pv: 6250 },
  { categoria: "Belleza", nombre: "Atomy Absolute BB 211 Unidad", precio: 17.5, pv: 8000 },
  { categoria: "Belleza", nombre: "Atomy Absolute Complejo Cellactive para Ojos", precio: 40.5, pv: 26000 },
  { categoria: "Belleza", nombre: "Atomy Absolute Urban Shield Cushion Solar", precio: 15, pv: 9000 },
  { categoria: "Belleza", nombre: "Cuidado de Noche Set", precio: 37, pv: 14000 },
  { categoria: "Belleza", nombre: "Deep Cleanser", precio: 9.5, pv: 3500 },
  { categoria: "Belleza", nombre: "Derma Real Cica Gel Limpiador", precio: 13.5, pv: 8000 },
  { categoria: "Belleza", nombre: "Derma Real Cica Set", precio: 62.5, pv: 43000 },
  { categoria: "Belleza", nombre: "Foam Cleanser", precio: 9.5, pv: 3500 },
  { categoria: "Belleza", nombre: "Homme Cuidado de la Piel Set", precio: 55, pv: 35000 },
  { categoria: "Belleza", nombre: "Limpiador Multi-Acción Homme", precio: 12.5, pv: 5000 },
  { categoria: "Belleza", nombre: "Lip Glow", precio: 12, pv: 6000 },
  { categoria: "Belleza", nombre: "Marine Ampoule Eye Patch", precio: 19.5, pv: 10000 },
  { categoria: "Belleza", nombre: "Marine Ampoule Gel Mask", precio: 32, pv: 22000 },
  { categoria: "Belleza", nombre: "Mascarilla Diaria Especializada", precio: 12.5, pv: 5000 },
  { categoria: "Belleza", nombre: "Mascarilla Nocturna de Oro 24K", precio: 28, pv: 21000 },
  { categoria: "Belleza", nombre: "Mild Bubble Cleanser", precio: 10.5, pv: 5000 },
  { categoria: "Belleza", nombre: "Peel-Off Mask", precio: 9.5, pv: 3500 },
  { categoria: "Belleza", nombre: "Peeling Gel", precio: 9.5, pv: 3500 },
  { categoria: "Belleza", nombre: "Peeling Pad", precio: 12, pv: 7000 },
  { categoria: "Belleza", nombre: "Sistema Cuidado para la Piel The Fame", precio: 99.5, pv: 60000 },
  { categoria: "Belleza", nombre: "Synergy Ampoule *1 Set", precio: 90, pv: 72000 },
  { categoria: "Belleza", nombre: "Travel Cleansing Kit Set", precio: 17, pv: 3800 },
  { categoria: "Otros", nombre: "Adelica Make-Up Brush Set + 2 Free Waterproof Mascara", precio: 35, pv: 27000 },
  { categoria: "Otros", nombre: "Adelica Waterproof Mascara", precio: 11.5, pv: 6250 },
  { categoria: "Otros", nombre: "Airopass Line Coffee (4-piece pouch)", precio: 6, pv: 0 },
  { categoria: "Otros", nombre: "Atomy Acropass Line Lifter 5 Pouch", precio: 60, pv: 35000 },
  { categoria: "Otros", nombre: "Atomy Business Book", precio: 10.5, pv: 0 },
  { categoria: "Otros", nombre: "Atomy Medi-Cook 4SET (9pcs.)", precio: 550, pv: 280000 },
  { categoria: "Otros", nombre: "Atomy T-shirt", precio: 15, pv: 0 },
  { categoria: "Otros", nombre: "Atomy Thermal Tumbler", precio: 22, pv: 5000 },
  { categoria: "Otros", nombre: "Best of Atomy Bundle", precio: 455, pv: 300000 },
  { categoria: "Otros", nombre: "Detergente para Ropa en Láminas", precio: 11, pv: 6500 },
  { categoria: "Otros", nombre: "MediCook Ceramic Set", precio: 155, pv: 100000 },
  { categoria: "Otros", nombre: "Mino Knives Set of 2", precio: 150, pv: 70000 },
  { categoria: "Otros", nombre: "New 2026Ver01 Leaflet (Bundle 20pieces)", precio: 5, pv: 0 },
  { categoria: "Otros", nombre: "Sticker Bundle Set", precio: 25, pv: 0 },
  { categoria: "Otros", nombre: "Summer Wellness Bundle", precio: 150, pv: 100000 },
  ],
  MX: [
  { categoria: "Cuidado Personal", nombre: "Absolute Conditioner", precio: 360, pv: 8000 },
  { categoria: "Cuidado Personal", nombre: "Absolute Shampoo", precio: 360, pv: 8000 },
  { categoria: "Cuidado Personal", nombre: "Aceite Esencial para el Cabello *1pza", precio: 260, pv: 5200 },
  { categoria: "Cuidado Personal", nombre: "Acondicionador Herbal para Cabello *1pza", precio: 280, pv: 5200 },
  { categoria: "Cuidado Personal", nombre: "Aidam Limpiador 1pza", precio: 130, pv: 1800 },
  { categoria: "Cuidado Personal", nombre: "Atomy Absolute Feminine Wash", precio: 240, pv: 5500 },
  { categoria: "Cuidado Personal", nombre: "Atomy Cepillo Dental para Niños", precio: 200, pv: 4000 },
  { categoria: "Cuidado Personal", nombre: "Atomy Cepillo Dental Set (6pza)", precio: 200, pv: 5000 },
  { categoria: "Cuidado Personal", nombre: "Atomy Enjuague Bucal", precio: 190, pv: 4000 },
  { categoria: "Cuidado Personal", nombre: "Atomy Hand Cream", precio: 295, pv: 7000 },
  { categoria: "Cuidado Personal", nombre: "Atomy Protein Intensive Hair Care Set", precio: 800, pv: 21700 },
  { categoria: "Cuidado Personal", nombre: "Atomy Salón & Color Castaño 5G", precio: 240, pv: 5000 },
  { categoria: "Cuidado Personal", nombre: "Atomy Salón & Color Castaño Obscuro 6G", precio: 240, pv: 5000 },
  { categoria: "Cuidado Personal", nombre: "Atomy Salón & Color Negro 7G", precio: 240, pv: 5000 },
  { categoria: "Cuidado Personal", nombre: "Atomy Sculpture Conditioner", precio: 330, pv: 5720 },
  { categoria: "Cuidado Personal", nombre: "Atomy Sculpture Shampoo", precio: 330, pv: 5720 },
  { categoria: "Cuidado Personal", nombre: "Curling Essence", precio: 195, pv: 5400 },
  { categoria: "Cuidado Personal", nombre: "Green Propolis Spray", precio: 460, pv: 9500 },
  { categoria: "Cuidado Personal", nombre: "Homme All-in-One Wash", precio: 370, pv: 7000 },
  { categoria: "Cuidado Personal", nombre: "Homme Multi-Action Cleanser", precio: 250, pv: 4800 },
  { categoria: "Cuidado Personal", nombre: "Jabón para Manos *1pza", precio: 80, pv: 1000 },
  { categoria: "Cuidado Personal", nombre: "Limpiador Herbal para Cuerpo *1pza", precio: 210, pv: 3200 },
  { categoria: "Cuidado Personal", nombre: "Loción para el Cuerpo 1pza", precio: 220, pv: 3200 },
  { categoria: "Cuidado Personal", nombre: "Pasta dental 200g *1set", precio: 370, pv: 3250 },
  { categoria: "Cuidado Personal", nombre: "Pasta dental 50g *1set", precio: 120, pv: 3000 },
  { categoria: "Cuidado Personal", nombre: "Pasta Dental para Encías y Dientes Sensibles", precio: 230, pv: 5500 },
  { categoria: "Cuidado Personal", nombre: "Shampoo Herbal para Cabello *1pza", precio: 280, pv: 5200 },
  { categoria: "Cuidado Personal", nombre: "Sistema de Cuidado Bucal *1set", precio: 300, pv: 6250 },
  { categoria: "Cuidado Personal", nombre: "Terapia para Manos (4pzas) 1kit", precio: 330, pv: 6000 },
  { categoria: "Cuidado Personal", nombre: "Tratamiento Herbal para Cabello *1pza", precio: 170, pv: 2900 },
  { categoria: "Cuidado Personal", nombre: "Tratamiento Líquido para Cabello *1pza", precio: 300, pv: 5200 },
  { categoria: "Hogar", nombre: "Atomy Fabric Detergent", precio: 300, pv: 3600 },
  { categoria: "Hogar", nombre: "Atomy Mexico MediCook Set", precio: 16000, pv: 300000 },
  { categoria: "Hogar", nombre: "Atomy Scratch Free Scrubber", precio: 100, pv: 1500 },
  { categoria: "Hogar", nombre: "Detergente Lavatrastes *1pza", precio: 170, pv: 3100 },
  { categoria: "Hogar", nombre: "Detergente Multisuperficies para Baño", precio: 280, pv: 6000 },
  { categoria: "Hogar", nombre: "Detergente Multisuperficies para Cocina", precio: 280, pv: 6000 },
  { categoria: "Hogar", nombre: "Detergente para Ropa 1pza", precio: 280, pv: 4400 },
  { categoria: "Hogar", nombre: "Fibra de Acero Inoxidable", precio: 70, pv: 1100 },
  { categoria: "Hogar", nombre: "Guantes de Látex (M)", precio: 130, pv: 2000 },
  { categoria: "Hogar", nombre: "MediCook 32cm Wok", precio: 5700, pv: 100000 },
  { categoria: "Hogar", nombre: "MediCook Olla 1.8 L", precio: 3200, pv: 56000 },
  { categoria: "Hogar", nombre: "MediCook Olla 5.5 L", precio: 5200, pv: 91000 },
  { categoria: "Hogar", nombre: "MediCook Sartén 22 cm", precio: 2400, pv: 42000 },
  { categoria: "Hogar", nombre: "O2 Bubble Power", precio: 220, pv: 5000 },
  { categoria: "Hogar", nombre: "Suavizante de Telas 1pza", precio: 240, pv: 3400 },
  { categoria: "Alimentos", nombre: "Atomy Café Arábica 0 Azúcar 50T", precio: 520, pv: 4000 },
  { categoria: "Alimentos", nombre: "Atomy Potato Ramen", precio: 210, pv: 1300 },
  { categoria: "Alimentos", nombre: "Café Arábica 50T", precio: 350, pv: 3000 },
  { categoria: "Alimentos", nombre: "Probiotics", precio: 750, pv: 16000 },
  { categoria: "Cuidado para la Salud", nombre: "Alaska E-Omega 3 *1pza", precio: 470, pv: 8300 },
  { categoria: "Cuidado para la Salud", nombre: "Applephenon Jelly Stick", precio: 560, pv: 15000 },
  { categoria: "Cuidado para la Salud", nombre: "Atomy Bitter Melon", precio: 790, pv: 22000 },
  { categoria: "Cuidado para la Salud", nombre: "Atomy Color B", precio: 460, pv: 9000 },
  { categoria: "Cuidado para la Salud", nombre: "Atomy Color C *1set", precio: 440, pv: 7800 },
  { categoria: "Cuidado para la Salud", nombre: "Atomy Finezyme", precio: 350, pv: 9000 },
  { categoria: "Cuidado para la Salud", nombre: "Atomy Greencera F", precio: 720, pv: 20000 },
  { categoria: "Cuidado para la Salud", nombre: "Atomy Inner Collagen Powder", precio: 770, pv: 22000 },
  { categoria: "Cuidado para la Salud", nombre: "Atomy Kids Vegan Gummy Multivitamin", precio: 420, pv: 11000 },
  { categoria: "Cuidado para la Salud", nombre: "Atomy Luxanthin", precio: 950, pv: 28000 },
  { categoria: "Cuidado para la Salud", nombre: "Atomy Pro Packed-Tamin", precio: 600, pv: 18000 },
  { categoria: "Cuidado para la Salud", nombre: "Atomy Pure Spirulina 100%", precio: 540, pv: 9100 },
  { categoria: "Cuidado para la Salud", nombre: "Atomy Rhubarb Queen", precio: 580, pv: 16000 },
  { categoria: "Cuidado para la Salud", nombre: "Atomy Tea", precio: 660, pv: 13000 },
  { categoria: "Cuidado para la Salud", nombre: "Atomy Tri-Active Calcium", precio: 490, pv: 13000 },
  { categoria: "Cuidado para la Salud", nombre: "Atomy TURMACIN MSM", precio: 900, pv: 21000 },
  { categoria: "Cuidado para la Salud", nombre: "Combo 5+1 Noni Challenge", precio: 6000, pv: 170000 },
  { categoria: "Cuidado para la Salud", nombre: "Combo Pequeños Impulsos", precio: 840, pv: 22000 },
  { categoria: "Cuidado para la Salud", nombre: "Organic Fermented Noni Concentrate (Bottle)", precio: 1200, pv: 34000 },
  { categoria: "Cuidado para la Salud", nombre: "Organic Noni Concentrate (Pouch)", precio: 1200, pv: 34000 },
  { categoria: "Cuidado para la Salud", nombre: "Rhodiola Milk Thistle", precio: 750, pv: 15000 },
  { categoria: "Him", nombre: "Him 4 Set PV's Up", precio: 8140, pv: 250000 },
  { categoria: "Him", nombre: "Him PV's Up", precio: 2150, pv: 65000 },
  { categoria: "Belleza", nombre: "4 Pasos PV's Up", precio: 830, pv: 16000 },
  { categoria: "Belleza", nombre: "Absolute 24K Gold Night Mask", precio: 730, pv: 19000 },
  { categoria: "Belleza", nombre: "Absolute Ampolla", precio: 1020, pv: 26000 },
  { categoria: "Belleza", nombre: "Absolute Contorno de Ojos", precio: 940, pv: 23400 },
  { categoria: "Belleza", nombre: "Absolute Crema Nutritiva", precio: 850, pv: 20800 },
  { categoria: "Belleza", nombre: "Absolute Hydra Balm", precio: 280, pv: 8000 },
  { categoria: "Belleza", nombre: "Absolute Loción", precio: 850, pv: 20800 },
  { categoria: "Belleza", nombre: "Absolute Oil Serum Mist", precio: 370, pv: 9000 },
  { categoria: "Belleza", nombre: "Absolute PV's Up", precio: 5060, pv: 170000 },
  { categoria: "Belleza", nombre: "Absolute Suero", precio: 940, pv: 23400 },
  { categoria: "Belleza", nombre: "Absoluto Tónico Facial", precio: 850, pv: 20800 },
  { categoria: "Belleza", nombre: "Adelica Lip Rouge Matt M01 True Red", precio: 290, pv: 9000 },
  { categoria: "Belleza", nombre: "Adelica Lip Rouge Matt M02 Neutral Pink", precio: 290, pv: 9000 },
  { categoria: "Belleza", nombre: "Adelica Lip Rouge Matt M03 Rose Flare", precio: 290, pv: 9000 },
  { categoria: "Belleza", nombre: "Adelica Lip Rouge Satin 02 Sweet Pink", precio: 290, pv: 9000 },
  { categoria: "Belleza", nombre: "Adelica Lip Rouge Satin 03 Raspberry", precio: 290, pv: 9000 },
  { categoria: "Belleza", nombre: "Adelica The New Gold Collagen Ampoule Cushion 02", precio: 590, pv: 16000 },
  { categoria: "Belleza", nombre: "Adelica The New Gold Collagen Ampoule Cushion 03", precio: 590, pv: 16000 },
  { categoria: "Belleza", nombre: "Adelica The New Gold Collagen Ampoule Cushion 04", precio: 590, pv: 16000 },
  { categoria: "Belleza", nombre: "Atomy Absolute BB 21*1EA", precio: 360, pv: 10000 },
  { categoria: "Belleza", nombre: "Atomy Absolute BB 23*1EA", precio: 360, pv: 10000 },
  { categoria: "Belleza", nombre: "Atomy Absolute Essence Sunscreen", precio: 250, pv: 5100 },
  { categoria: "Belleza", nombre: "Atomy Absolute Snow Dark Spot Corrector", precio: 340, pv: 9000 },
  { categoria: "Belleza", nombre: "Atomy Absolute Snow Day Cream", precio: 540, pv: 14000 },
  { categoria: "Belleza", nombre: "Atomy Absolute Snow Night Cream", precio: 640, pv: 17000 },
  { categoria: "Belleza", nombre: "Atomy Absolute Snow Serum", precio: 750, pv: 20000 },
  { categoria: "Belleza", nombre: "Atomy Absolute Snow Set", precio: 2900, pv: 90000 },
  { categoria: "Belleza", nombre: "Atomy Absolute Snow Tone-Up Essence Sun", precio: 280, pv: 7500 },
  { categoria: "Belleza", nombre: "Atomy Absolute Snow Toner", precio: 550, pv: 15000 },
  { categoria: "Belleza", nombre: "Atomy ACNE Clear Expert System", precio: 1520, pv: 40200 },
  { categoria: "Belleza", nombre: "Atomy Adelica Delineador de Cejas - Café Claro", precio: 170, pv: 4200 },
  { categoria: "Belleza", nombre: "Atomy Adelica Delineador de Cejas - Café Obscuro", precio: 170, pv: 4200 },
  { categoria: "Belleza", nombre: "Atomy Adelica Mascara para Pestañas a Prueba de Agua", precio: 280, pv: 6800 },
  { categoria: "Belleza", nombre: "Atomy Brush Pen Eyeliner (Black)", precio: 230, pv: 3600 },
  { categoria: "Belleza", nombre: "Atomy Fresh Sun Lotion", precio: 480, pv: 9500 },
  { categoria: "Belleza", nombre: "Atomy Homme Skincare Set", precio: 1200, pv: 29000 },
  { categoria: "Belleza", nombre: "Atomy Hydra Brightening Care Set", precio: 1000, pv: 27000 },
  { categoria: "Belleza", nombre: "Atomy Lip & Eye Remover", precio: 220, pv: 5000 },
  { categoria: "Belleza", nombre: "Atomy Marine Ampoule Eye Patch", precio: 400, pv: 10000 },
  { categoria: "Belleza", nombre: "Atomy Mascara para Pestañas - Volumen/Negro", precio: 280, pv: 6800 },
  { categoria: "Belleza", nombre: "Atomy Peeling Pad", precio: 250, pv: 6000 },
  { categoria: "Belleza", nombre: "Atomy Rose Rain Mist", precio: 270, pv: 5500 },
  { categoria: "Belleza", nombre: "Atomy Sun Stick", precio: 240, pv: 4500 },
  { categoria: "Belleza", nombre: "Atomy Synergy Ampoule Program", precio: 2600, pv: 68000 },
  { categoria: "Belleza", nombre: "Bálsamo Labial *1pza", precio: 110, pv: 2000 },
  { categoria: "Belleza", nombre: "Brillo Labial *1pza", precio: 290, pv: 5300 },
  { categoria: "Belleza", nombre: "Crema BB 1pza", precio: 200, pv: 2500 },
  { categoria: "Belleza", nombre: "Daily Expert Mask Brightening", precio: 265, pv: 4500 },
  { categoria: "Belleza", nombre: "Daily Expert Mask Firming", precio: 265, pv: 4500 },
  { categoria: "Belleza", nombre: "Daily Expert Mask Moisture", precio: 265, pv: 4500 },
  { categoria: "Belleza", nombre: "Deep Pure Cleansing Oil", precio: 420, pv: 7500 },
  { categoria: "Belleza", nombre: "Derma Calming Sun Stick", precio: 240, pv: 5100 },
  { categoria: "Belleza", nombre: "Derma Real Cica Gel Cleanser", precio: 260, pv: 8000 },
  { categoria: "Belleza", nombre: "Espuma Limpiadora 1pza", precio: 210, pv: 3250 },
  { categoria: "Belleza", nombre: "Gel Exfoliante 1pza", precio: 210, pv: 3250 },
  { categoria: "Belleza", nombre: "Homme All-in-One Wash", precio: 370, pv: 7000 },
  { categoria: "Belleza", nombre: "Homme Multi-Action Cleanser", precio: 250, pv: 4800 },
  { categoria: "Belleza", nombre: "Limpiador Profundo 1pza", precio: 210, pv: 3250 },
  { categoria: "Belleza", nombre: "Limpieza Profunda Kit de Viaje (6pzas) 1kit", precio: 350, pv: 5000 },
  { categoria: "Belleza", nombre: "Mascarilla en Gel - 7 Soluciones 1kit", precio: 720, pv: 13000 },
  { categoria: "Belleza", nombre: "Mascarilla Peel-Off 1pza", precio: 210, pv: 3250 },
  { categoria: "Belleza", nombre: "Protector Solar Beige 1pza", precio: 200, pv: 3250 },
  { categoria: "Belleza", nombre: "Protector Solar Blanco 1pza", precio: 200, pv: 3250 },
  { categoria: "Belleza", nombre: "Sistema Cuidado para la Piel The Fame", precio: 2370, pv: 57200 },
  { categoria: "Belleza", nombre: "The Fame Crema Esencia", precio: 530, pv: 12500 },
  { categoria: "Belleza", nombre: "The Fame Crema Nutritiva", precio: 500, pv: 11700 },
  { categoria: "Belleza", nombre: "The Fame Crema para Ojos", precio: 500, pv: 11700 },
  { categoria: "Belleza", nombre: "The Fame Loción", precio: 500, pv: 11700 },
  { categoria: "Belleza", nombre: "The Fame Tónico", precio: 500, pv: 11700 },
  { categoria: "Otros", nombre: "Bolsa de Plástico 1pza", precio: 15, pv: 0 },
  { categoria: "Otros", nombre: "Bolsa Laminada (S) 1pza", precio: 10, pv: 0 },
  { categoria: "Otros", nombre: "Folleto de productos *1set (20pzas)", precio: 190, pv: 0 },
  ],
  BR: [
  { categoria: "Cuidado Personal", nombre: "Atomy Absolute Feminine Wash 160mL", precio: 134, pv: 13000 },
  { categoria: "Cuidado Personal", nombre: "Atomy Absolute Hair Conditioner 500mL", precio: 145, pv: 14000 },
  { categoria: "Cuidado Personal", nombre: "Atomy Absolute Hair Shampoo 500mL", precio: 127, pv: 12000 },
  { categoria: "Cuidado Personal", nombre: "Atomy Absolute Haircare Set", precio: 346, pv: 36000 },
  { categoria: "Cuidado Personal", nombre: "Atomy Body Lotion 300mL", precio: 108, pv: 9000 },
  { categoria: "Cuidado Personal", nombre: "Atomy Cerakidz Cream 100mL", precio: 143, pv: 14000 },
  { categoria: "Cuidado Personal", nombre: "Atomy Cerakidz Lotion 200mL", precio: 168, pv: 16000 },
  { categoria: "Cuidado Personal", nombre: "Atomy Hair Essential Oil 100mL", precio: 135, pv: 14000 },
  { categoria: "Cuidado Personal", nombre: "Atomy Hand Balm Butter 50ml", precio: 59, pv: 6000 },
  { categoria: "Cuidado Personal", nombre: "Atomy Hand Balm Pure 50ml", precio: 59, pv: 6000 },
  { categoria: "Cuidado Personal", nombre: "Atomy Hand Soap 300mL", precio: 40, pv: 2500 },
  { categoria: "Cuidado Personal", nombre: "Atomy Herbal Body Cleanser 500mL", precio: 90, pv: 8000 },
  { categoria: "Cuidado Personal", nombre: "Atomy Herbal Conditioner 500mL", precio: 107, pv: 11000 },
  { categoria: "Cuidado Personal", nombre: "Atomy Herbal Hair Treatment 200mL", precio: 67, pv: 7000 },
  { categoria: "Cuidado Personal", nombre: "Atomy Herbal Shampoo 500mL", precio: 105, pv: 11000 },
  { categoria: "Cuidado Personal", nombre: "Atomy Homme All-in-One Wash 500mL", precio: 152, pv: 17000 },
  { categoria: "Cuidado Personal", nombre: "Atomy Kids Toothbrush (8 unidades)", precio: 80, pv: 7500 },
  { categoria: "Cuidado Personal", nombre: "Atomy Oral Care System", precio: 120, pv: 15000 },
  { categoria: "Cuidado Personal", nombre: "Atomy Protein Hair Repair Set", precio: 345, pv: 35000 },
  { categoria: "Cuidado Personal", nombre: "Atomy Protein Intensive Shampoo", precio: 198, pv: 20000 },
  { categoria: "Cuidado Personal", nombre: "Atomy Protein Intensive Treatment", precio: 158, pv: 16000 },
  { categoria: "Cuidado Personal", nombre: "Atomy Scalpcare Conditioner 500ml", precio: 125, pv: 12000 },
  { categoria: "Cuidado Personal", nombre: "Atomy Scalpcare Set", precio: 220, pv: 25000 },
  { categoria: "Cuidado Personal", nombre: "Atomy Scalpcare Shampoo 500ml", precio: 110, pv: 12000 },
  { categoria: "Cuidado Personal", nombre: "Atomy Sensitive Toothpaste Set", precio: 118, pv: 15000 },
  { categoria: "Cuidado Personal", nombre: "Atomy Toothbrush (8 unidades)", precio: 80, pv: 11000 },
  { categoria: "Cuidado Personal", nombre: "Atomy Toothpaste 4X50g", precio: 48, pv: 2200 },
  { categoria: "Cuidado Personal", nombre: "Atomy Toothpaste 5X200g", precio: 155, pv: 8000 },
  { categoria: "Cuidado Personal", nombre: "Atomy Travel Cleansing Kit", precio: 159, pv: 10000 },
  { categoria: "Cuidado Personal", nombre: "Atomy Ultra Rich Body Cream 200mL", precio: 130, pv: 11500 },
  { categoria: "Casa", nombre: "Atomy Sheet Laundry Detergent (30 folhas)", precio: 116, pv: 8000 },
  { categoria: "Alimentos", nombre: "Atomy Alaska E-Omega 3", precio: 176, pv: 17000 },
  { categoria: "Alimentos", nombre: "Atomy Café Arábica Black", precio: 152, pv: 6000 },
  { categoria: "Alimentos", nombre: "Atomy Café Arábica T50", precio: 72, pv: 3200 },
  { categoria: "Alimentos", nombre: "Atomy Puer Tea", precio: 199, pv: 24000 },
  { categoria: "Alimentos", nombre: "Atomy Vitamin C", precio: 162, pv: 17000 },
  { categoria: "Beleza", nombre: "Atomy Absolute Ampoule Total", precio: 310, pv: 45000 },
  { categoria: "Beleza", nombre: "Atomy Absolute CellActive Nutrition", precio: 1540, pv: 130000 },
  { categoria: "Beleza", nombre: "Atomy Absolute Evening Foam Balm", precio: 130, pv: 7000 },
  { categoria: "Beleza", nombre: "Atomy Absolute Gel Serum Mist", precio: 179, pv: 17000 },
  { categoria: "Beleza", nombre: "Atomy Absolute HTA Complex", precio: 249, pv: 30000 },
  { categoria: "Beleza", nombre: "Atomy Absolute Lotion", precio: 239, pv: 30000 },
  { categoria: "Beleza", nombre: "Atomy Absolute Skincare Set", precio: 1540, pv: 130000 },
  { categoria: "Beleza", nombre: "Atomy Absolute Snow Dark Spot Corrector", precio: 162, pv: 27000 },
  { categoria: "Beleza", nombre: "Atomy Absolute Snow Lotion", precio: 1250, pv: 170000 },
  { categoria: "Beleza", nombre: "Atomy Absolute Toner", precio: 269, pv: 30000 },
  { categoria: "Beleza", nombre: "Atomy Ceramide Cream", precio: 143, pv: 15000 },
  { categoria: "Beleza", nombre: "Atomy Daily Expert Mask Brightening", precio: 106, pv: 15000 },
  { categoria: "Beleza", nombre: "Atomy Daily Expert Mask Firming", precio: 106, pv: 15000 },
  { categoria: "Beleza", nombre: "Atomy Daily Expert Mask Moisturizing", precio: 159, pv: 7000 },
  { categoria: "Beleza", nombre: "Atomy Deep Pure Cleansing Toner", precio: 159, pv: 7000 },
  { categoria: "Beleza", nombre: "Atomy Evening Care Deep Cleanser", precio: 79, pv: 7000 },
  { categoria: "Beleza", nombre: "Atomy Evening Care Foam Cleanser", precio: 79, pv: 7000 },
  { categoria: "Beleza", nombre: "Atomy Evening Care Peeling Gel", precio: 239, pv: 30000 },
  { categoria: "Beleza", nombre: "Atomy Evening Care Set", precio: 310, pv: 35000 },
  { categoria: "Beleza", nombre: "Atomy Homme All-in-One", precio: 178, pv: 15000 },
  { categoria: "Beleza", nombre: "Atomy Homme Essence", precio: 144, pv: 15000 },
  { categoria: "Beleza", nombre: "Atomy Homme Lotion", precio: 169, pv: 21000 },
  { categoria: "Beleza", nombre: "Atomy Homme Multi-Action Moisturizing", precio: 99, pv: 15000 },
  { categoria: "Beleza", nombre: "Atomy Homme Nutrition Cream", precio: 169, pv: 21000 },
  { categoria: "Beleza", nombre: "Atomy Lip Gel Balm", precio: 104, pv: 5300 },
  { categoria: "Beleza", nombre: "Atomy Lip Treatment", precio: 51, pv: 7000 },
  { categoria: "Beleza", nombre: "Atomy Lotion", precio: 124, pv: 15000 },
  { categoria: "Beleza", nombre: "Atomy Mineral Sunscreen", precio: 76, pv: 11500 },
  { categoria: "Beleza", nombre: "Atomy The Fame Absolute Serum", precio: 169, pv: 27000 },
  { categoria: "Beleza", nombre: "Atomy The Fame Nutrition Cream", precio: 169, pv: 21000 },
  { categoria: "Beleza", nombre: "Atomy The Fame Toner", precio: 124, pv: 27000 },
  { categoria: "Beleza", nombre: "Atomy Ultra Rich Body Cream", precio: 130, pv: 15000 },
  { categoria: "Promociones", nombre: "Atomy Maestria 300K PV", precio: 2155, pv: 300000 },
  { categoria: "Otros", nombre: "Atomy Catálogo Produtos 20 Unidades", precio: 40, pv: 0 },
  { categoria: "Otros", nombre: "Atomy Cenário de Vida", precio: 15, pv: 0 },
  ],
  CA: [
  { categoria: "Personal Care", nombre: "Absolute Conditioner (500ml)", precio: 24, pv: 8000 },
  { categoria: "Personal Care", nombre: "Absolute Feminine Wash (160ml)", precio: 16, pv: 5500 },
  { categoria: "Personal Care", nombre: "Absolute Homme Wash (400ml)", precio: 16, pv: 6300 },
  { categoria: "Personal Care", nombre: "Absolute Shampoo (500ml)", precio: 24, pv: 8000 },
  { categoria: "Personal Care", nombre: "Aidam Cleanser (200ml)", precio: 8, pv: 2000 },
  { categoria: "Personal Care", nombre: "Body Lotion (300ml)", precio: 12, pv: 3200 },
  { categoria: "Personal Care", nombre: "Hair Essential Oil (100ml)", precio: 18, pv: 5500 },
  { categoria: "Personal Care", nombre: "Hand Cream (300ml)", precio: 18, pv: 7000 },
  { categoria: "Personal Care", nombre: "Hand Lotion (400ml)", precio: 18, pv: 7000 },
  { categoria: "Personal Care", nombre: "Hand Soap (300ml)", precio: 4.5, pv: 1000 },
  { categoria: "Personal Care", nombre: "Hand Therapy 4 Kit (30ml x4 Tubes)", precio: 20, pv: 7000 },
  { categoria: "Personal Care", nombre: "Herbal Body Cleanser (500ml)", precio: 13, pv: 4000 },
  { categoria: "Personal Care", nombre: "Herbal Hair Conditioner (500ml)", precio: 17, pv: 6000 },
  { categoria: "Personal Care", nombre: "Herbal Hair Shampoo (500ml)", precio: 17, pv: 6000 },
  { categoria: "Personal Care", nombre: "Herbday (Large) (10 Pads x4 Packs)", precio: 19, pv: 4500 },
  { categoria: "Personal Care", nombre: "Herbday (Medium) (10 Pads x4 Packs)", precio: 18, pv: 4000 },
  { categoria: "Personal Care", nombre: "Herbday (Panty Liner) (20 Pads x4 Packs)", precio: 18, pv: 4000 },
  { categoria: "Personal Care", nombre: "Kids Toothbrush (8 Brushes)", precio: 13, pv: 4500 },
  { categoria: "Personal Care", nombre: "Oral Care System (4 Sets)", precio: 19, pv: 7000 },
  { categoria: "Personal Care", nombre: "Root Vital Hair Care Set", precio: 75, pv: 32000 },
  { categoria: "Personal Care", nombre: "Root Vital Hair Shampoo (500ml)", precio: 28, pv: 9500 },
  { categoria: "Personal Care", nombre: "Root Vital Scalp & Hair Pack (200ml)", precio: 24, pv: 8500 },
  { categoria: "Personal Care", nombre: "Root Vital Scalp Ampoule (15ml)", precio: 24, pv: 9000 },
  { categoria: "Personal Care", nombre: "Saengmodan Hair Tonic (200ml)", precio: 18, pv: 6000 },
  { categoria: "Personal Care", nombre: "Scalpcare Conditioner (500ml)", precio: 19, pv: 5720 },
  { categoria: "Personal Care", nombre: "Scalpcare Shampoo (500ml)", precio: 19, pv: 5720 },
  { categoria: "Personal Care", nombre: "Sensitive Teeth and Gums Toothpaste (100g x3 Tubes)", precio: 16, pv: 5500 },
  { categoria: "Personal Care", nombre: "Toothbrush (8 Brushes)", precio: 13, pv: 5500 },
  { categoria: "Personal Care", nombre: "Toothpaste (200g x 5 Tubes)", precio: 25, pv: 4000 },
  { categoria: "Personal Care", nombre: "Toothpaste (50g x4 Tubes)", precio: 9, pv: 3000 },
  { categoria: "Home", nombre: "(L) Eco Zipper Bag (22 Bags)", precio: 3.5, pv: 520 },
  { categoria: "Home", nombre: "(S) Eco Zipper Bag (22 Bags)", precio: 3, pv: 455 },
  { categoria: "Home", nombre: "Dishwasher Tablet 12 (14g x60 Tablets)", precio: 25, pv: 7500 },
  { categoria: "Home", nombre: "Eco Glove (120 Pieces)", precio: 5, pv: 1000 },
  { categoria: "Home", nombre: "Hand Soap (400ml)", precio: 4.5, pv: 1000 },
  { categoria: "Home", nombre: "Latex Gloves (M 2 Set)", precio: 6.5, pv: 1300 },
  { categoria: "Home", nombre: "Laundry Detergent Pods (7.25g x100 Pods)", precio: 30, pv: 9000 },
  { categoria: "Home", nombre: "Liquid Detergent (67.43 FL Oz)", precio: 18, pv: 4400 },
  { categoria: "Home", nombre: "MediCook 5.4L Wok", precio: 270, pv: 110000 },
  { categoria: "Home", nombre: "Scratch Free Scrubber (4 Packs)", precio: 6, pv: 1500 },
  { categoria: "Home", nombre: "Sheet Laundry Detergent (30 Sheets)", precio: 16, pv: 5000 },
  { categoria: "Home", nombre: "Stainless Scrubber (2 Packs)", precio: 5, pv: 750 },
  { categoria: "Home", nombre: "Tape Cleaner (1 Roller + 3 Refills)", precio: 22, pv: 4500 },
  { categoria: "Home", nombre: "Tape Cleaner Refill (3 Refills)", precio: 15, pv: 3000 },
  { categoria: "Food", nombre: "(36-Pack) Olive Oil Grilled Laver (5g x36 Packs)", precio: 28, pv: 3200 },
  { categoria: "Food", nombre: "[4 Set] Organic Coconut Sugar (250g x4)", precio: 30, pv: 7500 },
  { categoria: "Food", nombre: "[4 Sets] Fermented Noni Concentrate (38ml x24 Pouches)", precio: 320, pv: 130000 },
  { categoria: "Food", nombre: "[5+1 CHALLENGE] Fermented Noni Concentrate (947ml x6 Bottles)", precio: 400, pv: 160000 },
  { categoria: "Food", nombre: "Apple Jelly Stick (15g x28 Sachets)", precio: 40, pv: 18000 },
  { categoria: "Food", nombre: "Cafe Arabica (12.1g x50 Packets)", precio: 18, pv: 1800 },
  { categoria: "Food", nombre: "Cafe Arabica Black (1.6g x80 Packets)", precio: 20, pv: 3900 },
  { categoria: "Food", nombre: "Cafe Arabica Zero Sugar 100T", precio: 47, pv: 5000 },
  { categoria: "Food", nombre: "Fermented Noni Concentrate (38ml x24 Pouches)", precio: 85, pv: 35000 },
  { categoria: "Food", nombre: "Fermented Noni Concentrate (947ml x1 Bottle)", precio: 80, pv: 32000 },
  { categoria: "Food", nombre: "Organic Coconut Sugar (250g)", precio: 9, pv: 2200 },
  { categoria: "Food", nombre: "Potato Ramen (114g x4 packs)", precio: 9, pv: 1000 },
  { categoria: "Food", nombre: "Potato Ramen Mild (113g x4 packs)", precio: 9, pv: 1000 },
  { categoria: "Food", nombre: "Potato Spicy Cold Noodles (4 packs)", precio: 9, pv: 1000 },
  { categoria: "Food", nombre: "Puer Tea (1g x30 Sachets)", precio: 40, pv: 14000 },
  { categoria: "Food", nombre: "Triple Up Protein (25g x30 Sachets)", precio: 69, pv: 26000 },
  { categoria: "Health", nombre: "100% Pure Spirulina (120 Tablets)", precio: 30, pv: 12000 },
  { categoria: "Health", nombre: "[1 Set] Mordant Collagen (x10 Bottles per set)", precio: 112, pv: 112000 },
  { categoria: "Health", nombre: "[4 Set] Bitter Melon Capsule (60 Capsules x4)", precio: 352, pv: 150000 },
  { categoria: "Health", nombre: "Bitter Melon Capsule (60 Capsules)", precio: 99, pv: 30000 },
  { categoria: "Health", nombre: "Derma Calming Sun Stick (19g)", precio: 16, pv: 6500 },
  { categoria: "Health", nombre: "Eye Lutein (90 Softgels)", precio: 43, pv: 51000 },
  { categoria: "Health", nombre: "Kbeka Omega 3 (180 Softgels)", precio: 29, pv: 20000 },
  { categoria: "Health", nombre: "Mineral Gel Patch (65 Patches)", precio: 48, pv: 53000 },
  { categoria: "Health", nombre: "Mineral Sunscreen (Tube)", precio: 22, pv: 6000 },
  { categoria: "Health", nombre: "Mordant Collagen (30 Sachets)", precio: 30, pv: 12000 },
  { categoria: "Health", nombre: "Pomegranate Beauty (10g x30 Sachets)", precio: 93, pv: 30000 },
  { categoria: "Health", nombre: "Probiotics 10 Plus (2g x60 Sachets)", precio: 43, pv: 58000 },
  { categoria: "Health", nombre: "Psyllium Husk (5g x30 Sachets)", precio: 38, pv: 16000 },
  { categoria: "Health", nombre: "Pure Tea (10g x40 Sachets)", precio: 40, pv: 16000 },
  { categoria: "Health", nombre: "Rhodiola Milk Thistle (600mg x90 Tablets)", precio: 33, pv: 12000 },
  { categoria: "Health", nombre: "Vital Mega Vitamin C 2000 (2g x90 Sachets)", precio: 45, pv: 21000 },
  { categoria: "Health", nombre: "Vitamin C (2g x90 Sachets)", precio: 27, pv: 15000 },
  { categoria: "HemoHIM", nombre: "[4 Sets] HemoHIM (30 Sachets per Set)", precio: 440, pv: 300000 },
  { categoria: "HemoHIM", nombre: "[4 Sets] HemoHIM (60 Sachets per Set)", precio: 500, pv: 240000 },
  { categoria: "HemoHIM", nombre: "HemoHIM (30 Sachets)", precio: 106, pv: 70000 },
  { categoria: "HemoHIM", nombre: "HemoHIM (60 Sachets)", precio: 130, pv: 60000 },
  { categoria: "Beauty", nombre: "Absolute Ampoule (40ml)", precio: 59, pv: 29000 },
  { categoria: "Beauty", nombre: "Absolute Eye-Complex (40ml)", precio: 55, pv: 26000 },
  { categoria: "Beauty", nombre: "Absolute Lotion (135ml)", precio: 50, pv: 23000 },
  { categoria: "Beauty", nombre: "Absolute Nutrition Cream (50ml)", precio: 50, pv: 23000 },
  { categoria: "Beauty", nombre: "Absolute Oil Serum Mist (80ml)", precio: 27, pv: 13000 },
  { categoria: "Beauty", nombre: "Absolute Serum (50ml)", precio: 55, pv: 26000 },
  { categoria: "Beauty", nombre: "Absolute Skincare Set (6 Pieces)", precio: 305, pv: 150000 },
  { categoria: "Beauty", nombre: "Absolute Toner (150ml)", precio: 50, pv: 23000 },
  { categoria: "Beauty", nombre: "Adelica Soft Brow Pencil (0.3g Brown)", precio: 11, pv: 4000 },
  { categoria: "Beauty", nombre: "BB Cream (40ml)", precio: 15, pv: 4000 },
  { categoria: "Beauty", nombre: "Cleansing Essential Mini Kit (6pcs)", precio: 15, pv: 3500 },
  { categoria: "Beauty", nombre: "Daily Expert Mask Brightening (10 Sheets)", precio: 16, pv: 4500 },
  { categoria: "Beauty", nombre: "Daily Expert Mask Firming (10 Sheets)", precio: 16, pv: 4500 },
  { categoria: "Beauty", nombre: "Daily Expert Mask Moisturizing (10 Sheets)", precio: 16, pv: 4500 },
  { categoria: "Beauty", nombre: "Deep Cleanser (150ml)", precio: 14, pv: 4000 },
  { categoria: "Beauty", nombre: "Deep Pure Cleansing Oil (150ml)", precio: 25, pv: 7500 },
  { categoria: "Beauty", nombre: "Derma Calming Sun Stick (16g)", precio: 16, pv: 5000 },
  { categoria: "Beauty", nombre: "Derma Real Cica Set (3 Pieces)", precio: 90, pv: 42000 },
  { categoria: "Beauty", nombre: "Evening Care 4 Set", precio: 50, pv: 16000 },
  { categoria: "Beauty", nombre: "Foam Cleanser (150ml)", precio: 14, pv: 4000 },
  { categoria: "Beauty", nombre: "Healthy Glow Base (33ml)", precio: 17, pv: 5000 },
  { categoria: "Beauty", nombre: "Homme Energizing All in One (80ml)", precio: 29, pv: 14000 },
  { categoria: "Beauty", nombre: "Lip Glow (3.3g)", precio: 14, pv: 5300 },
  { categoria: "Beauty", nombre: "Lip Treatment (3.9g)", precio: 7.5, pv: 2200 },
  { categoria: "Beauty", nombre: "Mineral Sunscreen (75ml)", precio: 22, pv: 8000 },
  { categoria: "Beauty", nombre: "Peel-Off Mask (120ml)", precio: 14, pv: 4000 },
  { categoria: "Beauty", nombre: "Peeling Gel (120ml)", precio: 14, pv: 4000 },
  { categoria: "Beauty", nombre: "Rose Rain Mist (130ml)", precio: 17, pv: 4800 },
  { categoria: "Beauty", nombre: "The Fame Essence (50ml)", precio: 31, pv: 14000 },
  { categoria: "Beauty", nombre: "The Fame Eye Cream (40ml)", precio: 29, pv: 13000 },
  { categoria: "Beauty", nombre: "The Fame Lotion (135ml)", precio: 29, pv: 13000 },
  { categoria: "Beauty", nombre: "The Fame Nutrition Cream (50ml)", precio: 29, pv: 13000 },
  { categoria: "Beauty", nombre: "The Fame Set (Individual Packaging)", precio: 138, pv: 66000 },
  { categoria: "Beauty", nombre: "The Fame Toner (150ml)", precio: 29, pv: 13000 },
  { categoria: "Otros", nombre: "Best Kit", precio: 595, pv: 300000 },
  { categoria: "Otros", nombre: "Essential Kit", precio: 235, pv: 100000 },
  { categoria: "Otros", nombre: "Starter Kit", precio: 128, pv: 50000 },
  { categoria: "Otros", nombre: "Tarpaulin Bag (1EA)", precio: 6, pv: 1500 },
  ],
  US: [
  { categoria: "Cuidado Personal", nombre: "Absolute Conditioner - Step 3", precio: 21, pv: 10000 },
  { categoria: "Cuidado Personal", nombre: "Absolute Hair Care Set", precio: 55, pv: 28000 },
  { categoria: "Cuidado Personal", nombre: "Absolute Shampoo - Step 1", precio: 21, pv: 10000 },
  { categoria: "Cuidado Personal", nombre: "Absolute Treatment - Step 2", precio: 15, pv: 6000 },
  { categoria: "Cuidado Personal", nombre: "Aidam Cleanser", precio: 7, pv: 2500 },
  { categoria: "Cuidado Personal", nombre: "Body Lotion", precio: 12.5, pv: 4500 },
  { categoria: "Cuidado Personal", nombre: "Curling Essence", precio: 10, pv: 6500 },
  { categoria: "Cuidado Personal", nombre: "Ethereal Patches", precio: 36, pv: 16000 },
  { categoria: "Cuidado Personal", nombre: "Fluoride-Free Toothpaste", precio: 13, pv: 7000 },
  { categoria: "Cuidado Personal", nombre: "Foot Nourishing Cream", precio: 17.5, pv: 10000 },
  { categoria: "Cuidado Personal", nombre: "Foot Scrub Wash", precio: 16.5, pv: 9000 },
  { categoria: "Cuidado Personal", nombre: "Hair & Body Set", precio: 50, pv: 25000 },
  { categoria: "Cuidado Personal", nombre: "Hair Essential Oil", precio: 14, pv: 6500 },
  { categoria: "Cuidado Personal", nombre: "Hand Cream", precio: 17, pv: 8000 },
  { categoria: "Cuidado Personal", nombre: "Hand Lotion", precio: 17, pv: 6600 },
  { categoria: "Cuidado Personal", nombre: "Hand Soap", precio: 6, pv: 2000 },
  { categoria: "Cuidado Personal", nombre: "Hand Therapy", precio: 18.5, pv: 8500 },
  { categoria: "Cuidado Personal", nombre: "Herb Day (Large)", precio: 17, pv: 5700 },
  { categoria: "Cuidado Personal", nombre: "Herb Day (Liner)", precio: 16, pv: 5000 },
  { categoria: "Cuidado Personal", nombre: "Herb Day (Medium)", precio: 16, pv: 5000 },
  { categoria: "Cuidado Personal", nombre: "Herbal Body Cleanser", precio: 12, pv: 5000 },
  { categoria: "Cuidado Personal", nombre: "Herbal Hair Conditioner", precio: 16, pv: 8000 },
  { categoria: "Cuidado Personal", nombre: "Herbal Hair Shampoo", precio: 14, pv: 7000 },
  { categoria: "Cuidado Personal", nombre: "Herbal Hair Treatment", precio: 9, pv: 4000 },
  { categoria: "Cuidado Personal", nombre: "Homme All-in-One Wash", precio: 18, pv: 8000 },
  { categoria: "Cuidado Personal", nombre: "Homme Multi-Action Cleanser", precio: 18, pv: 5000 },
  { categoria: "Cuidado Personal", nombre: "Kids Toothbrush (8ea)", precio: 12, pv: 6000 },
  { categoria: "Cuidado Personal", nombre: "Oral Care System", precio: 16, pv: 8000 },
  { categoria: "Cuidado Personal", nombre: "Root Vital Hair Care Set", precio: 59, pv: 33000 },
  { categoria: "Cuidado Personal", nombre: "Root Vital Hair Shampoo", precio: 23, pv: 10000 },
  { categoria: "Cuidado Personal", nombre: "Root Vital Scalp Ampoule", precio: 20, pv: 9500 },
  { categoria: "Cuidado Personal", nombre: "Root Vital Scalp Ampoule *3ea", precio: 55, pv: 30000 },
  { categoria: "Cuidado Personal", nombre: "Saengmodan Hair Tonic", precio: 17, pv: 8000 },
  { categoria: "Cuidado Personal", nombre: "Scalpcare Conditioner", precio: 16.5, pv: 6200 },
  { categoria: "Cuidado Personal", nombre: "Scalpcare Hair Care Set", precio: 55, pv: 22500 },
  { categoria: "Cuidado Personal", nombre: "Scalpcare Set", precio: 32, pv: 15000 },
  { categoria: "Cuidado Personal", nombre: "Scalpcare Shampoo", precio: 16.5, pv: 7000 },
  { categoria: "Cuidado Personal", nombre: "Silk Protein Hair Essence", precio: 18, pv: 8000 },
  { categoria: "Cuidado Personal", nombre: "Sugar Body Scrub", precio: 20, pv: 11000 },
  { categoria: "Cuidado Personal", nombre: "Toothbrush (8pk)", precio: 12, pv: 7000 },
  { categoria: "Cuidado Personal", nombre: "Toothpaste", precio: 22, pv: 6000 },
  { categoria: "Cuidado Personal", nombre: "Toothpaste 50g", precio: 6, pv: 4000 },
  { categoria: "Cuidado Personal", nombre: "Ultra Rich Body Cream", precio: 16.5, pv: 7500 },
  { categoria: "Cuidado Personal", nombre: "Ultra Rich Body Wash", precio: 14, pv: 6000 },
  { categoria: "Hogar", nombre: "Dishwashing Liquid", precio: 12, pv: 5000 },
  { categoria: "Hogar", nombre: "Fabric Detergent", precio: 17, pv: 5000 },
  { categoria: "Hogar", nombre: "Fabric Softener", precio: 14, pv: 5000 },
  { categoria: "Hogar", nombre: "Latex Gloves (L) *2 sets", precio: 8, pv: 3000 },
  { categoria: "Hogar", nombre: "Latex Gloves (M) *2 sets", precio: 6, pv: 2000 },
  { categoria: "Hogar", nombre: "Liquid Laundry Detergent", precio: 17, pv: 6000 },
  { categoria: "Hogar", nombre: "MediCook 28cm Fry Pan", precio: 140, pv: 75000 },
  { categoria: "Hogar", nombre: "MediCook 3.3L", precio: 200, pv: 110000 },
  { categoria: "Hogar", nombre: "MediCook 5.4L Wok", precio: 260, pv: 140000 },
  { categoria: "Hogar", nombre: "MediCook 5.5L", precio: 240, pv: 130000 },
  { categoria: "Hogar", nombre: "O2 Bubble Power", precio: 14, pv: 6000 },
  { categoria: "Hogar", nombre: "Scratch Free Scrubber", precio: 6.5, pv: 2000 },
  { categoria: "Hogar", nombre: "Sheet Laundry Detergent", precio: 13, pv: 6000 },
  { categoria: "Comida", nombre: "Avocado 100% Extra Virgin Avocado Oil", precio: 18, pv: 6000 },
  { categoria: "Comida", nombre: "Cafe Arabica 50", precio: 12, pv: 4000 },
  { categoria: "Comida", nombre: "Cafe Arabica 50T *16ea", precio: 192, pv: 64000 },
  { categoria: "Comida", nombre: "Cafe Arabica Black", precio: 21, pv: 5500 },
  { categoria: "Comida", nombre: "Cafe Arabica Zero Sugar 100T", precio: 39, pv: 5000 },
  { categoria: "Comida", nombre: "Health Best Kit", precio: 150, pv: 100000 },
  { categoria: "Comida", nombre: "Manuka Honey 830+", precio: 78, pv: 35000 },
  { categoria: "Comida", nombre: "Olive Oil Grilled Laver", precio: 19, pv: 4000 },
  { categoria: "Comida", nombre: "Olive Oil Grilled Laver (36 Packs)", precio: 20, pv: 3000 },
  { categoria: "Comida", nombre: "Potato Ramen *4 pack", precio: 9, pv: 1300 },
  { categoria: "Comida", nombre: "Puer Tea", precio: 35, pv: 16000 },
  { categoria: "Cuidado de la Salud", nombre: "Applena Queen", precio: 39, pv: 15000 },
  { categoria: "Cuidado de la Salud", nombre: "Applephenon Jelly Stick", precio: 32, pv: 15000 },
  { categoria: "Cuidado de la Salud", nombre: "Bitter Melon", precio: 46, pv: 22000 },
  { categoria: "Cuidado de la Salud", nombre: "Eye Health Luteanthin", precio: 45, pv: 28000 },
  { categoria: "Cuidado de la Salud", nombre: "Eye Lutein", precio: 35, pv: 11000 },
  { categoria: "Cuidado de la Salud", nombre: "Green Propolis Spray", precio: 26, pv: 11000 },
  { categoria: "Cuidado de la Salud", nombre: "HemoHIM", precio: 105, pv: 66000 },
  { categoria: "Cuidado de la Salud", nombre: "HemoHIM *4 Sets", precio: 405, pv: 300000 },
  { categoria: "Cuidado de la Salud", nombre: "Insect Memory Up", precio: 40, pv: 21000 },
  { categoria: "Cuidado de la Salud", nombre: "Iron", precio: 17, pv: 15000 },
  { categoria: "Cuidado de la Salud", nombre: "ITG Omega 3", precio: 35, pv: 8900 },
  { categoria: "Cuidado de la Salud", nombre: "Korean Red Ginseng Jelly Stick", precio: 47, pv: 27000 },
  { categoria: "Cuidado de la Salud", nombre: "Mangosteen", precio: 95, pv: 34000 },
  { categoria: "Cuidado de la Salud", nombre: "Organic Fermented Noni Concentrate (Bottle)", precio: 57, pv: 34000 },
  { categoria: "Cuidado de la Salud", nombre: "Organic Fermented Noni Concentrate (Pouch)", precio: 62, pv: 34000 },
  { categoria: "Cuidado de la Salud", nombre: "Plant Calcium", precio: 32, pv: 13000 },
  { categoria: "Cuidado de la Salud", nombre: "Pomegranate Beauty", precio: 77, pv: 37000 },
  { categoria: "Cuidado de la Salud", nombre: "Power Vits Energizer", precio: 39, pv: 22000 },
  { categoria: "Cuidado de la Salud", nombre: "Psyllium Husk", precio: 32, pv: 21000 },
  { categoria: "Cuidado de la Salud", nombre: "Pure Spirulina 100%", precio: 26, pv: 12000 },
  { categoria: "Cuidado de la Salud", nombre: "Rhodiola Milk Thistle", precio: 35, pv: 15000 },
  { categoria: "Cuidado de la Salud", nombre: "Saw Palmetto", precio: 38, pv: 15000 },
  { categoria: "Cuidado de la Salud", nombre: "US Probiotics", precio: 40, pv: 22000 },
  { categoria: "Cuidado de la Salud", nombre: "Vital Color Vitamin C", precio: 24, pv: 11000 },
  { categoria: "Cuidado de la Salud", nombre: "Vital Mega Vitamin C 2000", precio: 39, pv: 22000 },
  { categoria: "Cuidado de la Salud", nombre: "Vitamin B Complex", precio: 22, pv: 10000 },
  { categoria: "Cuidado de la Salud", nombre: "Vitamin D3", precio: 32, pv: 12000 },
  { categoria: "HemoHIM", nombre: "HemoHIM 30 Pack", precio: 80, pv: 75000 },
  { categoria: "HemoHIM", nombre: "HemoHIM Manual (English) *1ea", precio: 0.4, pv: 0 },
  { categoria: "Belleza", nombre: "3-Seconds Beauty Water", precio: 16, pv: 7500 },
  { categoria: "Belleza", nombre: "A.C. Expert Foam Cleanser", precio: 17.5, pv: 11000 },
  { categoria: "Belleza", nombre: "A.C. Expert Serum", precio: 25, pv: 15000 },
  { categoria: "Belleza", nombre: "A.C. Expert Spot Solution", precio: 22, pv: 12000 },
  { categoria: "Belleza", nombre: "A.C. Expert System Set", precio: 84, pv: 55000 },
  { categoria: "Belleza", nombre: "A.C. Expert Toner", precio: 24, pv: 15000 },
  { categoria: "Belleza", nombre: "Absolute Ampoule", precio: 50, pv: 33000 },
  { categoria: "Belleza", nombre: "Absolute Eye-Complex", precio: 48, pv: 30000 },
  { categoria: "Belleza", nombre: "Absolute Lotion", precio: 45, pv: 27000 },
  { categoria: "Belleza", nombre: "Absolute Nutrition Cream", precio: 45, pv: 27000 },
  { categoria: "Belleza", nombre: "Absolute Oil Serum Mist", precio: 26, pv: 17000 },
  { categoria: "Belleza", nombre: "Absolute Serum", precio: 48, pv: 30000 },
  { categoria: "Belleza", nombre: "Absolute Skincare Set", precio: 260, pv: 175000 },
  { categoria: "Belleza", nombre: "Absolute Spot-Out Cream", precio: 39, pv: 22000 },
  { categoria: "Belleza", nombre: "Absolute Spot-Out Essence", precio: 45, pv: 26000 },
  { categoria: "Belleza", nombre: "Absolute Toner", precio: 45, pv: 27000 },
  { categoria: "Belleza", nombre: "Adelica Long-Lash Mascara", precio: 15.5, pv: 9000 },
  { categoria: "Belleza", nombre: "Adelica Loose Setting Powder", precio: 30.5, pv: 19000 },
  { categoria: "Belleza", nombre: "Adelica Mood on Eye Palette", precio: 25, pv: 15000 },
  { categoria: "Belleza", nombre: "Adelica Volume Mascara", precio: 15.5, pv: 9000 },
  { categoria: "Belleza", nombre: "BB Cream", precio: 10, pv: 3000 },
  { categoria: "Belleza", nombre: "Cream Mist", precio: 17, pv: 10000 },
  { categoria: "Belleza", nombre: "Daily Expert Mask Brightening", precio: 12.5, pv: 6000 },
  { categoria: "Belleza", nombre: "Daily Expert Mask Firming", precio: 12.5, pv: 6000 },
  { categoria: "Belleza", nombre: "Daily Expert Mask Moisturizing", precio: 12.5, pv: 6000 },
  { categoria: "Belleza", nombre: "Deep Cleanser", precio: 12, pv: 5000 },
  { categoria: "Belleza", nombre: "Deep Pure Cleansing Oil", precio: 20, pv: 8000 },
  { categoria: "Belleza", nombre: "Derma Calming Sun Stick", precio: 13, pv: 6000 },
  { categoria: "Belleza", nombre: "Derma Real Cica Ampoule", precio: 36, pv: 22000 },
  { categoria: "Belleza", nombre: "Derma Real Cica Cream", precio: 25, pv: 16000 },
  { categoria: "Belleza", nombre: "Derma Real Cica Gel Cleanser", precio: 15.5, pv: 10000 },
  { categoria: "Belleza", nombre: "Derma Real Cica Set", precio: 76, pv: 51000 },
  { categoria: "Belleza", nombre: "Derma Real Cica Toner", precio: 18.5, pv: 12000 },
  { categoria: "Belleza", nombre: "Evening Care 4 Set", precio: 45, pv: 21000 },
  { categoria: "Belleza", nombre: "Foam Cleanser", precio: 12, pv: 5000 },
  { categoria: "Belleza", nombre: "Healthy Glow Base", precio: 16, pv: 6000 },
  { categoria: "Belleza", nombre: "Homme Energizing All in One", precio: 25, pv: 14000 },
  { categoria: "Belleza", nombre: "Homme Essence", precio: 20, pv: 12000 },
  { categoria: "Belleza", nombre: "Homme Lotion", precio: 21, pv: 12000 },
  { categoria: "Belleza", nombre: "Homme Multi-Action Cleanser", precio: 12, pv: 5500 },
  { categoria: "Belleza", nombre: "Homme Skincare Set", precio: 58, pv: 37000 },
  { categoria: "Belleza", nombre: "Homme Toner", precio: 21, pv: 12000 },
  { categoria: "Belleza", nombre: "Hydra Brightening Care Set", precio: 50, pv: 32000 },
  { categoria: "Belleza", nombre: "Hydra Brightening Cream", precio: 25, pv: 15000 },
  { categoria: "Belleza", nombre: "Hydra Brightening Essence", precio: 26, pv: 16000 },
  { categoria: "Belleza", nombre: "Lip Glow", precio: 14, pv: 7000 },
  { categoria: "Belleza", nombre: "Lip Treatment", precio: 6.5, pv: 3000 },
  { categoria: "Belleza", nombre: "Marine Ampoule Eye Patch", precio: 19, pv: 11000 },
  { categoria: "Belleza", nombre: "Peel-Off Mask", precio: 12, pv: 5000 },
  { categoria: "Belleza", nombre: "Peeling Gel", precio: 12, pv: 5000 },
  { categoria: "Belleza", nombre: "Peeling Pad", precio: 12, pv: 6500 },
  { categoria: "Belleza", nombre: "Rose Rain Mist", precio: 13, pv: 5000 },
  { categoria: "Belleza", nombre: "Sun Stick", precio: 12, pv: 6000 },
  { categoria: "Belleza", nombre: "Sunscreen (Beige)", precio: 12, pv: 6000 },
  { categoria: "Belleza", nombre: "Sunscreen (White)", precio: 12, pv: 6000 },
  { categoria: "Belleza", nombre: "Synergy Ampoule *1 Set", precio: 135, pv: 90000 },
  { categoria: "Belleza", nombre: "Synergy Ampoule *3 Sets", precio: 400, pv: 320000 },
  { categoria: "Belleza", nombre: "The Fame Essence", precio: 27, pv: 16000 },
  { categoria: "Belleza", nombre: "The Fame Eye Cream", precio: 26, pv: 15000 },
  { categoria: "Belleza", nombre: "The Fame Lotion", precio: 26, pv: 15000 },
  { categoria: "Belleza", nombre: "The Fame Nutrition Cream", precio: 26, pv: 15000 },
  { categoria: "Belleza", nombre: "The Fame Set", precio: 120, pv: 77000 },
  { categoria: "Belleza", nombre: "The Fame Toner", precio: 26, pv: 15000 },
  { categoria: "Belleza", nombre: "The Fame Travel Kit", precio: 40, pv: 15000 },
  { categoria: "Belleza", nombre: "Travel Cleansing Kit", precio: 15, pv: 4000 },
  { categoria: "Otros", nombre: "[CHALLENGE] Noni 5+1", precio: 285, pv: 175000 },
  { categoria: "Otros", nombre: "Beauty & Personal Care Best Kit", precio: 300, pv: 200000 },
  { categoria: "Otros", nombre: "HemoBlend Kit", precio: 150, pv: 50000 },
  { categoria: "Otros", nombre: "Leaflet *50ea", precio: 15, pv: 0 },
  { categoria: "Otros", nombre: "Life Scenario (English) *10ea", precio: 10, pv: 0 },
  { categoria: "Otros", nombre: "Life Scenario (Spanish) *10ea", precio: 10, pv: 0 },
  { categoria: "Otros", nombre: "Non-Woven Fabric Shopping Bag *1ea", precio: 10, pv: 0 },
  { categoria: "Otros", nombre: "Plastic Bag *1ea", precio: 2, pv: 0 },
  { categoria: "Otros", nombre: "Shopping Bag (Blue) *1ea", precio: 1, pv: 0 },
  { categoria: "Otros", nombre: "Shopping Bag (White) *1ea", precio: 1, pv: 0 },
  ],
};

const CATALOGO_PRODUCTOS_NOTA = "Catálogo de referencia a partir de tu propia lista — Atomy actualiza sus productos con frecuencia y cada país tiene un catálogo distinto, así que puede estar desfasado. Edita, agrega o elimina productos aquí para mantenerlo al día.";

const CATALOGO_PRODUCTOS_NOTA_VACIO = "Aún no tenemos cargado el catálogo de este país. Toca \"+ Añadir producto\" para empezar a construirlo (o envíale a tu asistente capturas de pantalla de los precios/PV de tu país para cargarlo completo).";

const META_PV_QUINCENA = 2500000;

const MENSAJE_BIENVENIDA =
  "Ya conquistaste Sales Master — esta es tu siguiente montaña. Aquí vas a entender cómo funciona el plan de compensación completo, y a planear quincena a quincena con tu equipo para aprovechar cada punto y no perder ningún ciclaje.";

const IDIOMAS_INFORME = [
  { id: "es", label: "Español" },
  { id: "en", label: "English" },
  { id: "fr", label: "Français" },
  { id: "it", label: "Italiano" },
  { id: "ro", label: "Română" },
  { id: "pt", label: "Português" },
];

const INFORME_I18N = {
  es: { llamadas: "Llamadas", mensajes: "Mensajes de invitación", presentaciones: "Presentaciones (Show the Plan)", reuniones: "Reuniones / consultorías",
    tituloPersonal: "📊 Mi informe semanal de actividad (Cumbre Master):", cierrePersonal: "¿Qué te parece? ¿En qué puedo mejorar esta semana?",
    tituloEquipo: "👥 Informe semanal de mi equipo (Cumbre Master):", personasRed: "Personas en mi red esta quincena", verificados: "Verificados (ya pidieron sus puntos)", pendientes: "Pendientes por verificar", pvPlaneado: "PV total planeado", pvVerificado: "PV verificado", cierreEquipo: "Aquí va el resumen de mi equipo — ¿me ayudas a revisarlo?" },
  en: { llamadas: "Calls", mensajes: "Invitation messages", presentaciones: "Presentations (Show the Plan)", reuniones: "Meetings / consultations",
    tituloPersonal: "📊 My weekly activity report (Cumbre Master):", cierrePersonal: "What do you think? How can I improve this week?",
    tituloEquipo: "👥 My team's weekly report (Cumbre Master):", personasRed: "People in my network this period", verificados: "Verified (already ordered their points)", pendientes: "Pending verification", pvPlaneado: "Total planned PV", pvVerificado: "Verified PV", cierreEquipo: "Here's my team's summary — can you help me review it?" },
  fr: { llamadas: "Appels", mensajes: "Messages d'invitation", presentaciones: "Présentations (Show the Plan)", reuniones: "Réunions / consultations",
    tituloPersonal: "📊 Mon rapport d'activité hebdomadaire (Cumbre Master) :", cierrePersonal: "Qu'en penses-tu ? Comment puis-je m'améliorer cette semaine ?",
    tituloEquipo: "👥 Rapport hebdomadaire de mon équipe (Cumbre Master) :", personasRed: "Personnes dans mon réseau cette période", verificados: "Vérifiés (ont déjà commandé leurs points)", pendientes: "En attente de vérification", pvPlaneado: "PV total prévu", pvVerificado: "PV vérifié", cierreEquipo: "Voici le résumé de mon équipe — peux-tu m'aider à le revoir ?" },
  it: { llamadas: "Chiamate", mensajes: "Messaggi di invito", presentaciones: "Presentazioni (Show the Plan)", reuniones: "Riunioni / consulenze",
    tituloPersonal: "📊 Il mio report settimanale di attività (Cumbre Master):", cierrePersonal: "Cosa ne pensi? Come posso migliorare questa settimana?",
    tituloEquipo: "👥 Report settimanale del mio team (Cumbre Master):", personasRed: "Persone nella mia rete questo periodo", verificados: "Verificati (hanno già ordinato i loro punti)", pendientes: "In attesa di verifica", pvPlaneado: "PV totale pianificato", pvVerificado: "PV verificato", cierreEquipo: "Ecco il riepilogo del mio team — mi aiuti a rivederlo?" },
  ro: { llamadas: "Apeluri", mensajes: "Mesaje de invitație", presentaciones: "Prezentări (Show the Plan)", reuniones: "Întâlniri / consultații",
    tituloPersonal: "📊 Raportul meu săptămânal de activitate (Cumbre Master):", cierrePersonal: "Ce părere ai? Cum pot îmbunătăți săptămâna asta?",
    tituloEquipo: "👥 Raportul săptămânal al echipei mele (Cumbre Master):", personasRed: "Persoane în rețeaua mea în această perioadă", verificados: "Verificați (și-au comandat deja punctele)", pendientes: "În așteptarea verificării", pvPlaneado: "PV total planificat", pvVerificado: "PV verificat", cierreEquipo: "Iată rezumatul echipei mele — mă ajuți să-l revizuim?" },
  pt: { llamadas: "Chamadas", mensajes: "Mensagens de convite", presentaciones: "Apresentações (Show the Plan)", reuniones: "Reuniões / consultorias",
    tituloPersonal: "📊 Meu relatório semanal de atividade (Cumbre Master):", cierrePersonal: "O que você acha? Como posso melhorar esta semana?",
    tituloEquipo: "👥 Relatório semanal da minha equipe (Cumbre Master):", personasRed: "Pessoas na minha rede neste período", verificados: "Verificados (já pediram seus pontos)", pendientes: "Pendentes de verificação", pvPlaneado: "PV total planejado", pvVerificado: "PV verificado", cierreEquipo: "Aqui está o resumo da minha equipe — pode me ajudar a revisar?" },
};

function informeI18n(idioma) {
  return INFORME_I18N[idioma] || INFORME_I18N.es;
}

/* ---------------------------------------------------------------
   AGENDA SEMANAL — rutina de trabajo de un líder: llamadas y reuniones
   con afiliados, formaciones de equipo, reuniones de líderes y Zoom.
--------------------------------------------------------------- */

const DIAS_SEMANA = [
  { id: "lunes", label: "Lunes" },
  { id: "martes", label: "Martes" },
  { id: "miercoles", label: "Miércoles" },
  { id: "jueves", label: "Jueves" },
  { id: "viernes", label: "Viernes" },
  { id: "sabado", label: "Sábado" },
  { id: "domingo", label: "Domingo" },
];

const AGENDA_TIPOS = [
  { id: "llamada", label: "Llamada a un socio", icon: "phone-call" },
  { id: "reunion-afiliado", label: "Reunión con un afiliado", icon: "users" },
  { id: "consultoria", label: "Consultoría / seguimiento", icon: "target" },
  { id: "formacion", label: "Formación de equipo", icon: "book-open" },
  { id: "reunion-lideres", label: "Reunión de líderes", icon: "crown" },
];
