/* ---------------------------------------------------------------
   LICENCIA — marca de agua sutil por comprador.
   Antes de desplegar una copia de esta app para un líder que la haya
   comprado, cambia el valor de abajo con su nombre (y opcionalmente su
   rango) y despliega esa copia con un nombre de proyecto propio en Vercel.
   No es un candado técnico — es una firma visible en la app que deja
   claro de quién es esa copia si alguna vez circula fuera de su equipo.
   Déjalo en "" para una copia sin licencia asignada (uso propio, demos).
--------------------------------------------------------------- */
const LICENCIA_TITULAR = "";

/* ---------------------------------------------------------------
   CONTENIDO — Cumbre Master: Plan de Compensación (Sales Master → Imperial Master)
   Fuente: documento oficial de distribución de comisiones (Colombia, en COP).
   Los valores en USD son una conversión aproximada de referencia (~4.000 COP = 1 USD),
   sujeta a la tasa de cambio (TRM) real de cada momento.
--------------------------------------------------------------- */

const DISTRIBUCION = {
  intro: "Din suma totală generată de vânzările companiei, 35% se rezervă pentru comisioane și stimulente. Acel 35% devine 100% din PV, care se împart astfel:",
  partes: [
    { pct: "44%", nombre: "Comisionul General", detalle: "Se împarte între toți membrii, în funcție de nivelul lor de grad și de punctaj.", icon: "users" },
    { pct: "20%", nombre: "Comisionul de Măiestrie", detalle: "Se împarte între cei care au atins deja un rang de Măiestrie (de la Sales Master în sus).", icon: "mountain-flag" },
    { pct: "6%", nombre: "Comisionul Centrului de Educație", detalle: "Merge la centrul educațional din care faci parte, pentru a-i acoperi cheltuielile operaționale.", icon: "book-open" },
    { pct: "30%", nombre: "Profitul net al companiei", detalle: "Este partea care rămâne pentru Atomy.", icon: "package" },
  ],
  notaPeriodo: "Perioada de acumulare a punctelor este mereu de la 1 la 15, și de la 16 până la finalul lunii — adică două quincene pe lună.",
};

const COMISION_GENERAL = [
  { nivel: "al 8-lea", puntos: "5 puncte", condicion: "Reprezentant de Vânzări — acumulat de la 10.000 la 299.999 PV personale.", piernaDebil: "≥ 300.000 PV" },
  { nivel: "al 7-lea", puntos: "15 puncte", condicion: "Agent — minimum 300.000 PV personale, sau linia mai slabă cu 600.000 PV acumulate în luna anterioară.", piernaDebil: "≥ 300.000 PV" },
  { nivel: "al 6-lea", puntos: "30 puncte", condicion: "Agent Special — minimum 700.000 PV personale, sau linia mai slabă cu 1,4M PV în luna anterioară.", piernaDebil: "≥ 700.000 PV" },
  { nivel: "al 5-lea", puntos: "60 puncte", condicion: "Distribuitor — minimum 1,5M PV personale, sau linia mai slabă cu 3M PV în luna anterioară.", piernaDebil: "≥ 1.500.000 PV" },
  { nivel: "al 4-lea", puntos: "90 puncte", condicion: "Distribuitor Special — minimum 2,4M PV personale, sau linia mai slabă cu 4,8M PV în luna anterioară.", piernaDebil: "≥ 2.400.000 PV" },
  { nivel: "al 3-lea", puntos: "150 puncte", condicion: "Continuă scala de Distribuitor Special, cu un volum mai mare pe linia mai slabă.", piernaDebil: "≥ 6.000.000 PV" },
  { nivel: "al 2-lea", puntos: "250 puncte", condicion: "Continuă scala de Distribuitor Special, cu un volum mai mare pe linia mai slabă.", piernaDebil: "≥ 20.000.000 PV" },
  { nivel: "1-ul", puntos: "300 puncte", condicion: "Continuă scala de Distribuitor Special, cu un volum mai mare pe linia mai slabă.", piernaDebil: "≥ 50.000.000 PV" },
];

const COMISION_GENERAL_NOTA = "Comisioanele se plătesc marțea următoare, socotind acumulatul zilnic din miercuri până în acea marți (data exactă poate varia în funcție de banca locală). PV-urile tale personale se adaugă mereu la linia ta mai slabă.";

const RANGOS_MASTER = [
  {
    n: 0, nombre: "Sales Master", icon: "mountain-flag",
    prerrequisito: "Minimum 2.500.000 PV de grup pe fiecare linie și 700.000 PV personale. Dacă totalul PV al liniei tale mai slabe trece de 300.000 PV, PV-urile personale pe care le generezi în perioada respectivă se pot aduna la acea linie pentru a completa Măiestria.",
    comisionMaestria: "10% din totalul PV al companiei, împărțit în părți egale între toți Sales Master.",
    promocion: "Bonus de 1.500.000 COP (≈ 375 USD) prima dată când atingi rangul, transferat direct în contul tău.",
    criterio: "Fără restricții pentru a avansa — trebuie doar să îndeplinești cerința acestei quincene.",
    montos: [{ etiqueta: "Bonus la atingerea rangului", cop: 1500000 }],
  },
  {
    n: 1, nombre: "Diamond Master", icon: "gem",
    prerrequisito: "Minimum 2 Sales Master pe fiecare linie și 1.500.000 PV personale.",
    comisionMaestria: "5% din totalul PV, împărțit între Diamond Master și măiestriile superioare.",
    promocion: "Bonus de 1.500.000 COP (≈ 375 USD) prima dată, plus un bonus de avansare de aproximativ 3.000.000 COP (≈ 750 USD).",
    criterio: "Fără restricții pentru a avansa.",
    montos: [
      { etiqueta: "Bonus la atingerea rangului", cop: 1500000 },
      { etiqueta: "Bonus de avansare", cop: 3000000 },
    ],
  },
  {
    n: 2, nombre: "Sharon Rose Master", icon: "sparkles",
    prerrequisito: "Minimum 2 Diamond Master pe fiecare linie și 2.400.000 PV personale.",
    comisionMaestria: "2% din totalul PV, împărțit între Sharon Rose Master și măiestriile superioare.",
    promocion: "Aproximativ 7.600.000 COP (≈ 1.900 USD) transferați în contul tău, plus o călătorie pentru 2 persoane.",
    criterio: "Fără restricții pentru a avansa.",
    montos: [{ etiqueta: "Bonus la atingerea rangului", cop: 7600000 }],
  },
  {
    n: 3, nombre: "Star Master", icon: "star",
    prerrequisito: "Minimum 2 Sharon Rose Master pe fiecare linie.",
    comisionMaestria: "1,2% din totalul PV, împărțit între Star Master și măiestriile superioare.",
    promocion: "Aproximativ 38.000.000 COP (≈ 9.500 USD) transferați în contul tău, plus o călătorie pentru 4 persoane.",
    criterio: "Trebuie să te fi calificat ca Sharon Rose Master de 3 ori înainte de a putea avansa la Star Master.",
    montos: [{ etiqueta: "Bonus la atingerea rangului", cop: 38000000 }],
  },
  {
    n: 4, nombre: "Royal Master", icon: "crown",
    prerrequisito: "Minimum 2 Star Master pe fiecare linie.",
    comisionMaestria: "1% din totalul PV, împărțit între Royal Master și măiestriile superioare.",
    promocion: "Aproximativ 190.000.000 COP (≈ 47.500 USD) transferați în contul tău, o călătorie pentru 4 persoane, un card de debit de aproximativ 7.600.000 COP (≈ 1.900 USD) și chiria unui automobil.",
    criterio: "Trebuie să te fi calificat ca Star Master de 3 ori înainte de a putea avansa la Royal Master.",
    montos: [
      { etiqueta: "Bonus la atingerea rangului", cop: 190000000 },
      { etiqueta: "Card de debit", cop: 7600000 },
    ],
  },
  {
    n: 5, nombre: "Crown Master", icon: "award",
    prerrequisito: "Minimum 2 Royal Master pe fiecare linie.",
    comisionMaestria: "0,5% din totalul PV, împărțit între Crown Master și Imperial Master.",
    promocion: "Aproximativ 1.150.000.000 COP (≈ 287.500 USD) transferați în contul tău, o călătorie pentru 4 persoane, un card de debit de aproximativ 19.000.000 COP (≈ 4.750 USD) și un automobil de lux propriu.",
    criterio: "Trebuie să te fi calificat ca Royal Master de 3 ori înainte de a putea avansa la Crown Master.",
    montos: [
      { etiqueta: "Bonus la atingerea rangului", cop: 1150000000 },
      { etiqueta: "Card de debit", cop: 19000000 },
    ],
  },
  {
    n: 6, nombre: "Imperial Master", icon: "trophy",
    prerrequisito: "Minimum 2 Crown Master pe fiecare linie.",
    comisionMaestria: "0,3% din totalul PV, împărțit între Imperial Master.",
    promocion: "Aproximativ 3.800.000.000 COP (≈ 950.000 USD) transferați în contul tău, o călătorie pentru 4 persoane, un card de debit de aproximativ 38.000.000 COP (≈ 9.500 USD), un automobil de lux propriu cu șofer și un birou cu asistent personal.",
    criterio: "Trebuie să te fi calificat ca Crown Master de 3 ori înainte de a putea avansa la Imperial Master — cel mai înalt rang al planului.",
    montos: [
      { etiqueta: "Bonus la atingerea rangului", cop: 3800000000 },
      { etiqueta: "Card de debit", cop: 38000000 },
    ],
  },
];

/* ---------------------------------------------------------------
   CONVERSIÓN DE MONEDA POR PAÍS (para "Mi Rango")
   Todos los montos oficiales de RANGOS_MASTER están en COP. Estas tasas
   son aproximadas ~2024, solo para referencia visual en pantalla — no son
   datos financieros exactos ni se actualizan con el mercado. La comisión
   real siempre se calcula y liquida con base en el valor del Won coreano
   (KRW) del momento, así que el monto que ve cada líder en su moneda local
   varía según la tasa de cambio real de cada fecha.
--------------------------------------------------------------- */
const TASAS_COP_POR_MONEDA = {
  COP: 1,
  USD: 4000,
  EUR: 4300,
  MXN: 230,
  BRL: 720,
  CAD: 2900,
};

function convertirDesdeCOP(montoCOP, monedaDestino) {
  const tasa = TASAS_COP_POR_MONEDA[monedaDestino] || TASAS_COP_POR_MONEDA.COP;
  return Number(montoCOP || 0) / tasa;
}

const NOTA_MONEDA_APROX = "Sumele de mai sus sunt o estimare (aprox.) convertită în moneda ta locală — comisionul real se calculează și se plătește mereu pe baza valorii Won-ului coreean (KRW) din acel moment și variază în funcție de rata de schimb din fiecare dată.";

const CRITERIOS_GENERALES = [
  "Odată ce atingi un rang de Măiestrie, îl păstrezi definitiv: nu există condiții pentru a-l menține.",
  "Nu este posibil să avansezi două niveluri de Măiestrie într-o singură perioadă, cu excepția până la Diamond Master; de la Sharon Rose Master în sus, avansarea se face mereu cu un nivel o dată.",
  "Nu există un termen limită pentru a avansa — trebuie doar să păstrezi o calitate de membru valabilă.",
  "Comisionul de Măiestrie se plătește de două ori pe lună: pe data de 15 și, de asemenea, în ziua a 7-a după închiderea lunară.",
];

/* Los montos oficiales siempre están en pesos colombianos (COP) y antes de
   impuestos — cada etiqueta se convierte a la moneda del país activo con
   formatMonedaAprox() al momento de renderizar (ver NOTA_MONEDA_APROX). */
const NOTAS_VALORES = [
  { etiqueta: "Călătorie pentru Sharon Rose Master și Star Master", cop: 3817000, sufijo: "de persoană" },
  { etiqueta: "Călătorie pentru Royal Master, Crown Master și Imperial Master", cop: 15286000, sufijo: "de persoană" },
  { etiqueta: "Chiria automobilului de Royal Master", cop: 3817000, sufijo: "lunar" },
  { etiqueta: "Automobil de lux de Crown Master", cop: 244288000, sufijo: "" },
  { etiqueta: "Automobil de lux de Imperial Master", cop: 297726000, sufijo: "" },
  { etiqueta: "Birou în chirie (Imperial Master)", cop: 9542500, sufijo: "lunar" },
  { etiqueta: "Asistent personal (Imperial Master)", cop: 5725500, sufijo: "lunar" },
  { etiqueta: "Șofer (Imperial Master)", cop: 7634000, sufijo: "lunar" },
];

const CLUBES_EXITO = [
  { nombre: "AutoSales Master", requisito: "Să te recalifici ca Sales Master de 12 ori într-un an (o dată pe quincenă, în medie).", ingresoCopMin: 8000000, ingresoCopMax: 12000000, ingresoSufijo: "lunar" },
  { nombre: "Clubul Liderilor", ingresoAnualCop: 350000000 },
  { nombre: "Clubul Liderilor Royal", ingresoAnualCop: 700000000 },
  { nombre: "Clubul Liderilor Crown", ingresoAnualCop: 1500000000 },
  { nombre: "Clubul Liderilor Imperial", requisito: "Să ajungi Imperial Master." },
];

const PAISES_CATALOGO = [
  { id: "CO", label: "Columbia", moneda: "COP", simbolo: "$", locale: "es-CO", codigo: "+57" },
  { id: "EU", label: "Europa", moneda: "EUR", simbolo: "€", locale: "es-ES", codigo: "+34" },
  { id: "MX", label: "Mexic", moneda: "MXN", simbolo: "$", locale: "es-MX", codigo: "+52" },
  { id: "BR", label: "Brazilia", moneda: "BRL", simbolo: "R$", locale: "pt-BR", codigo: "+55" },
  { id: "CA", label: "Canada", moneda: "CAD", simbolo: "$", locale: "en-CA", codigo: "+1" },
  { id: "US", label: "Statele Unite", moneda: "USD", simbolo: "$", locale: "en-US", codigo: "+1" },
];

const CATALOGO_PRODUCTOS_POR_PAIS = {
  CO: [
  { categoria: "Îngrijire Personală", nombre: "Absolute Acondicionador - Paso 3", precio: 78000, pv: 8000 },
  { categoria: "Îngrijire Personală", nombre: "Absolute Shampoo - Paso 1", precio: 78000, pv: 8000 },
  { categoria: "Îngrijire Personală", nombre: "Absolute Tratamiento - Paso 2", precio: 53000, pv: 5000 },
  { categoria: "Îngrijire Personală", nombre: "Acondicionador Herbal para Cabello", precio: 53800, pv: 5700 },
  { categoria: "Îngrijire Personală", nombre: "Aidam Limpiador Íntimo Unisex", precio: 25000, pv: 2000 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Exfoliante Corporal a Base de Sal", precio: 75000, pv: 8300 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Homme All-in-One Wash", precio: 70600, pv: 7400 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Homme Multi-Action Cleanser", precio: 50000, pv: 5000 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Root Vital Hair Care Set", precio: 219000, pv: 22500 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Sculpture Acondicionador - Paso 2", precio: 62400, pv: 6200 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Sculpture Shampoo - Paso 1", precio: 62400, pv: 6200 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Shampoo de Proteína", precio: 80000, pv: 8000 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Tónico para Cabello", precio: 56600, pv: 5600 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Tratamiento Líquido de Proteína", precio: 60000, pv: 6500 },
  { categoria: "Îngrijire Personală", nombre: "Cepillo Dental (8 unidades)", precio: 37000, pv: 5300 },
  { categoria: "Îngrijire Personală", nombre: "Cepillo Dental Niños (8 unidades)", precio: 48300, pv: 4200 },
  { categoria: "Îngrijire Personală", nombre: "Crema de Manos", precio: 53600, pv: 7400 },
  { categoria: "Îngrijire Personală", nombre: "Esencia para Rizos", precio: 44000, pv: 5400 },
  { categoria: "Îngrijire Personală", nombre: "Hand Balm Butter 50ml", precio: 24000, pv: 2800 },
  { categoria: "Îngrijire Personală", nombre: "Hand Balm Marine 50ml", precio: 24000, pv: 2800 },
  { categoria: "Îngrijire Personală", nombre: "Hand Balm Pure 50ml", precio: 24000, pv: 2800 },
  { categoria: "Îngrijire Personală", nombre: "Jabón de Manos", precio: 15400, pv: 1100 },
  { categoria: "Îngrijire Personală", nombre: "Kit de Viaje (6 piezas)", precio: 91000, pv: 5000 },
  { categoria: "Îngrijire Personală", nombre: "Limpiador Herbal para Cuerpo", precio: 39800, pv: 3500 },
  { categoria: "Îngrijire Personală", nombre: "Loción Corporal", precio: 42400, pv: 3520 },
  { categoria: "Îngrijire Personală", nombre: "Óleo Esencial para el Cabello", precio: 49200, pv: 5600 },
  { categoria: "Îngrijire Personală", nombre: "Pasta dental 200g (x5 unidades)", precio: 71200, pv: 3600 },
  { categoria: "Îngrijire Personală", nombre: "Pasta dental 50g (x4 unidades)", precio: 23100, pv: 3300 },
  { categoria: "Îngrijire Personală", nombre: "Pasta Dental Sensitive (x3 unidades)", precio: 48000, pv: 4800 },
  { categoria: "Îngrijire Personală", nombre: "Root Vital Hair Shampoo", precio: 95000, pv: 9100 },
  { categoria: "Îngrijire Personală", nombre: "Set de Ampolletas Para Cuero Cabelludo Root Vital (X3)", precio: 178000, pv: 24000 },
  { categoria: "Îngrijire Personală", nombre: "Shampoo Herbal para Cabello", precio: 53800, pv: 5700 },
  { categoria: "Îngrijire Personală", nombre: "Sistema de Cuidado Bucal (x4 kits)", precio: 55000, pv: 6500 },
  { categoria: "Îngrijire Personală", nombre: "Spray de Propóleo Verde (x3 unidades)", precio: 110000, pv: 9500 },
  { categoria: "Îngrijire Personală", nombre: "Terapia para Manos (x4 unidades)", precio: 63500, pv: 6600 },
  { categoria: "Îngrijire Personală", nombre: "Tratamiento Herbal para Cabello", precio: 29700, pv: 2900 },
  { categoria: "Îngrijire Personală", nombre: "Tratamiento Root Vital", precio: 72000, pv: 8000 },
  { categoria: "Casă", nombre: "Atomy Esponjillas de Acero Inoxidable (x2 unidades)", precio: 16900, pv: 750 },
  { categoria: "Casă", nombre: "Atomy Scratch Free Scrubber", precio: 20000, pv: 1400 },
  { categoria: "Casă", nombre: "Detergente en Polvo para Ropa (x2 unidades)", precio: 57700, pv: 4000 },
  { categoria: "Casă", nombre: "Detergente Lavatrastes", precio: 32700, pv: 3400 },
  { categoria: "Casă", nombre: "Detergente Líquido para Ropa", precio: 54000, pv: 4800 },
  { categoria: "Casă", nombre: "Guantes de Látex (M) *2 pares", precio: 23900, pv: 1300 },
  { categoria: "Casă", nombre: "Suavizante de Telas", precio: 46200, pv: 3700 },
  { categoria: "Alimente", nombre: "Aceite de Aguacate Extra Virgen", precio: 90000, pv: 8000 },
  { categoria: "Alimente", nombre: "Atomy Sí Puer (X 30 sobres)", precio: 122000, pv: 13600 },
  { categoria: "Alimente", nombre: "Café Arábica Black (x80 sobres)", precio: 95000, pv: 5200 },
  { categoria: "Alimente", nombre: "Café Arábica Zero Sugar X 100 Sobres", precio: 149000, pv: 5500 },
  { categoria: "Alimente", nombre: "Crema no Láctea (x50 sobres)", precio: 53100, pv: 2200 },
  { categoria: "HemoHIM", nombre: "Atomy HemoHIM *4set", precio: 1700000, pv: 300000 },
  { categoria: "HemoHIM", nombre: "Bolsa de Regalo (20cm x 31cm)", precio: 1500, pv: 0 },
  { categoria: "HemoHIM", nombre: "Bolsa reutilizable HemoHIM", precio: 4200, pv: 0 },
  { categoria: "HemoHIM", nombre: "Combo HemoHIM x 2 set", precio: 880000, pv: 150000 },
  { categoria: "HemoHIM", nombre: "HemoHIM (x60 sobres)", precio: 440000, pv: 70000 },
  { categoria: "Îngrijirea Pielii", nombre: "Absolute Ampolla - Paso 2", precio: 196000, pv: 28600 },
  { categoria: "Îngrijirea Pielii", nombre: "Absolute CellActive (1 Set con 6 productos)", precio: 880000, pv: 130000 },
  { categoria: "Îngrijirea Pielii", nombre: "Absolute Contorno de Ojos - Paso 5", precio: 163500, pv: 23400 },
  { categoria: "Îngrijirea Pielii", nombre: "Absolute Crema Nutritiva - Paso 6", precio: 147800, pv: 20800 },
  { categoria: "Îngrijirea Pielii", nombre: "Absolute Loción - Paso 4", precio: 147800, pv: 20800 },
  { categoria: "Îngrijirea Pielii", nombre: "Absolute Suero - Paso 3", precio: 163500, pv: 23400 },
  { categoria: "Îngrijirea Pielii", nombre: "Absolute Tónico - Paso 1", precio: 147800, pv: 20800 },
  { categoria: "Îngrijirea Pielii", nombre: "Aceite Limpiador", precio: 79300, pv: 8100 },
  { categoria: "Îngrijirea Pielii", nombre: "Adelica Máscara de Pestañas Long-Lash", precio: 64000, pv: 6800 },
  { categoria: "Îngrijirea Pielii", nombre: "Adelica Máscara de Pestañas Volumen", precio: 64000, pv: 6800 },
  { categoria: "Îngrijirea Pielii", nombre: "Aplicador Atomy Absolute", precio: 18000, pv: 2000 },
  { categoria: "Îngrijirea Pielii", nombre: "Atomy Absolute Hydra Balm", precio: 62000, pv: 8800 },
  { categoria: "Îngrijirea Pielii", nombre: "Atomy Absolute Protector Solar", precio: 53000, pv: 5000 },
  { categoria: "Îngrijirea Pielii", nombre: "Atomy Absolute Snow Crema de Día - Paso 3", precio: 131000, pv: 18500 },
  { categoria: "Îngrijirea Pielii", nombre: "Atomy Absolute Snow Crema de Noche - Paso 4", precio: 139000, pv: 19500 },
  { categoria: "Îngrijirea Pielii", nombre: "Atomy Absolute Snow Dark Spot Corrector - Noche Paso 2", precio: 90000, pv: 12000 },
  { categoria: "Îngrijirea Pielii", nombre: "Atomy Absolute Snow Protector Solar", precio: 78000, pv: 9000 },
  { categoria: "Îngrijirea Pielii", nombre: "Atomy Absolute Snow Set (5 productos)", precio: 552000, pv: 92000 },
  { categoria: "Îngrijirea Pielii", nombre: "Atomy Absolute Snow Suero - Día Paso 2 / Noche Paso 3", precio: 139000, pv: 18500 },
  { categoria: "Îngrijirea Pielii", nombre: "Atomy Absolute Snow Tónico - Día/Noche Paso 1", precio: 106000, pv: 14600 },
  { categoria: "Îngrijirea Pielii", nombre: "Atomy Loción de Protección Solar", precio: 130000, pv: 15000 },
  { categoria: "Îngrijirea Pielii", nombre: "Atomy Mascarilla de Arcilla Hinoki", precio: 73000, pv: 9700 },
  { categoria: "Îngrijirea Pielii", nombre: "Atomy Sun Stick", precio: 45500, pv: 4700 },
  { categoria: "Îngrijirea Pielii", nombre: "Bálsamo Labial", precio: 21200, pv: 2200 },
  { categoria: "Îngrijirea Pielii", nombre: "Brillo Labial", precio: 50700, pv: 5300 },
  { categoria: "Îngrijirea Pielii", nombre: "Cream Mist", precio: 58000, pv: 8000 },
  { categoria: "Îngrijirea Pielii", nombre: "Crema BB", precio: 38500, pv: 2800 },
  { categoria: "Îngrijirea Pielii", nombre: "Cuidado Nocturno 4 Pasos (1 Set)", precio: 156600, pv: 14300 },
  { categoria: "Îngrijirea Pielii", nombre: "Desmaquillante Bifásico", precio: 48000, pv: 5000 },
  { categoria: "Îngrijirea Pielii", nombre: "Espuma Limpiadora - Paso 2", precio: 39600, pv: 3400 },
  { categoria: "Îngrijirea Pielii", nombre: "Gel Exfoliante - Paso 3", precio: 39600, pv: 3400 },
  { categoria: "Îngrijirea Pielii", nombre: "Hydra Brightening Care Set", precio: 170000, pv: 25000 },
  { categoria: "Îngrijirea Pielii", nombre: "Kit de Viaje (6 piezas)", precio: 91000, pv: 5000 },
  { categoria: "Îngrijirea Pielii", nombre: "Lápiz de Cejas (Café)", precio: 35000, pv: 4200 },
  { categoria: "Îngrijirea Pielii", nombre: "Limpiador Profundo - Paso 1", precio: 39600, pv: 3400 },
  { categoria: "Îngrijirea Pielii", nombre: "Marine Ampoule Mask Brightening & Firming (x10 unidades)", precio: 120000, pv: 18000 },
  { categoria: "Îngrijirea Pielii", nombre: "Mascarilla de Oro 24K", precio: 160000, pv: 23000 },
  { categoria: "Îngrijirea Pielii", nombre: "Mascarilla Diaria Expert (Hidratante) (x10 unidades)", precio: 46000, pv: 4500 },
  { categoria: "Îngrijirea Pielii", nombre: "Mascarilla Peel-Off - Paso 4", precio: 39600, pv: 3400 },
  { categoria: "Îngrijirea Pielii", nombre: "Parche para Ojos de Hidrogel (x60 Parches)", precio: 82000, pv: 10000 },
  { categoria: "Îngrijirea Pielii", nombre: "Peeling Pad", precio: 53000, pv: 7000 },
  { categoria: "Îngrijirea Pielii", nombre: "Protector Solar Beige (x1)", precio: 39800, pv: 3600 },
  { categoria: "Îngrijirea Pielii", nombre: "Protector Solar Blanco (x1)", precio: 39800, pv: 3600 },
  { categoria: "Îngrijirea Pielii", nombre: "Sistema Cuidado para la Piel The Fame (1 Set con 5 Productos)", precio: 400000, pv: 57200 },
  { categoria: "Îngrijirea Pielii", nombre: "Sobre Individual Marine Ampoule Mask Brightening", precio: 13000, pv: 1200 },
  { categoria: "Îngrijirea Pielii", nombre: "The Fame Crema Esencia - Paso 3", precio: 89400, pv: 12500 },
  { categoria: "Îngrijirea Pielii", nombre: "The Fame Crema Nutritiva - Paso 5", precio: 84300, pv: 11700 },
  { categoria: "Îngrijirea Pielii", nombre: "The Fame Crema para Ojos - Paso 2", precio: 84300, pv: 11700 },
  { categoria: "Îngrijirea Pielii", nombre: "The Fame Loción - Paso 4", precio: 84300, pv: 11700 },
  { categoria: "Îngrijirea Pielii", nombre: "The Fame Tónico - Paso 1", precio: 84300, pv: 11700 },
  { categoria: "Sănătate", nombre: "Atomy Fibra Psyllium Husk (x45 sobres)", precio: 135000, pv: 19100 },
  { categoria: "Sănătate", nombre: "Atomy Spirulina & SOD", precio: 147000, pv: 17000 },
  { categoria: "Sănătate", nombre: "Caja Individual Probióticos", precio: 81000, pv: 8000 },
  { categoria: "Sănătate", nombre: "E-Omega 3 (x180 Cápsulas)", precio: 110000, pv: 10000 },
  { categoria: "Sănătate", nombre: "Fermento de Noni Concentrado", precio: 270000, pv: 35000 },
  { categoria: "Sănătate", nombre: "Fermento de Noni Sachet (24 sobres)", precio: 295000, pv: 39500 },
  { categoria: "Sănătate", nombre: "Gel de Manzana Verde (x28 sobres)", precio: 128000, pv: 15000 },
  { categoria: "Sănătate", nombre: "Gomitas de Propóleo y Zinc", precio: 120000, pv: 11000 },
  { categoria: "Sănătate", nombre: "Hierro (x60 sobres)", precio: 138000, pv: 15000 },
  { categoria: "Sănătate", nombre: "Probióticos 10+ (4 Cajas x 30 sobres, total 120 sobres)", precio: 290000, pv: 30000 },
  { categoria: "Sănătate", nombre: "Rutina Detox + PVs", precio: 539000, pv: 75000 },
  { categoria: "Sănătate", nombre: "Rutina Fortalece + PVs", precio: 688000, pv: 110000 },
  { categoria: "Promoții", nombre: "Absolute Recargado", precio: 1760000, pv: 300000 },
  { categoria: "Promoții", nombre: "Combo Evolución Fitness", precio: 500000, pv: 55000 },
  { categoria: "Promoții", nombre: "Combo Imperial 2026", precio: 2049000, pv: 300000 },
  { categoria: "Promoții", nombre: "Combo San Valentín", precio: 261700, pv: 28100 },
  { categoria: "Promoții", nombre: "Promo Noni 5+1", precio: 1350000, pv: 175000 },
  { categoria: "Promoții", nombre: "Rutina Equilibrio + PVs", precio: 720000, pv: 100000 },
  { categoria: "Diverse", nombre: "Balanza y Muñequera de Skincare", precio: 24000, pv: 0 },
  { categoria: "Diverse", nombre: "Bolsa Laminada (x1)", precio: 1700, pv: 0 },
  { categoria: "Diverse", nombre: "Bolsa Multiusos (x1)", precio: 2600, pv: 0 },
  { categoria: "Diverse", nombre: "Cartilla Escenario de Vida (x10 unidades)", precio: 25000, pv: 0 },
  { categoria: "Diverse", nombre: "Cosmetiquera Atomy Merch", precio: 24000, pv: 0 },
  { categoria: "Diverse", nombre: "Cuaderno Oficial Atomy Colombia", precio: 24900, pv: 0 },
  { categoria: "Diverse", nombre: "Gorra Oficial Atomy Colombia", precio: 34000, pv: 0 },
  { categoria: "Diverse", nombre: "Maleta Oficial Atomy", precio: 99000, pv: 0 },
  { categoria: "Diverse", nombre: "Muñequito Han Gil Park (Limitado)", precio: 42000, pv: 0 },
  { categoria: "Diverse", nombre: "Pin Amplifica", precio: 14000, pv: 0 },
  { categoria: "Diverse", nombre: "Pin Metálico Oficial Atomy Colombia", precio: 12000, pv: 0 },
  { categoria: "Diverse", nombre: "Pin Metálico Oficial HemoHIM", precio: 12000, pv: 0 },
  ],
  EU: [
  { categoria: "Îngrijire Personală", nombre: "Acondicionador Herbal", precio: 15, pv: 4000 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Cerakids Shampoo & Bath *1EA", precio: 13.5, pv: 6500 },
  { categoria: "Îngrijire Personală", nombre: "Cepillo de Dientes (8 unidades)", precio: 7.99, pv: 5000 },
  { categoria: "Îngrijire Personală", nombre: "Cera de Cabello & Anti-Yea", precio: 13.5, pv: 6000 },
  { categoria: "Îngrijire Personală", nombre: "Champú Herbal", precio: 14.5, pv: 7000 },
  { categoria: "Îngrijire Personală", nombre: "Complejo de Aceite Capilar", precio: 13.5, pv: 6000 },
  { categoria: "Îngrijire Personală", nombre: "Crema Corporal Ultra Rich", precio: 14.5, pv: 7000 },
  { categoria: "Îngrijire Personală", nombre: "Cuidado de Cuello Brazil (Kit)", precio: 14.5, pv: 7000 },
  { categoria: "Îngrijire Personală", nombre: "Dental Sonic Herbal Head Bundle", precio: 85, pv: 67000 },
  { categoria: "Îngrijire Personală", nombre: "Dental Sonic Refill Head", precio: 14.5, pv: 8000 },
  { categoria: "Îngrijire Personală", nombre: "Foot Scrub Wash", precio: 11, pv: 6000 },
  { categoria: "Îngrijire Personală", nombre: "Fresh Sun Lotion", precio: 25, pv: 16000 },
  { categoria: "Îngrijire Personală", nombre: "Hand Therapy 4 Kit", precio: 16.5, pv: 6200 },
  { categoria: "Îngrijire Personală", nombre: "Limpiador de Manos", precio: 15.5, pv: 5000 },
  { categoria: "Îngrijire Personală", nombre: "Limpiador Multi-Acción Homme", precio: 12.5, pv: 5000 },
  { categoria: "Îngrijire Personală", nombre: "Loción Corporal", precio: 12, pv: 6000 },
  { categoria: "Îngrijire Personală", nombre: "Pasta de Dientes 200g x5 Tubos", precio: 18.5, pv: 6000 },
  { categoria: "Îngrijire Personală", nombre: "Pasta de Dientes 50g x4", precio: 6.5, pv: 2000 },
  { categoria: "Îngrijire Personală", nombre: "Proteína Intensiva Shampoo", precio: 20, pv: 10000 },
  { categoria: "Îngrijire Personală", nombre: "Proteína Intensiva Tratamiento", precio: 16.5, pv: 9500 },
  { categoria: "Îngrijire Personală", nombre: "Root Nourishing Lotion", precio: 12, pv: 7000 },
  { categoria: "Îngrijire Personală", nombre: "Saengmodan Hair Tonic", precio: 14, pv: 7000 },
  { categoria: "Îngrijire Personală", nombre: "Sal de Baño Ultra Rich", precio: 14, pv: 6000 },
  { categoria: "Îngrijire Personală", nombre: "Scalpcare 2 Set", precio: 28, pv: 11000 },
  { categoria: "Îngrijire Personală", nombre: "Scalpcare Acondicionador", precio: 14.5, pv: 6000 },
  { categoria: "Îngrijire Personală", nombre: "Scalpcare Hair Champú", precio: 14.5, pv: 6000 },
  { categoria: "Îngrijire Personală", nombre: "Silk & Protein Hair Essence", precio: 13.5, pv: 6000 },
  { categoria: "Îngrijire Personală", nombre: "Sistema de Cuidado Bucal 1 Set (4 pcs)", precio: 14.5, pv: 7000 },
  { categoria: "Îngrijire Personală", nombre: "Sun Stick", precio: 12, pv: 5000 },
  { categoria: "Îngrijire Personală", nombre: "Travel Cleansing Kit Set", precio: 17, pv: 3800 },
  { categoria: "Îngrijire Personală", nombre: "Ultra Fine Wash", precio: 17.5, pv: 7000 },
  { categoria: "Îngrijire Personală", nombre: "Ultra Rich Body Set", precio: 27, pv: 13000 },
  { categoria: "Alimente", nombre: "Cafe Arabica 3 in 1 (50 sticks)", precio: 12.5, pv: 2000 },
  { categoria: "Alimente", nombre: "Cafe Arabica Black", precio: 16, pv: 5000 },
  { categoria: "Alimente", nombre: "Fermented Noni Drink Pouch", precio: 56.5, pv: 37000 },
  { categoria: "Alimente", nombre: "Noni Pouch x4 Set", precio: 226, pv: 150000 },
  { categoria: "Alimente", nombre: "Té Pu'er", precio: 25, pv: 14000 },
  { categoria: "Suplimente Alimentare", nombre: "Bióticos 10 Plus", precio: 29.5, pv: 15000 },
  { categoria: "Suplimente Alimentare", nombre: "E-Omega 3", precio: 22.5, pv: 9000 },
  { categoria: "Suplimente Alimentare", nombre: "Espirulina Pura 100%", precio: 24, pv: 10000 },
  { categoria: "Suplimente Alimentare", nombre: "Eye Lutein", precio: 32, pv: 15000 },
  { categoria: "Suplimente Alimentare", nombre: "Hemohim G (4 set)", precio: 420, pv: 300000 },
  { categoria: "Suplimente Alimentare", nombre: "Hemohim G - EU", precio: 105, pv: 73000 },
  { categoria: "Suplimente Alimentare", nombre: "Hongsdaman", precio: 77.5, pv: 55000 },
  { categoria: "Suplimente Alimentare", nombre: "Inner Collagen", precio: 34, pv: 19000 },
  { categoria: "Suplimente Alimentare", nombre: "Noni Bottle", precio: 49, pv: 35000 },
  { categoria: "Suplimente Alimentare", nombre: "Pomegranate Mixed Fruit Jelly", precio: 67.5, pv: 30000 },
  { categoria: "Suplimente Alimentare", nombre: "Vitamina C", precio: 22.5, pv: 9000 },
  { categoria: "Frumusețe", nombre: "Absolute Ampolla", precio: 41, pv: 27000 },
  { categoria: "Frumusețe", nombre: "Absolute Crema Nutritiva", precio: 37, pv: 23000 },
  { categoria: "Frumusețe", nombre: "Absolute Crema Spot-Out", precio: 36, pv: 23000 },
  { categoria: "Frumusețe", nombre: "Absolute Loción", precio: 37, pv: 23000 },
  { categoria: "Frumusețe", nombre: "Absolute Mix 21 Saldito", precio: 17.5, pv: 6000 },
  { categoria: "Frumusețe", nombre: "Absolute Protector Solar Esencia", precio: 12.5, pv: 6000 },
  { categoria: "Frumusețe", nombre: "Absolute Skincare Set", precio: 195, pv: 115000 },
  { categoria: "Frumusețe", nombre: "Absolute Suero", precio: 40, pv: 26000 },
  { categoria: "Frumusețe", nombre: "Absolute Tónico", precio: 35.5, pv: 22000 },
  { categoria: "Frumusețe", nombre: "Adelica Lip Color Glow", precio: 9.5, pv: 5250 },
  { categoria: "Frumusețe", nombre: "Adelica Volume Mascara Black", precio: 11.5, pv: 6250 },
  { categoria: "Frumusețe", nombre: "Adelica Waterproof Mascara", precio: 11.5, pv: 6250 },
  { categoria: "Frumusețe", nombre: "Atomy Absolute BB 211 Unidad", precio: 17.5, pv: 8000 },
  { categoria: "Frumusețe", nombre: "Atomy Absolute Complejo Cellactive para Ojos", precio: 40.5, pv: 26000 },
  { categoria: "Frumusețe", nombre: "Atomy Absolute Urban Shield Cushion Solar", precio: 15, pv: 9000 },
  { categoria: "Frumusețe", nombre: "Cuidado de Noche Set", precio: 37, pv: 14000 },
  { categoria: "Frumusețe", nombre: "Deep Cleanser", precio: 9.5, pv: 3500 },
  { categoria: "Frumusețe", nombre: "Derma Real Cica Gel Limpiador", precio: 13.5, pv: 8000 },
  { categoria: "Frumusețe", nombre: "Derma Real Cica Set", precio: 62.5, pv: 43000 },
  { categoria: "Frumusețe", nombre: "Foam Cleanser", precio: 9.5, pv: 3500 },
  { categoria: "Frumusețe", nombre: "Homme Cuidado de la Piel Set", precio: 55, pv: 35000 },
  { categoria: "Frumusețe", nombre: "Limpiador Multi-Acción Homme", precio: 12.5, pv: 5000 },
  { categoria: "Frumusețe", nombre: "Lip Glow", precio: 12, pv: 6000 },
  { categoria: "Frumusețe", nombre: "Marine Ampoule Eye Patch", precio: 19.5, pv: 10000 },
  { categoria: "Frumusețe", nombre: "Marine Ampoule Gel Mask", precio: 32, pv: 22000 },
  { categoria: "Frumusețe", nombre: "Mascarilla Diaria Especializada", precio: 12.5, pv: 5000 },
  { categoria: "Frumusețe", nombre: "Mascarilla Nocturna de Oro 24K", precio: 28, pv: 21000 },
  { categoria: "Frumusețe", nombre: "Mild Bubble Cleanser", precio: 10.5, pv: 5000 },
  { categoria: "Frumusețe", nombre: "Peel-Off Mask", precio: 9.5, pv: 3500 },
  { categoria: "Frumusețe", nombre: "Peeling Gel", precio: 9.5, pv: 3500 },
  { categoria: "Frumusețe", nombre: "Peeling Pad", precio: 12, pv: 7000 },
  { categoria: "Frumusețe", nombre: "Sistema Cuidado para la Piel The Fame", precio: 99.5, pv: 60000 },
  { categoria: "Frumusețe", nombre: "Synergy Ampoule *1 Set", precio: 90, pv: 72000 },
  { categoria: "Frumusețe", nombre: "Travel Cleansing Kit Set", precio: 17, pv: 3800 },
  { categoria: "Diverse", nombre: "Adelica Make-Up Brush Set + 2 Free Waterproof Mascara", precio: 35, pv: 27000 },
  { categoria: "Diverse", nombre: "Adelica Waterproof Mascara", precio: 11.5, pv: 6250 },
  { categoria: "Diverse", nombre: "Airopass Line Coffee (4-piece pouch)", precio: 6, pv: 0 },
  { categoria: "Diverse", nombre: "Atomy Acropass Line Lifter 5 Pouch", precio: 60, pv: 35000 },
  { categoria: "Diverse", nombre: "Atomy Business Book", precio: 10.5, pv: 0 },
  { categoria: "Diverse", nombre: "Atomy Medi-Cook 4SET (9pcs.)", precio: 550, pv: 280000 },
  { categoria: "Diverse", nombre: "Atomy T-shirt", precio: 15, pv: 0 },
  { categoria: "Diverse", nombre: "Atomy Thermal Tumbler", precio: 22, pv: 5000 },
  { categoria: "Diverse", nombre: "Best of Atomy Bundle", precio: 455, pv: 300000 },
  { categoria: "Diverse", nombre: "Detergente para Ropa en Láminas", precio: 11, pv: 6500 },
  { categoria: "Diverse", nombre: "MediCook Ceramic Set", precio: 155, pv: 100000 },
  { categoria: "Diverse", nombre: "Mino Knives Set of 2", precio: 150, pv: 70000 },
  { categoria: "Diverse", nombre: "New 2026Ver01 Leaflet (Bundle 20pieces)", precio: 5, pv: 0 },
  { categoria: "Diverse", nombre: "Sticker Bundle Set", precio: 25, pv: 0 },
  { categoria: "Diverse", nombre: "Summer Wellness Bundle", precio: 150, pv: 100000 },
  ],
  MX: [
  { categoria: "Îngrijire Personală", nombre: "Absolute Conditioner", precio: 360, pv: 8000 },
  { categoria: "Îngrijire Personală", nombre: "Absolute Shampoo", precio: 360, pv: 8000 },
  { categoria: "Îngrijire Personală", nombre: "Aceite Esencial para el Cabello *1pza", precio: 260, pv: 5200 },
  { categoria: "Îngrijire Personală", nombre: "Acondicionador Herbal para Cabello *1pza", precio: 280, pv: 5200 },
  { categoria: "Îngrijire Personală", nombre: "Aidam Limpiador 1pza", precio: 130, pv: 1800 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Absolute Feminine Wash", precio: 240, pv: 5500 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Cepillo Dental para Niños", precio: 200, pv: 4000 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Cepillo Dental Set (6pza)", precio: 200, pv: 5000 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Enjuague Bucal", precio: 190, pv: 4000 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Hand Cream", precio: 295, pv: 7000 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Protein Intensive Hair Care Set", precio: 800, pv: 21700 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Salón & Color Castaño 5G", precio: 240, pv: 5000 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Salón & Color Castaño Obscuro 6G", precio: 240, pv: 5000 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Salón & Color Negro 7G", precio: 240, pv: 5000 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Sculpture Conditioner", precio: 330, pv: 5720 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Sculpture Shampoo", precio: 330, pv: 5720 },
  { categoria: "Îngrijire Personală", nombre: "Curling Essence", precio: 195, pv: 5400 },
  { categoria: "Îngrijire Personală", nombre: "Green Propolis Spray", precio: 460, pv: 9500 },
  { categoria: "Îngrijire Personală", nombre: "Homme All-in-One Wash", precio: 370, pv: 7000 },
  { categoria: "Îngrijire Personală", nombre: "Homme Multi-Action Cleanser", precio: 250, pv: 4800 },
  { categoria: "Îngrijire Personală", nombre: "Jabón para Manos *1pza", precio: 80, pv: 1000 },
  { categoria: "Îngrijire Personală", nombre: "Limpiador Herbal para Cuerpo *1pza", precio: 210, pv: 3200 },
  { categoria: "Îngrijire Personală", nombre: "Loción para el Cuerpo 1pza", precio: 220, pv: 3200 },
  { categoria: "Îngrijire Personală", nombre: "Pasta dental 200g *1set", precio: 370, pv: 3250 },
  { categoria: "Îngrijire Personală", nombre: "Pasta dental 50g *1set", precio: 120, pv: 3000 },
  { categoria: "Îngrijire Personală", nombre: "Pasta Dental para Encías y Dientes Sensibles", precio: 230, pv: 5500 },
  { categoria: "Îngrijire Personală", nombre: "Shampoo Herbal para Cabello *1pza", precio: 280, pv: 5200 },
  { categoria: "Îngrijire Personală", nombre: "Sistema de Cuidado Bucal *1set", precio: 300, pv: 6250 },
  { categoria: "Îngrijire Personală", nombre: "Terapia para Manos (4pzas) 1kit", precio: 330, pv: 6000 },
  { categoria: "Îngrijire Personală", nombre: "Tratamiento Herbal para Cabello *1pza", precio: 170, pv: 2900 },
  { categoria: "Îngrijire Personală", nombre: "Tratamiento Líquido para Cabello *1pza", precio: 300, pv: 5200 },
  { categoria: "Casă", nombre: "Atomy Fabric Detergent", precio: 300, pv: 3600 },
  { categoria: "Casă", nombre: "Atomy Mexico MediCook Set", precio: 16000, pv: 300000 },
  { categoria: "Casă", nombre: "Atomy Scratch Free Scrubber", precio: 100, pv: 1500 },
  { categoria: "Casă", nombre: "Detergente Lavatrastes *1pza", precio: 170, pv: 3100 },
  { categoria: "Casă", nombre: "Detergente Multisuperficies para Baño", precio: 280, pv: 6000 },
  { categoria: "Casă", nombre: "Detergente Multisuperficies para Cocina", precio: 280, pv: 6000 },
  { categoria: "Casă", nombre: "Detergente para Ropa 1pza", precio: 280, pv: 4400 },
  { categoria: "Casă", nombre: "Fibra de Acero Inoxidable", precio: 70, pv: 1100 },
  { categoria: "Casă", nombre: "Guantes de Látex (M)", precio: 130, pv: 2000 },
  { categoria: "Casă", nombre: "MediCook 32cm Wok", precio: 5700, pv: 100000 },
  { categoria: "Casă", nombre: "MediCook Olla 1.8 L", precio: 3200, pv: 56000 },
  { categoria: "Casă", nombre: "MediCook Olla 5.5 L", precio: 5200, pv: 91000 },
  { categoria: "Casă", nombre: "MediCook Sartén 22 cm", precio: 2400, pv: 42000 },
  { categoria: "Casă", nombre: "O2 Bubble Power", precio: 220, pv: 5000 },
  { categoria: "Casă", nombre: "Suavizante de Telas 1pza", precio: 240, pv: 3400 },
  { categoria: "Alimente", nombre: "Atomy Café Arábica 0 Azúcar 50T", precio: 520, pv: 4000 },
  { categoria: "Alimente", nombre: "Atomy Potato Ramen", precio: 210, pv: 1300 },
  { categoria: "Alimente", nombre: "Café Arábica 50T", precio: 350, pv: 3000 },
  { categoria: "Alimente", nombre: "Probiotics", precio: 750, pv: 16000 },
  { categoria: "Sănătate", nombre: "Alaska E-Omega 3 *1pza", precio: 470, pv: 8300 },
  { categoria: "Sănătate", nombre: "Applephenon Jelly Stick", precio: 560, pv: 15000 },
  { categoria: "Sănătate", nombre: "Atomy Bitter Melon", precio: 790, pv: 22000 },
  { categoria: "Sănătate", nombre: "Atomy Color B", precio: 460, pv: 9000 },
  { categoria: "Sănătate", nombre: "Atomy Color C *1set", precio: 440, pv: 7800 },
  { categoria: "Sănătate", nombre: "Atomy Finezyme", precio: 350, pv: 9000 },
  { categoria: "Sănătate", nombre: "Atomy Greencera F", precio: 720, pv: 20000 },
  { categoria: "Sănătate", nombre: "Atomy Inner Collagen Powder", precio: 770, pv: 22000 },
  { categoria: "Sănătate", nombre: "Atomy Kids Vegan Gummy Multivitamin", precio: 420, pv: 11000 },
  { categoria: "Sănătate", nombre: "Atomy Luxanthin", precio: 950, pv: 28000 },
  { categoria: "Sănătate", nombre: "Atomy Pro Packed-Tamin", precio: 600, pv: 18000 },
  { categoria: "Sănătate", nombre: "Atomy Pure Spirulina 100%", precio: 540, pv: 9100 },
  { categoria: "Sănătate", nombre: "Atomy Rhubarb Queen", precio: 580, pv: 16000 },
  { categoria: "Sănătate", nombre: "Atomy Tea", precio: 660, pv: 13000 },
  { categoria: "Sănătate", nombre: "Atomy Tri-Active Calcium", precio: 490, pv: 13000 },
  { categoria: "Sănătate", nombre: "Atomy TURMACIN MSM", precio: 900, pv: 21000 },
  { categoria: "Sănătate", nombre: "Combo 5+1 Noni Challenge", precio: 6000, pv: 170000 },
  { categoria: "Sănătate", nombre: "Combo Pequeños Impulsos", precio: 840, pv: 22000 },
  { categoria: "Sănătate", nombre: "Organic Fermented Noni Concentrate (Bottle)", precio: 1200, pv: 34000 },
  { categoria: "Sănătate", nombre: "Organic Noni Concentrate (Pouch)", precio: 1200, pv: 34000 },
  { categoria: "Sănătate", nombre: "Rhodiola Milk Thistle", precio: 750, pv: 15000 },
  { categoria: "Him", nombre: "Him 4 Set PV's Up", precio: 8140, pv: 250000 },
  { categoria: "Him", nombre: "Him PV's Up", precio: 2150, pv: 65000 },
  { categoria: "Frumusețe", nombre: "4 Pasos PV's Up", precio: 830, pv: 16000 },
  { categoria: "Frumusețe", nombre: "Absolute 24K Gold Night Mask", precio: 730, pv: 19000 },
  { categoria: "Frumusețe", nombre: "Absolute Ampolla", precio: 1020, pv: 26000 },
  { categoria: "Frumusețe", nombre: "Absolute Contorno de Ojos", precio: 940, pv: 23400 },
  { categoria: "Frumusețe", nombre: "Absolute Crema Nutritiva", precio: 850, pv: 20800 },
  { categoria: "Frumusețe", nombre: "Absolute Hydra Balm", precio: 280, pv: 8000 },
  { categoria: "Frumusețe", nombre: "Absolute Loción", precio: 850, pv: 20800 },
  { categoria: "Frumusețe", nombre: "Absolute Oil Serum Mist", precio: 370, pv: 9000 },
  { categoria: "Frumusețe", nombre: "Absolute PV's Up", precio: 5060, pv: 170000 },
  { categoria: "Frumusețe", nombre: "Absolute Suero", precio: 940, pv: 23400 },
  { categoria: "Frumusețe", nombre: "Absoluto Tónico Facial", precio: 850, pv: 20800 },
  { categoria: "Frumusețe", nombre: "Adelica Lip Rouge Matt M01 True Red", precio: 290, pv: 9000 },
  { categoria: "Frumusețe", nombre: "Adelica Lip Rouge Matt M02 Neutral Pink", precio: 290, pv: 9000 },
  { categoria: "Frumusețe", nombre: "Adelica Lip Rouge Matt M03 Rose Flare", precio: 290, pv: 9000 },
  { categoria: "Frumusețe", nombre: "Adelica Lip Rouge Satin 02 Sweet Pink", precio: 290, pv: 9000 },
  { categoria: "Frumusețe", nombre: "Adelica Lip Rouge Satin 03 Raspberry", precio: 290, pv: 9000 },
  { categoria: "Frumusețe", nombre: "Adelica The New Gold Collagen Ampoule Cushion 02", precio: 590, pv: 16000 },
  { categoria: "Frumusețe", nombre: "Adelica The New Gold Collagen Ampoule Cushion 03", precio: 590, pv: 16000 },
  { categoria: "Frumusețe", nombre: "Adelica The New Gold Collagen Ampoule Cushion 04", precio: 590, pv: 16000 },
  { categoria: "Frumusețe", nombre: "Atomy Absolute BB 21*1EA", precio: 360, pv: 10000 },
  { categoria: "Frumusețe", nombre: "Atomy Absolute BB 23*1EA", precio: 360, pv: 10000 },
  { categoria: "Frumusețe", nombre: "Atomy Absolute Essence Sunscreen", precio: 250, pv: 5100 },
  { categoria: "Frumusețe", nombre: "Atomy Absolute Snow Dark Spot Corrector", precio: 340, pv: 9000 },
  { categoria: "Frumusețe", nombre: "Atomy Absolute Snow Day Cream", precio: 540, pv: 14000 },
  { categoria: "Frumusețe", nombre: "Atomy Absolute Snow Night Cream", precio: 640, pv: 17000 },
  { categoria: "Frumusețe", nombre: "Atomy Absolute Snow Serum", precio: 750, pv: 20000 },
  { categoria: "Frumusețe", nombre: "Atomy Absolute Snow Set", precio: 2900, pv: 90000 },
  { categoria: "Frumusețe", nombre: "Atomy Absolute Snow Tone-Up Essence Sun", precio: 280, pv: 7500 },
  { categoria: "Frumusețe", nombre: "Atomy Absolute Snow Toner", precio: 550, pv: 15000 },
  { categoria: "Frumusețe", nombre: "Atomy ACNE Clear Expert System", precio: 1520, pv: 40200 },
  { categoria: "Frumusețe", nombre: "Atomy Adelica Delineador de Cejas - Café Claro", precio: 170, pv: 4200 },
  { categoria: "Frumusețe", nombre: "Atomy Adelica Delineador de Cejas - Café Obscuro", precio: 170, pv: 4200 },
  { categoria: "Frumusețe", nombre: "Atomy Adelica Mascara para Pestañas a Prueba de Agua", precio: 280, pv: 6800 },
  { categoria: "Frumusețe", nombre: "Atomy Brush Pen Eyeliner (Black)", precio: 230, pv: 3600 },
  { categoria: "Frumusețe", nombre: "Atomy Fresh Sun Lotion", precio: 480, pv: 9500 },
  { categoria: "Frumusețe", nombre: "Atomy Homme Skincare Set", precio: 1200, pv: 29000 },
  { categoria: "Frumusețe", nombre: "Atomy Hydra Brightening Care Set", precio: 1000, pv: 27000 },
  { categoria: "Frumusețe", nombre: "Atomy Lip & Eye Remover", precio: 220, pv: 5000 },
  { categoria: "Frumusețe", nombre: "Atomy Marine Ampoule Eye Patch", precio: 400, pv: 10000 },
  { categoria: "Frumusețe", nombre: "Atomy Mascara para Pestañas - Volumen/Negro", precio: 280, pv: 6800 },
  { categoria: "Frumusețe", nombre: "Atomy Peeling Pad", precio: 250, pv: 6000 },
  { categoria: "Frumusețe", nombre: "Atomy Rose Rain Mist", precio: 270, pv: 5500 },
  { categoria: "Frumusețe", nombre: "Atomy Sun Stick", precio: 240, pv: 4500 },
  { categoria: "Frumusețe", nombre: "Atomy Synergy Ampoule Program", precio: 2600, pv: 68000 },
  { categoria: "Frumusețe", nombre: "Bálsamo Labial *1pza", precio: 110, pv: 2000 },
  { categoria: "Frumusețe", nombre: "Brillo Labial *1pza", precio: 290, pv: 5300 },
  { categoria: "Frumusețe", nombre: "Crema BB 1pza", precio: 200, pv: 2500 },
  { categoria: "Frumusețe", nombre: "Daily Expert Mask Brightening", precio: 265, pv: 4500 },
  { categoria: "Frumusețe", nombre: "Daily Expert Mask Firming", precio: 265, pv: 4500 },
  { categoria: "Frumusețe", nombre: "Daily Expert Mask Moisture", precio: 265, pv: 4500 },
  { categoria: "Frumusețe", nombre: "Deep Pure Cleansing Oil", precio: 420, pv: 7500 },
  { categoria: "Frumusețe", nombre: "Derma Calming Sun Stick", precio: 240, pv: 5100 },
  { categoria: "Frumusețe", nombre: "Derma Real Cica Gel Cleanser", precio: 260, pv: 8000 },
  { categoria: "Frumusețe", nombre: "Espuma Limpiadora 1pza", precio: 210, pv: 3250 },
  { categoria: "Frumusețe", nombre: "Gel Exfoliante 1pza", precio: 210, pv: 3250 },
  { categoria: "Frumusețe", nombre: "Homme All-in-One Wash", precio: 370, pv: 7000 },
  { categoria: "Frumusețe", nombre: "Homme Multi-Action Cleanser", precio: 250, pv: 4800 },
  { categoria: "Frumusețe", nombre: "Limpiador Profundo 1pza", precio: 210, pv: 3250 },
  { categoria: "Frumusețe", nombre: "Limpieza Profunda Kit de Viaje (6pzas) 1kit", precio: 350, pv: 5000 },
  { categoria: "Frumusețe", nombre: "Mascarilla en Gel - 7 Soluciones 1kit", precio: 720, pv: 13000 },
  { categoria: "Frumusețe", nombre: "Mascarilla Peel-Off 1pza", precio: 210, pv: 3250 },
  { categoria: "Frumusețe", nombre: "Protector Solar Beige 1pza", precio: 200, pv: 3250 },
  { categoria: "Frumusețe", nombre: "Protector Solar Blanco 1pza", precio: 200, pv: 3250 },
  { categoria: "Frumusețe", nombre: "Sistema Cuidado para la Piel The Fame", precio: 2370, pv: 57200 },
  { categoria: "Frumusețe", nombre: "The Fame Crema Esencia", precio: 530, pv: 12500 },
  { categoria: "Frumusețe", nombre: "The Fame Crema Nutritiva", precio: 500, pv: 11700 },
  { categoria: "Frumusețe", nombre: "The Fame Crema para Ojos", precio: 500, pv: 11700 },
  { categoria: "Frumusețe", nombre: "The Fame Loción", precio: 500, pv: 11700 },
  { categoria: "Frumusețe", nombre: "The Fame Tónico", precio: 500, pv: 11700 },
  { categoria: "Diverse", nombre: "Bolsa de Plástico 1pza", precio: 15, pv: 0 },
  { categoria: "Diverse", nombre: "Bolsa Laminada (S) 1pza", precio: 10, pv: 0 },
  { categoria: "Diverse", nombre: "Folleto de productos *1set (20pzas)", precio: 190, pv: 0 },
  ],
  BR: [
  { categoria: "Îngrijire Personală", nombre: "Atomy Absolute Feminine Wash 160mL", precio: 134, pv: 13000 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Absolute Hair Conditioner 500mL", precio: 145, pv: 14000 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Absolute Hair Shampoo 500mL", precio: 127, pv: 12000 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Absolute Haircare Set", precio: 346, pv: 36000 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Body Lotion 300mL", precio: 108, pv: 9000 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Cerakidz Cream 100mL", precio: 143, pv: 14000 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Cerakidz Lotion 200mL", precio: 168, pv: 16000 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Hair Essential Oil 100mL", precio: 135, pv: 14000 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Hand Balm Butter 50ml", precio: 59, pv: 6000 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Hand Balm Pure 50ml", precio: 59, pv: 6000 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Hand Soap 300mL", precio: 40, pv: 2500 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Herbal Body Cleanser 500mL", precio: 90, pv: 8000 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Herbal Conditioner 500mL", precio: 107, pv: 11000 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Herbal Hair Treatment 200mL", precio: 67, pv: 7000 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Herbal Shampoo 500mL", precio: 105, pv: 11000 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Homme All-in-One Wash 500mL", precio: 152, pv: 17000 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Kids Toothbrush (8 unidades)", precio: 80, pv: 7500 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Oral Care System", precio: 120, pv: 15000 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Protein Hair Repair Set", precio: 345, pv: 35000 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Protein Intensive Shampoo", precio: 198, pv: 20000 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Protein Intensive Treatment", precio: 158, pv: 16000 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Scalpcare Conditioner 500ml", precio: 125, pv: 12000 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Scalpcare Set", precio: 220, pv: 25000 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Scalpcare Shampoo 500ml", precio: 110, pv: 12000 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Sensitive Toothpaste Set", precio: 118, pv: 15000 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Toothbrush (8 unidades)", precio: 80, pv: 11000 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Toothpaste 4X50g", precio: 48, pv: 2200 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Toothpaste 5X200g", precio: 155, pv: 8000 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Travel Cleansing Kit", precio: 159, pv: 10000 },
  { categoria: "Îngrijire Personală", nombre: "Atomy Ultra Rich Body Cream 200mL", precio: 130, pv: 11500 },
  { categoria: "Casă", nombre: "Atomy Sheet Laundry Detergent (30 folhas)", precio: 116, pv: 8000 },
  { categoria: "Alimente", nombre: "Atomy Alaska E-Omega 3", precio: 176, pv: 17000 },
  { categoria: "Alimente", nombre: "Atomy Café Arábica Black", precio: 152, pv: 6000 },
  { categoria: "Alimente", nombre: "Atomy Café Arábica T50", precio: 72, pv: 3200 },
  { categoria: "Alimente", nombre: "Atomy Puer Tea", precio: 199, pv: 24000 },
  { categoria: "Alimente", nombre: "Atomy Vitamin C", precio: 162, pv: 17000 },
  { categoria: "Frumusețe", nombre: "Atomy Absolute Ampoule Total", precio: 310, pv: 45000 },
  { categoria: "Frumusețe", nombre: "Atomy Absolute CellActive Nutrition", precio: 1540, pv: 130000 },
  { categoria: "Frumusețe", nombre: "Atomy Absolute Evening Foam Balm", precio: 130, pv: 7000 },
  { categoria: "Frumusețe", nombre: "Atomy Absolute Gel Serum Mist", precio: 179, pv: 17000 },
  { categoria: "Frumusețe", nombre: "Atomy Absolute HTA Complex", precio: 249, pv: 30000 },
  { categoria: "Frumusețe", nombre: "Atomy Absolute Lotion", precio: 239, pv: 30000 },
  { categoria: "Frumusețe", nombre: "Atomy Absolute Skincare Set", precio: 1540, pv: 130000 },
  { categoria: "Frumusețe", nombre: "Atomy Absolute Snow Dark Spot Corrector", precio: 162, pv: 27000 },
  { categoria: "Frumusețe", nombre: "Atomy Absolute Snow Lotion", precio: 1250, pv: 170000 },
  { categoria: "Frumusețe", nombre: "Atomy Absolute Toner", precio: 269, pv: 30000 },
  { categoria: "Frumusețe", nombre: "Atomy Ceramide Cream", precio: 143, pv: 15000 },
  { categoria: "Frumusețe", nombre: "Atomy Daily Expert Mask Brightening", precio: 106, pv: 15000 },
  { categoria: "Frumusețe", nombre: "Atomy Daily Expert Mask Firming", precio: 106, pv: 15000 },
  { categoria: "Frumusețe", nombre: "Atomy Daily Expert Mask Moisturizing", precio: 159, pv: 7000 },
  { categoria: "Frumusețe", nombre: "Atomy Deep Pure Cleansing Toner", precio: 159, pv: 7000 },
  { categoria: "Frumusețe", nombre: "Atomy Evening Care Deep Cleanser", precio: 79, pv: 7000 },
  { categoria: "Frumusețe", nombre: "Atomy Evening Care Foam Cleanser", precio: 79, pv: 7000 },
  { categoria: "Frumusețe", nombre: "Atomy Evening Care Peeling Gel", precio: 239, pv: 30000 },
  { categoria: "Frumusețe", nombre: "Atomy Evening Care Set", precio: 310, pv: 35000 },
  { categoria: "Frumusețe", nombre: "Atomy Homme All-in-One", precio: 178, pv: 15000 },
  { categoria: "Frumusețe", nombre: "Atomy Homme Essence", precio: 144, pv: 15000 },
  { categoria: "Frumusețe", nombre: "Atomy Homme Lotion", precio: 169, pv: 21000 },
  { categoria: "Frumusețe", nombre: "Atomy Homme Multi-Action Moisturizing", precio: 99, pv: 15000 },
  { categoria: "Frumusețe", nombre: "Atomy Homme Nutrition Cream", precio: 169, pv: 21000 },
  { categoria: "Frumusețe", nombre: "Atomy Lip Gel Balm", precio: 104, pv: 5300 },
  { categoria: "Frumusețe", nombre: "Atomy Lip Treatment", precio: 51, pv: 7000 },
  { categoria: "Frumusețe", nombre: "Atomy Lotion", precio: 124, pv: 15000 },
  { categoria: "Frumusețe", nombre: "Atomy Mineral Sunscreen", precio: 76, pv: 11500 },
  { categoria: "Frumusețe", nombre: "Atomy The Fame Absolute Serum", precio: 169, pv: 27000 },
  { categoria: "Frumusețe", nombre: "Atomy The Fame Nutrition Cream", precio: 169, pv: 21000 },
  { categoria: "Frumusețe", nombre: "Atomy The Fame Toner", precio: 124, pv: 27000 },
  { categoria: "Frumusețe", nombre: "Atomy Ultra Rich Body Cream", precio: 130, pv: 15000 },
  { categoria: "Promoții", nombre: "Atomy Maestria 300K PV", precio: 2155, pv: 300000 },
  { categoria: "Diverse", nombre: "Atomy Catálogo Produtos 20 Unidades", precio: 40, pv: 0 },
  { categoria: "Diverse", nombre: "Atomy Cenário de Vida", precio: 15, pv: 0 },
  ],
  CA: [
  { categoria: "Îngrijire Personală", nombre: "Absolute Conditioner (500ml)", precio: 24, pv: 8000 },
  { categoria: "Îngrijire Personală", nombre: "Absolute Feminine Wash (160ml)", precio: 16, pv: 5500 },
  { categoria: "Îngrijire Personală", nombre: "Absolute Homme Wash (400ml)", precio: 16, pv: 6300 },
  { categoria: "Îngrijire Personală", nombre: "Absolute Shampoo (500ml)", precio: 24, pv: 8000 },
  { categoria: "Îngrijire Personală", nombre: "Aidam Cleanser (200ml)", precio: 8, pv: 2000 },
  { categoria: "Îngrijire Personală", nombre: "Body Lotion (300ml)", precio: 12, pv: 3200 },
  { categoria: "Îngrijire Personală", nombre: "Hair Essential Oil (100ml)", precio: 18, pv: 5500 },
  { categoria: "Îngrijire Personală", nombre: "Hand Cream (300ml)", precio: 18, pv: 7000 },
  { categoria: "Îngrijire Personală", nombre: "Hand Lotion (400ml)", precio: 18, pv: 7000 },
  { categoria: "Îngrijire Personală", nombre: "Hand Soap (300ml)", precio: 4.5, pv: 1000 },
  { categoria: "Îngrijire Personală", nombre: "Hand Therapy 4 Kit (30ml x4 Tubes)", precio: 20, pv: 7000 },
  { categoria: "Îngrijire Personală", nombre: "Herbal Body Cleanser (500ml)", precio: 13, pv: 4000 },
  { categoria: "Îngrijire Personală", nombre: "Herbal Hair Conditioner (500ml)", precio: 17, pv: 6000 },
  { categoria: "Îngrijire Personală", nombre: "Herbal Hair Shampoo (500ml)", precio: 17, pv: 6000 },
  { categoria: "Îngrijire Personală", nombre: "Herbday (Large) (10 Pads x4 Packs)", precio: 19, pv: 4500 },
  { categoria: "Îngrijire Personală", nombre: "Herbday (Medium) (10 Pads x4 Packs)", precio: 18, pv: 4000 },
  { categoria: "Îngrijire Personală", nombre: "Herbday (Panty Liner) (20 Pads x4 Packs)", precio: 18, pv: 4000 },
  { categoria: "Îngrijire Personală", nombre: "Kids Toothbrush (8 Brushes)", precio: 13, pv: 4500 },
  { categoria: "Îngrijire Personală", nombre: "Oral Care System (4 Sets)", precio: 19, pv: 7000 },
  { categoria: "Îngrijire Personală", nombre: "Root Vital Hair Care Set", precio: 75, pv: 32000 },
  { categoria: "Îngrijire Personală", nombre: "Root Vital Hair Shampoo (500ml)", precio: 28, pv: 9500 },
  { categoria: "Îngrijire Personală", nombre: "Root Vital Scalp & Hair Pack (200ml)", precio: 24, pv: 8500 },
  { categoria: "Îngrijire Personală", nombre: "Root Vital Scalp Ampoule (15ml)", precio: 24, pv: 9000 },
  { categoria: "Îngrijire Personală", nombre: "Saengmodan Hair Tonic (200ml)", precio: 18, pv: 6000 },
  { categoria: "Îngrijire Personală", nombre: "Scalpcare Conditioner (500ml)", precio: 19, pv: 5720 },
  { categoria: "Îngrijire Personală", nombre: "Scalpcare Shampoo (500ml)", precio: 19, pv: 5720 },
  { categoria: "Îngrijire Personală", nombre: "Sensitive Teeth and Gums Toothpaste (100g x3 Tubes)", precio: 16, pv: 5500 },
  { categoria: "Îngrijire Personală", nombre: "Toothbrush (8 Brushes)", precio: 13, pv: 5500 },
  { categoria: "Îngrijire Personală", nombre: "Toothpaste (200g x 5 Tubes)", precio: 25, pv: 4000 },
  { categoria: "Îngrijire Personală", nombre: "Toothpaste (50g x4 Tubes)", precio: 9, pv: 3000 },
  { categoria: "Casă", nombre: "(L) Eco Zipper Bag (22 Bags)", precio: 3.5, pv: 520 },
  { categoria: "Casă", nombre: "(S) Eco Zipper Bag (22 Bags)", precio: 3, pv: 455 },
  { categoria: "Casă", nombre: "Dishwasher Tablet 12 (14g x60 Tablets)", precio: 25, pv: 7500 },
  { categoria: "Casă", nombre: "Eco Glove (120 Pieces)", precio: 5, pv: 1000 },
  { categoria: "Casă", nombre: "Hand Soap (400ml)", precio: 4.5, pv: 1000 },
  { categoria: "Casă", nombre: "Latex Gloves (M 2 Set)", precio: 6.5, pv: 1300 },
  { categoria: "Casă", nombre: "Laundry Detergent Pods (7.25g x100 Pods)", precio: 30, pv: 9000 },
  { categoria: "Casă", nombre: "Liquid Detergent (67.43 FL Oz)", precio: 18, pv: 4400 },
  { categoria: "Casă", nombre: "MediCook 5.4L Wok", precio: 270, pv: 110000 },
  { categoria: "Casă", nombre: "Scratch Free Scrubber (4 Packs)", precio: 6, pv: 1500 },
  { categoria: "Casă", nombre: "Sheet Laundry Detergent (30 Sheets)", precio: 16, pv: 5000 },
  { categoria: "Casă", nombre: "Stainless Scrubber (2 Packs)", precio: 5, pv: 750 },
  { categoria: "Casă", nombre: "Tape Cleaner (1 Roller + 3 Refills)", precio: 22, pv: 4500 },
  { categoria: "Casă", nombre: "Tape Cleaner Refill (3 Refills)", precio: 15, pv: 3000 },
  { categoria: "Alimente", nombre: "(36-Pack) Olive Oil Grilled Laver (5g x36 Packs)", precio: 28, pv: 3200 },
  { categoria: "Alimente", nombre: "[4 Set] Organic Coconut Sugar (250g x4)", precio: 30, pv: 7500 },
  { categoria: "Alimente", nombre: "[4 Sets] Fermented Noni Concentrate (38ml x24 Pouches)", precio: 320, pv: 130000 },
  { categoria: "Alimente", nombre: "[5+1 CHALLENGE] Fermented Noni Concentrate (947ml x6 Bottles)", precio: 400, pv: 160000 },
  { categoria: "Alimente", nombre: "Apple Jelly Stick (15g x28 Sachets)", precio: 40, pv: 18000 },
  { categoria: "Alimente", nombre: "Cafe Arabica (12.1g x50 Packets)", precio: 18, pv: 1800 },
  { categoria: "Alimente", nombre: "Cafe Arabica Black (1.6g x80 Packets)", precio: 20, pv: 3900 },
  { categoria: "Alimente", nombre: "Cafe Arabica Zero Sugar 100T", precio: 47, pv: 5000 },
  { categoria: "Alimente", nombre: "Fermented Noni Concentrate (38ml x24 Pouches)", precio: 85, pv: 35000 },
  { categoria: "Alimente", nombre: "Fermented Noni Concentrate (947ml x1 Bottle)", precio: 80, pv: 32000 },
  { categoria: "Alimente", nombre: "Organic Coconut Sugar (250g)", precio: 9, pv: 2200 },
  { categoria: "Alimente", nombre: "Potato Ramen (114g x4 packs)", precio: 9, pv: 1000 },
  { categoria: "Alimente", nombre: "Potato Ramen Mild (113g x4 packs)", precio: 9, pv: 1000 },
  { categoria: "Alimente", nombre: "Potato Spicy Cold Noodles (4 packs)", precio: 9, pv: 1000 },
  { categoria: "Alimente", nombre: "Puer Tea (1g x30 Sachets)", precio: 40, pv: 14000 },
  { categoria: "Alimente", nombre: "Triple Up Protein (25g x30 Sachets)", precio: 69, pv: 26000 },
  { categoria: "Sănătate", nombre: "100% Pure Spirulina (120 Tablets)", precio: 30, pv: 12000 },
  { categoria: "Sănătate", nombre: "[1 Set] Mordant Collagen (x10 Bottles per set)", precio: 112, pv: 112000 },
  { categoria: "Sănătate", nombre: "[4 Set] Bitter Melon Capsule (60 Capsules x4)", precio: 352, pv: 150000 },
  { categoria: "Sănătate", nombre: "Bitter Melon Capsule (60 Capsules)", precio: 99, pv: 30000 },
  { categoria: "Sănătate", nombre: "Derma Calming Sun Stick (19g)", precio: 16, pv: 6500 },
  { categoria: "Sănătate", nombre: "Eye Lutein (90 Softgels)", precio: 43, pv: 51000 },
  { categoria: "Sănătate", nombre: "Kbeka Omega 3 (180 Softgels)", precio: 29, pv: 20000 },
  { categoria: "Sănătate", nombre: "Mineral Gel Patch (65 Patches)", precio: 48, pv: 53000 },
  { categoria: "Sănătate", nombre: "Mineral Sunscreen (Tube)", precio: 22, pv: 6000 },
  { categoria: "Sănătate", nombre: "Mordant Collagen (30 Sachets)", precio: 30, pv: 12000 },
  { categoria: "Sănătate", nombre: "Pomegranate Beauty (10g x30 Sachets)", precio: 93, pv: 30000 },
  { categoria: "Sănătate", nombre: "Probiotics 10 Plus (2g x60 Sachets)", precio: 43, pv: 58000 },
  { categoria: "Sănătate", nombre: "Psyllium Husk (5g x30 Sachets)", precio: 38, pv: 16000 },
  { categoria: "Sănătate", nombre: "Pure Tea (10g x40 Sachets)", precio: 40, pv: 16000 },
  { categoria: "Sănătate", nombre: "Rhodiola Milk Thistle (600mg x90 Tablets)", precio: 33, pv: 12000 },
  { categoria: "Sănătate", nombre: "Vital Mega Vitamin C 2000 (2g x90 Sachets)", precio: 45, pv: 21000 },
  { categoria: "Sănătate", nombre: "Vitamin C (2g x90 Sachets)", precio: 27, pv: 15000 },
  { categoria: "HemoHIM", nombre: "[4 Sets] HemoHIM (30 Sachets per Set)", precio: 440, pv: 300000 },
  { categoria: "HemoHIM", nombre: "[4 Sets] HemoHIM (60 Sachets per Set)", precio: 500, pv: 240000 },
  { categoria: "HemoHIM", nombre: "HemoHIM (30 Sachets)", precio: 106, pv: 70000 },
  { categoria: "HemoHIM", nombre: "HemoHIM (60 Sachets)", precio: 130, pv: 60000 },
  { categoria: "Frumusețe", nombre: "Absolute Ampoule (40ml)", precio: 59, pv: 29000 },
  { categoria: "Frumusețe", nombre: "Absolute Eye-Complex (40ml)", precio: 55, pv: 26000 },
  { categoria: "Frumusețe", nombre: "Absolute Lotion (135ml)", precio: 50, pv: 23000 },
  { categoria: "Frumusețe", nombre: "Absolute Nutrition Cream (50ml)", precio: 50, pv: 23000 },
  { categoria: "Frumusețe", nombre: "Absolute Oil Serum Mist (80ml)", precio: 27, pv: 13000 },
  { categoria: "Frumusețe", nombre: "Absolute Serum (50ml)", precio: 55, pv: 26000 },
  { categoria: "Frumusețe", nombre: "Absolute Skincare Set (6 Pieces)", precio: 305, pv: 150000 },
  { categoria: "Frumusețe", nombre: "Absolute Toner (150ml)", precio: 50, pv: 23000 },
  { categoria: "Frumusețe", nombre: "Adelica Soft Brow Pencil (0.3g Brown)", precio: 11, pv: 4000 },
  { categoria: "Frumusețe", nombre: "BB Cream (40ml)", precio: 15, pv: 4000 },
  { categoria: "Frumusețe", nombre: "Cleansing Essential Mini Kit (6pcs)", precio: 15, pv: 3500 },
  { categoria: "Frumusețe", nombre: "Daily Expert Mask Brightening (10 Sheets)", precio: 16, pv: 4500 },
  { categoria: "Frumusețe", nombre: "Daily Expert Mask Firming (10 Sheets)", precio: 16, pv: 4500 },
  { categoria: "Frumusețe", nombre: "Daily Expert Mask Moisturizing (10 Sheets)", precio: 16, pv: 4500 },
  { categoria: "Frumusețe", nombre: "Deep Cleanser (150ml)", precio: 14, pv: 4000 },
  { categoria: "Frumusețe", nombre: "Deep Pure Cleansing Oil (150ml)", precio: 25, pv: 7500 },
  { categoria: "Frumusețe", nombre: "Derma Calming Sun Stick (16g)", precio: 16, pv: 5000 },
  { categoria: "Frumusețe", nombre: "Derma Real Cica Set (3 Pieces)", precio: 90, pv: 42000 },
  { categoria: "Frumusețe", nombre: "Evening Care 4 Set", precio: 50, pv: 16000 },
  { categoria: "Frumusețe", nombre: "Foam Cleanser (150ml)", precio: 14, pv: 4000 },
  { categoria: "Frumusețe", nombre: "Healthy Glow Base (33ml)", precio: 17, pv: 5000 },
  { categoria: "Frumusețe", nombre: "Homme Energizing All in One (80ml)", precio: 29, pv: 14000 },
  { categoria: "Frumusețe", nombre: "Lip Glow (3.3g)", precio: 14, pv: 5300 },
  { categoria: "Frumusețe", nombre: "Lip Treatment (3.9g)", precio: 7.5, pv: 2200 },
  { categoria: "Frumusețe", nombre: "Mineral Sunscreen (75ml)", precio: 22, pv: 8000 },
  { categoria: "Frumusețe", nombre: "Peel-Off Mask (120ml)", precio: 14, pv: 4000 },
  { categoria: "Frumusețe", nombre: "Peeling Gel (120ml)", precio: 14, pv: 4000 },
  { categoria: "Frumusețe", nombre: "Rose Rain Mist (130ml)", precio: 17, pv: 4800 },
  { categoria: "Frumusețe", nombre: "The Fame Essence (50ml)", precio: 31, pv: 14000 },
  { categoria: "Frumusețe", nombre: "The Fame Eye Cream (40ml)", precio: 29, pv: 13000 },
  { categoria: "Frumusețe", nombre: "The Fame Lotion (135ml)", precio: 29, pv: 13000 },
  { categoria: "Frumusețe", nombre: "The Fame Nutrition Cream (50ml)", precio: 29, pv: 13000 },
  { categoria: "Frumusețe", nombre: "The Fame Set (Individual Packaging)", precio: 138, pv: 66000 },
  { categoria: "Frumusețe", nombre: "The Fame Toner (150ml)", precio: 29, pv: 13000 },
  { categoria: "Diverse", nombre: "Best Kit", precio: 595, pv: 300000 },
  { categoria: "Diverse", nombre: "Essential Kit", precio: 235, pv: 100000 },
  { categoria: "Diverse", nombre: "Starter Kit", precio: 128, pv: 50000 },
  { categoria: "Diverse", nombre: "Tarpaulin Bag (1EA)", precio: 6, pv: 1500 },
  ],
  US: [
  { categoria: "Îngrijire Personală", nombre: "Absolute Conditioner - Step 3", precio: 21, pv: 10000 },
  { categoria: "Îngrijire Personală", nombre: "Absolute Hair Care Set", precio: 55, pv: 28000 },
  { categoria: "Îngrijire Personală", nombre: "Absolute Shampoo - Step 1", precio: 21, pv: 10000 },
  { categoria: "Îngrijire Personală", nombre: "Absolute Treatment - Step 2", precio: 15, pv: 6000 },
  { categoria: "Îngrijire Personală", nombre: "Aidam Cleanser", precio: 7, pv: 2500 },
  { categoria: "Îngrijire Personală", nombre: "Body Lotion", precio: 12.5, pv: 4500 },
  { categoria: "Îngrijire Personală", nombre: "Curling Essence", precio: 10, pv: 6500 },
  { categoria: "Îngrijire Personală", nombre: "Ethereal Patches", precio: 36, pv: 16000 },
  { categoria: "Îngrijire Personală", nombre: "Fluoride-Free Toothpaste", precio: 13, pv: 7000 },
  { categoria: "Îngrijire Personală", nombre: "Foot Nourishing Cream", precio: 17.5, pv: 10000 },
  { categoria: "Îngrijire Personală", nombre: "Foot Scrub Wash", precio: 16.5, pv: 9000 },
  { categoria: "Îngrijire Personală", nombre: "Hair & Body Set", precio: 50, pv: 25000 },
  { categoria: "Îngrijire Personală", nombre: "Hair Essential Oil", precio: 14, pv: 6500 },
  { categoria: "Îngrijire Personală", nombre: "Hand Cream", precio: 17, pv: 8000 },
  { categoria: "Îngrijire Personală", nombre: "Hand Lotion", precio: 17, pv: 6600 },
  { categoria: "Îngrijire Personală", nombre: "Hand Soap", precio: 6, pv: 2000 },
  { categoria: "Îngrijire Personală", nombre: "Hand Therapy", precio: 18.5, pv: 8500 },
  { categoria: "Îngrijire Personală", nombre: "Herb Day (Large)", precio: 17, pv: 5700 },
  { categoria: "Îngrijire Personală", nombre: "Herb Day (Liner)", precio: 16, pv: 5000 },
  { categoria: "Îngrijire Personală", nombre: "Herb Day (Medium)", precio: 16, pv: 5000 },
  { categoria: "Îngrijire Personală", nombre: "Herbal Body Cleanser", precio: 12, pv: 5000 },
  { categoria: "Îngrijire Personală", nombre: "Herbal Hair Conditioner", precio: 16, pv: 8000 },
  { categoria: "Îngrijire Personală", nombre: "Herbal Hair Shampoo", precio: 14, pv: 7000 },
  { categoria: "Îngrijire Personală", nombre: "Herbal Hair Treatment", precio: 9, pv: 4000 },
  { categoria: "Îngrijire Personală", nombre: "Homme All-in-One Wash", precio: 18, pv: 8000 },
  { categoria: "Îngrijire Personală", nombre: "Homme Multi-Action Cleanser", precio: 18, pv: 5000 },
  { categoria: "Îngrijire Personală", nombre: "Kids Toothbrush (8ea)", precio: 12, pv: 6000 },
  { categoria: "Îngrijire Personală", nombre: "Oral Care System", precio: 16, pv: 8000 },
  { categoria: "Îngrijire Personală", nombre: "Root Vital Hair Care Set", precio: 59, pv: 33000 },
  { categoria: "Îngrijire Personală", nombre: "Root Vital Hair Shampoo", precio: 23, pv: 10000 },
  { categoria: "Îngrijire Personală", nombre: "Root Vital Scalp Ampoule", precio: 20, pv: 9500 },
  { categoria: "Îngrijire Personală", nombre: "Root Vital Scalp Ampoule *3ea", precio: 55, pv: 30000 },
  { categoria: "Îngrijire Personală", nombre: "Saengmodan Hair Tonic", precio: 17, pv: 8000 },
  { categoria: "Îngrijire Personală", nombre: "Scalpcare Conditioner", precio: 16.5, pv: 6200 },
  { categoria: "Îngrijire Personală", nombre: "Scalpcare Hair Care Set", precio: 55, pv: 22500 },
  { categoria: "Îngrijire Personală", nombre: "Scalpcare Set", precio: 32, pv: 15000 },
  { categoria: "Îngrijire Personală", nombre: "Scalpcare Shampoo", precio: 16.5, pv: 7000 },
  { categoria: "Îngrijire Personală", nombre: "Silk Protein Hair Essence", precio: 18, pv: 8000 },
  { categoria: "Îngrijire Personală", nombre: "Sugar Body Scrub", precio: 20, pv: 11000 },
  { categoria: "Îngrijire Personală", nombre: "Toothbrush (8pk)", precio: 12, pv: 7000 },
  { categoria: "Îngrijire Personală", nombre: "Toothpaste", precio: 22, pv: 6000 },
  { categoria: "Îngrijire Personală", nombre: "Toothpaste 50g", precio: 6, pv: 4000 },
  { categoria: "Îngrijire Personală", nombre: "Ultra Rich Body Cream", precio: 16.5, pv: 7500 },
  { categoria: "Îngrijire Personală", nombre: "Ultra Rich Body Wash", precio: 14, pv: 6000 },
  { categoria: "Casă", nombre: "Dishwashing Liquid", precio: 12, pv: 5000 },
  { categoria: "Casă", nombre: "Fabric Detergent", precio: 17, pv: 5000 },
  { categoria: "Casă", nombre: "Fabric Softener", precio: 14, pv: 5000 },
  { categoria: "Casă", nombre: "Latex Gloves (L) *2 sets", precio: 8, pv: 3000 },
  { categoria: "Casă", nombre: "Latex Gloves (M) *2 sets", precio: 6, pv: 2000 },
  { categoria: "Casă", nombre: "Liquid Laundry Detergent", precio: 17, pv: 6000 },
  { categoria: "Casă", nombre: "MediCook 28cm Fry Pan", precio: 140, pv: 75000 },
  { categoria: "Casă", nombre: "MediCook 3.3L", precio: 200, pv: 110000 },
  { categoria: "Casă", nombre: "MediCook 5.4L Wok", precio: 260, pv: 140000 },
  { categoria: "Casă", nombre: "MediCook 5.5L", precio: 240, pv: 130000 },
  { categoria: "Casă", nombre: "O2 Bubble Power", precio: 14, pv: 6000 },
  { categoria: "Casă", nombre: "Scratch Free Scrubber", precio: 6.5, pv: 2000 },
  { categoria: "Casă", nombre: "Sheet Laundry Detergent", precio: 13, pv: 6000 },
  { categoria: "Alimente", nombre: "Avocado 100% Extra Virgin Avocado Oil", precio: 18, pv: 6000 },
  { categoria: "Alimente", nombre: "Cafe Arabica 50", precio: 12, pv: 4000 },
  { categoria: "Alimente", nombre: "Cafe Arabica 50T *16ea", precio: 192, pv: 64000 },
  { categoria: "Alimente", nombre: "Cafe Arabica Black", precio: 21, pv: 5500 },
  { categoria: "Alimente", nombre: "Cafe Arabica Zero Sugar 100T", precio: 39, pv: 5000 },
  { categoria: "Alimente", nombre: "Health Best Kit", precio: 150, pv: 100000 },
  { categoria: "Alimente", nombre: "Manuka Honey 830+", precio: 78, pv: 35000 },
  { categoria: "Alimente", nombre: "Olive Oil Grilled Laver", precio: 19, pv: 4000 },
  { categoria: "Alimente", nombre: "Olive Oil Grilled Laver (36 Packs)", precio: 20, pv: 3000 },
  { categoria: "Alimente", nombre: "Potato Ramen *4 pack", precio: 9, pv: 1300 },
  { categoria: "Alimente", nombre: "Puer Tea", precio: 35, pv: 16000 },
  { categoria: "Sănătate", nombre: "Applena Queen", precio: 39, pv: 15000 },
  { categoria: "Sănătate", nombre: "Applephenon Jelly Stick", precio: 32, pv: 15000 },
  { categoria: "Sănătate", nombre: "Bitter Melon", precio: 46, pv: 22000 },
  { categoria: "Sănătate", nombre: "Eye Health Luteanthin", precio: 45, pv: 28000 },
  { categoria: "Sănătate", nombre: "Eye Lutein", precio: 35, pv: 11000 },
  { categoria: "Sănătate", nombre: "Green Propolis Spray", precio: 26, pv: 11000 },
  { categoria: "Sănătate", nombre: "HemoHIM", precio: 105, pv: 66000 },
  { categoria: "Sănătate", nombre: "HemoHIM *4 Sets", precio: 405, pv: 300000 },
  { categoria: "Sănătate", nombre: "Insect Memory Up", precio: 40, pv: 21000 },
  { categoria: "Sănătate", nombre: "Iron", precio: 17, pv: 15000 },
  { categoria: "Sănătate", nombre: "ITG Omega 3", precio: 35, pv: 8900 },
  { categoria: "Sănătate", nombre: "Korean Red Ginseng Jelly Stick", precio: 47, pv: 27000 },
  { categoria: "Sănătate", nombre: "Mangosteen", precio: 95, pv: 34000 },
  { categoria: "Sănătate", nombre: "Organic Fermented Noni Concentrate (Bottle)", precio: 57, pv: 34000 },
  { categoria: "Sănătate", nombre: "Organic Fermented Noni Concentrate (Pouch)", precio: 62, pv: 34000 },
  { categoria: "Sănătate", nombre: "Plant Calcium", precio: 32, pv: 13000 },
  { categoria: "Sănătate", nombre: "Pomegranate Beauty", precio: 77, pv: 37000 },
  { categoria: "Sănătate", nombre: "Power Vits Energizer", precio: 39, pv: 22000 },
  { categoria: "Sănătate", nombre: "Psyllium Husk", precio: 32, pv: 21000 },
  { categoria: "Sănătate", nombre: "Pure Spirulina 100%", precio: 26, pv: 12000 },
  { categoria: "Sănătate", nombre: "Rhodiola Milk Thistle", precio: 35, pv: 15000 },
  { categoria: "Sănătate", nombre: "Saw Palmetto", precio: 38, pv: 15000 },
  { categoria: "Sănătate", nombre: "US Probiotics", precio: 40, pv: 22000 },
  { categoria: "Sănătate", nombre: "Vital Color Vitamin C", precio: 24, pv: 11000 },
  { categoria: "Sănătate", nombre: "Vital Mega Vitamin C 2000", precio: 39, pv: 22000 },
  { categoria: "Sănătate", nombre: "Vitamin B Complex", precio: 22, pv: 10000 },
  { categoria: "Sănătate", nombre: "Vitamin D3", precio: 32, pv: 12000 },
  { categoria: "HemoHIM", nombre: "HemoHIM 30 Pack", precio: 80, pv: 75000 },
  { categoria: "HemoHIM", nombre: "HemoHIM Manual (English) *1ea", precio: 0.4, pv: 0 },
  { categoria: "Frumusețe", nombre: "3-Seconds Beauty Water", precio: 16, pv: 7500 },
  { categoria: "Frumusețe", nombre: "A.C. Expert Foam Cleanser", precio: 17.5, pv: 11000 },
  { categoria: "Frumusețe", nombre: "A.C. Expert Serum", precio: 25, pv: 15000 },
  { categoria: "Frumusețe", nombre: "A.C. Expert Spot Solution", precio: 22, pv: 12000 },
  { categoria: "Frumusețe", nombre: "A.C. Expert System Set", precio: 84, pv: 55000 },
  { categoria: "Frumusețe", nombre: "A.C. Expert Toner", precio: 24, pv: 15000 },
  { categoria: "Frumusețe", nombre: "Absolute Ampoule", precio: 50, pv: 33000 },
  { categoria: "Frumusețe", nombre: "Absolute Eye-Complex", precio: 48, pv: 30000 },
  { categoria: "Frumusețe", nombre: "Absolute Lotion", precio: 45, pv: 27000 },
  { categoria: "Frumusețe", nombre: "Absolute Nutrition Cream", precio: 45, pv: 27000 },
  { categoria: "Frumusețe", nombre: "Absolute Oil Serum Mist", precio: 26, pv: 17000 },
  { categoria: "Frumusețe", nombre: "Absolute Serum", precio: 48, pv: 30000 },
  { categoria: "Frumusețe", nombre: "Absolute Skincare Set", precio: 260, pv: 175000 },
  { categoria: "Frumusețe", nombre: "Absolute Spot-Out Cream", precio: 39, pv: 22000 },
  { categoria: "Frumusețe", nombre: "Absolute Spot-Out Essence", precio: 45, pv: 26000 },
  { categoria: "Frumusețe", nombre: "Absolute Toner", precio: 45, pv: 27000 },
  { categoria: "Frumusețe", nombre: "Adelica Long-Lash Mascara", precio: 15.5, pv: 9000 },
  { categoria: "Frumusețe", nombre: "Adelica Loose Setting Powder", precio: 30.5, pv: 19000 },
  { categoria: "Frumusețe", nombre: "Adelica Mood on Eye Palette", precio: 25, pv: 15000 },
  { categoria: "Frumusețe", nombre: "Adelica Volume Mascara", precio: 15.5, pv: 9000 },
  { categoria: "Frumusețe", nombre: "BB Cream", precio: 10, pv: 3000 },
  { categoria: "Frumusețe", nombre: "Cream Mist", precio: 17, pv: 10000 },
  { categoria: "Frumusețe", nombre: "Daily Expert Mask Brightening", precio: 12.5, pv: 6000 },
  { categoria: "Frumusețe", nombre: "Daily Expert Mask Firming", precio: 12.5, pv: 6000 },
  { categoria: "Frumusețe", nombre: "Daily Expert Mask Moisturizing", precio: 12.5, pv: 6000 },
  { categoria: "Frumusețe", nombre: "Deep Cleanser", precio: 12, pv: 5000 },
  { categoria: "Frumusețe", nombre: "Deep Pure Cleansing Oil", precio: 20, pv: 8000 },
  { categoria: "Frumusețe", nombre: "Derma Calming Sun Stick", precio: 13, pv: 6000 },
  { categoria: "Frumusețe", nombre: "Derma Real Cica Ampoule", precio: 36, pv: 22000 },
  { categoria: "Frumusețe", nombre: "Derma Real Cica Cream", precio: 25, pv: 16000 },
  { categoria: "Frumusețe", nombre: "Derma Real Cica Gel Cleanser", precio: 15.5, pv: 10000 },
  { categoria: "Frumusețe", nombre: "Derma Real Cica Set", precio: 76, pv: 51000 },
  { categoria: "Frumusețe", nombre: "Derma Real Cica Toner", precio: 18.5, pv: 12000 },
  { categoria: "Frumusețe", nombre: "Evening Care 4 Set", precio: 45, pv: 21000 },
  { categoria: "Frumusețe", nombre: "Foam Cleanser", precio: 12, pv: 5000 },
  { categoria: "Frumusețe", nombre: "Healthy Glow Base", precio: 16, pv: 6000 },
  { categoria: "Frumusețe", nombre: "Homme Energizing All in One", precio: 25, pv: 14000 },
  { categoria: "Frumusețe", nombre: "Homme Essence", precio: 20, pv: 12000 },
  { categoria: "Frumusețe", nombre: "Homme Lotion", precio: 21, pv: 12000 },
  { categoria: "Frumusețe", nombre: "Homme Multi-Action Cleanser", precio: 12, pv: 5500 },
  { categoria: "Frumusețe", nombre: "Homme Skincare Set", precio: 58, pv: 37000 },
  { categoria: "Frumusețe", nombre: "Homme Toner", precio: 21, pv: 12000 },
  { categoria: "Frumusețe", nombre: "Hydra Brightening Care Set", precio: 50, pv: 32000 },
  { categoria: "Frumusețe", nombre: "Hydra Brightening Cream", precio: 25, pv: 15000 },
  { categoria: "Frumusețe", nombre: "Hydra Brightening Essence", precio: 26, pv: 16000 },
  { categoria: "Frumusețe", nombre: "Lip Glow", precio: 14, pv: 7000 },
  { categoria: "Frumusețe", nombre: "Lip Treatment", precio: 6.5, pv: 3000 },
  { categoria: "Frumusețe", nombre: "Marine Ampoule Eye Patch", precio: 19, pv: 11000 },
  { categoria: "Frumusețe", nombre: "Peel-Off Mask", precio: 12, pv: 5000 },
  { categoria: "Frumusețe", nombre: "Peeling Gel", precio: 12, pv: 5000 },
  { categoria: "Frumusețe", nombre: "Peeling Pad", precio: 12, pv: 6500 },
  { categoria: "Frumusețe", nombre: "Rose Rain Mist", precio: 13, pv: 5000 },
  { categoria: "Frumusețe", nombre: "Sun Stick", precio: 12, pv: 6000 },
  { categoria: "Frumusețe", nombre: "Sunscreen (Beige)", precio: 12, pv: 6000 },
  { categoria: "Frumusețe", nombre: "Sunscreen (White)", precio: 12, pv: 6000 },
  { categoria: "Frumusețe", nombre: "Synergy Ampoule *1 Set", precio: 135, pv: 90000 },
  { categoria: "Frumusețe", nombre: "Synergy Ampoule *3 Sets", precio: 400, pv: 320000 },
  { categoria: "Frumusețe", nombre: "The Fame Essence", precio: 27, pv: 16000 },
  { categoria: "Frumusețe", nombre: "The Fame Eye Cream", precio: 26, pv: 15000 },
  { categoria: "Frumusețe", nombre: "The Fame Lotion", precio: 26, pv: 15000 },
  { categoria: "Frumusețe", nombre: "The Fame Nutrition Cream", precio: 26, pv: 15000 },
  { categoria: "Frumusețe", nombre: "The Fame Set", precio: 120, pv: 77000 },
  { categoria: "Frumusețe", nombre: "The Fame Toner", precio: 26, pv: 15000 },
  { categoria: "Frumusețe", nombre: "The Fame Travel Kit", precio: 40, pv: 15000 },
  { categoria: "Frumusețe", nombre: "Travel Cleansing Kit", precio: 15, pv: 4000 },
  { categoria: "Diverse", nombre: "[CHALLENGE] Noni 5+1", precio: 285, pv: 175000 },
  { categoria: "Diverse", nombre: "Beauty & Personal Care Best Kit", precio: 300, pv: 200000 },
  { categoria: "Diverse", nombre: "HemoBlend Kit", precio: 150, pv: 50000 },
  { categoria: "Diverse", nombre: "Leaflet *50ea", precio: 15, pv: 0 },
  { categoria: "Diverse", nombre: "Life Scenario (English) *10ea", precio: 10, pv: 0 },
  { categoria: "Diverse", nombre: "Life Scenario (Spanish) *10ea", precio: 10, pv: 0 },
  { categoria: "Diverse", nombre: "Non-Woven Fabric Shopping Bag *1ea", precio: 10, pv: 0 },
  { categoria: "Diverse", nombre: "Plastic Bag *1ea", precio: 2, pv: 0 },
  { categoria: "Diverse", nombre: "Shopping Bag (Blue) *1ea", precio: 1, pv: 0 },
  { categoria: "Diverse", nombre: "Shopping Bag (White) *1ea", precio: 1, pv: 0 },
  ],
};

const CATALOGO_PRODUCTOS_NOTA = "Catalog de referință construit din propria ta listă — Atomy își actualizează frecvent produsele și fiecare țară are un catalog diferit, așa că poate fi depășit. Editează, adaugă sau șterge produse aici pentru a-l ține la zi.";

const CATALOGO_PRODUCTOS_NOTA_VACIO = "Încă nu avem încărcat catalogul acestei țări. Apasă \"+ Adaugă produs\" pentru a începe să-l construiești (sau trimite-i asistentului tău capturi de ecran cu prețurile/PV din țara ta, pentru a-l încărca complet).";

const META_PV_QUINCENA = 2500000;

const MENSAJE_BIENVENIDA =
  "Ai cucerit deja Sales Master — acesta este următorul tău munte. Aici vei înțelege cum funcționează planul complet de compensare și vei planifica quincenă cu quincenă alături de echipa ta, ca să valorifici fiecare punct și să nu pierzi niciun ciclaj.";

const IDIOMAS_INFORME = [
  { id: "es", label: "Español" },
  { id: "en", label: "English" },
  { id: "fr", label: "Français" },
  { id: "it", label: "Italiano" },
  { id: "ro", label: "Română" },
  { id: "pt", label: "Português" },
];

const INFORME_I18N = {
  es: { llamadas: "Llamadas", mensajes: "Mensajes de invitación", presentaciones: "Presentaciones (Show the Plan)", reuniones: "Reuniones / consultorías",
    tituloPersonal: "📊 Mi informe semanal de actividad (Cumbre Master):", cierrePersonal: "¿Qué te parece? ¿En qué puedo mejorar esta semana?",
    tituloEquipo: "👥 Informe semanal de mi equipo (Cumbre Master):", personasRed: "Personas en mi red esta quincena", verificados: "Verificados (ya pidieron sus puntos)", pendientes: "Pendientes por verificar", pvPlaneado: "PV total planeado", pvVerificado: "PV verificado", cierreEquipo: "Aquí va el resumen de mi equipo — ¿me ayudas a revisarlo?" },
  en: { llamadas: "Calls", mensajes: "Invitation messages", presentaciones: "Presentations (Show the Plan)", reuniones: "Meetings / consultations",
    tituloPersonal: "📊 My weekly activity report (Cumbre Master):", cierrePersonal: "What do you think? How can I improve this week?",
    tituloEquipo: "👥 My team's weekly report (Cumbre Master):", personasRed: "People in my network this period", verificados: "Verified (already ordered their points)", pendientes: "Pending verification", pvPlaneado: "Total planned PV", pvVerificado: "Verified PV", cierreEquipo: "Here's my team's summary — can you help me review it?" },
  fr: { llamadas: "Appels", mensajes: "Messages d'invitation", presentaciones: "Présentations (Show the Plan)", reuniones: "Réunions / consultations",
    tituloPersonal: "📊 Mon rapport d'activité hebdomadaire (Cumbre Master) :", cierrePersonal: "Qu'en penses-tu ? Comment puis-je m'améliorer cette semaine ?",
    tituloEquipo: "👥 Rapport hebdomadaire de mon équipe (Cumbre Master) :", personasRed: "Personnes dans mon réseau cette période", verificados: "Vérifiés (ont déjà commandé leurs points)", pendientes: "En attente de vérification", pvPlaneado: "PV total prévu", pvVerificado: "PV vérifié", cierreEquipo: "Voici le résumé de mon équipe — peux-tu m'aider à le revoir ?" },
  it: { llamadas: "Chiamate", mensajes: "Messaggi di invito", presentaciones: "Presentazioni (Show the Plan)", reuniones: "Riunioni / consulenze",
    tituloPersonal: "📊 Il mio report settimanale di attività (Cumbre Master):", cierrePersonal: "Cosa ne pensi? Come posso migliorare questa settimana?",
    tituloEquipo: "👥 Report settimanale del mio team (Cumbre Master):", personasRed: "Persone nella mia rete questo periodo", verificados: "Verificati (hanno già ordinato i loro punti)", pendientes: "In attesa di verifica", pvPlaneado: "PV totale pianificato", pvVerificado: "PV verificato", cierreEquipo: "Ecco il riepilogo del mio team — mi aiuti a rivederlo?" },
  ro: { llamadas: "Apeluri", mensajes: "Mesaje de invitație", presentaciones: "Prezentări (Show the Plan)", reuniones: "Întâlniri / consultații",
    tituloPersonal: "📊 Raportul meu săptămânal de activitate (Cumbre Master):", cierrePersonal: "Ce părere ai? Cum pot îmbunătăți săptămâna asta?",
    tituloEquipo: "👥 Raportul săptămânal al echipei mele (Cumbre Master):", personasRed: "Persoane în rețeaua mea în această perioadă", verificados: "Verificați (și-au comandat deja punctele)", pendientes: "În așteptarea verificării", pvPlaneado: "PV total planificat", pvVerificado: "PV verificat", cierreEquipo: "Iată rezumatul echipei mele — mă ajuți să-l revizuim?" },
  pt: { llamadas: "Chamadas", mensajes: "Mensagens de convite", presentaciones: "Apresentações (Show the Plan)", reuniones: "Reuniões / consultorias",
    tituloPersonal: "📊 Meu relatório semanal de atividade (Cumbre Master):", cierrePersonal: "O que você acha? Como posso melhorar esta semana?",
    tituloEquipo: "👥 Relatório semanal da minha equipe (Cumbre Master):", personasRed: "Pessoas na minha rede neste período", verificados: "Verificados (já pediram seus pontos)", pendientes: "Pendentes de verificação", pvPlaneado: "PV total planejado", pvVerificado: "PV verificado", cierreEquipo: "Aqui está o resumo da minha equipe — pode me ajudar a revisar?" },
};

function informeI18n(idioma) {
  return INFORME_I18N[idioma] || INFORME_I18N.es;
}

/* ---------------------------------------------------------------
   AGENDA SEMANAL — rutina de trabajo de un líder: llamadas y reuniones
   con afiliados, formaciones de equipo, reuniones de líderes y Zoom.
--------------------------------------------------------------- */

const DIAS_SEMANA = [
  { id: "lunes", label: "Luni" },
  { id: "martes", label: "Marți" },
  { id: "miercoles", label: "Miercuri" },
  { id: "jueves", label: "Joi" },
  { id: "viernes", label: "Vineri" },
  { id: "sabado", label: "Sâmbătă" },
  { id: "domingo", label: "Duminică" },
];

const AGENDA_TIPOS = [
  { id: "llamada", label: "Apel către un partener", icon: "phone-call" },
  { id: "reunion-afiliado", label: "Întâlnire cu un afiliat", icon: "users" },
  { id: "consultoria", label: "Consultanță / urmărire", icon: "target" },
  { id: "formacion", label: "Formare de echipă", icon: "book-open" },
  { id: "reunion-lideres", label: "Întâlnire de lideri", icon: "crown" },
];

/* ---------------------------------------------------------------
   HERRAMIENTAS DE PLANIFICACIÓN — Gran Plan 3, Diario de mi yo futuro,
   Evaluación mensual de Los 8 Pasos y Plan comercial mensual, incrustadas
   en Planeador de Quincena.
--------------------------------------------------------------- */

const DIARIO_FUTURO_INTRO =
  "Scrie o scrisoare sau un jurnal din perspectiva „eu-lui tău din viitor” — persoana de succes în care te vei transforma. Povestește-i eu-lui tău de astăzi cum ai reușit, ce ai învățat pe drum și ce i-ai spune pentru a-l încuraja să continue.";

const DIARIO_FUTURO_EJEMPLO =
  "Ex.: „Astăzi am absolvit Școala de Succes Atomy... Cu timp în urmă am avut un vis și am muncit din greu ca să-l realizez. Nu a fost simplu, dar fiecare pas a meritat. Dacă citești asta, continuă — persoana în care te vei transforma îți va fi recunoscătoare.”";

const GRAN_PLAN_3_INTRO =
  "Desenează-ți viu planul de 3 ani: la ce dată vei atinge fiecare nivel de măiestrie, cu câte PV de grup și ce venituri. Nu trebuie completat lună de lună — adaugă reperele care au sens pentru tine, în anul care corespunde.";

const EVALUACION_8PASOS_CATEGORIAS = [
  { id: "metas", label: "Stabilirea obiectivelor", pregunta: "Ai stabilit obiective specifice de performanță în afacere, pentru o viață echilibrată?" },
  { id: "propositos", label: "Scopuri", pregunta: "Te-ai implicat activ în afacere și ai luat inițiativa de a-ți exprima opiniile altora, cu o atitudine pozitivă?" },
  { id: "lista", label: "Realizarea unei liste", pregunta: "Ai făcut o listă cu toate persoanele pe care le cunoști în jurul tău?" },
  { id: "contacto", label: "Contact", pregunta: "Ai alocat un timp specific fiecare zi și ai comunicat cu ei în mod regulat?" },
  { id: "descripcion", label: "Descrierea afacerii", pregunta: "Ai explicat următoarele? ① Filosofia companiei ② Produsele ③ Planul de compensare ④ Viziunea corporativă" },
  { id: "seguimiento", label: "Gestionarea urmăririi", pregunta: "Ți-ai făcut timp să răspunzi oricărei plângeri sau neînțelegeri legate de produse/afacere în interval de 48 de ore?" },
  { id: "consulta", label: "Consultare", pregunta: "Ai găsit o soluție la vreo problemă datorită consultărilor cu partenerii?" },
  { id: "replicacion", label: "Duplicare", pregunta: "Ai învățat despre succesul sponsorului tău și ți-ai împărtășit propriile cunoștințe cu partenerii tăi?" },
];

/* ---------------------------------------------------------------
   RETO 7×7 — ciclo semanal de 7 días para desarrollar el negocio
   (contactar → presentar → recomendar → seguir → cerrar → duplicar → repetir)
--------------------------------------------------------------- */

const RETO_7X7_INTRO =
  "Provocarea 7×7 este munca ta zilnică pentru a-ți dezvolta afacerea: 7 zile, un ciclu complet. Completează-o în fiecare săptămână, în aceste 4 săptămâni, și apoi repetă-o pentru totdeauna — acesta este secretul duplicării.";

const RETO_7X7_DIAS = [
  {
    id: 1,
    icono: "flame",
    titulo: "Definește-te și pregătește-te",
    frase: "„Dacă nu am o țintă, nu am o direcție.”",
    contenido: [
      "1. Definește-ți obiectivul pentru următoarele 7 zile (câte conversații, prezentări sau înregistrări vrei să obții).",
      "2. Fă o listă cu 30 de persoane.",
      "3. Clasifică-ți contactele: potențiali clienți, persoane interesate de wellness, persoane interesate să genereze venituri.",
      "4. Alege-ți primele 10 contacte cu care să începi mâine.",
      "Încă nu vinde nimic: mai întâi construim lista.",
      "Misiunea zilei: 30 de nume înainte de a te culca.",
    ],
    checklist: [
      "Mi-am definit obiectivul pentru următoarele 7 zile.",
      "Mi-am făcut lista cu 30 de persoane și mi-am clasificat contactele.",
      "Mi-am ales primele 10 contacte — misiune: 30 de nume înainte de culcare.",
    ],
    quiz: {
      pregunta: "Câte nume este misiunea de azi, înainte de culcare?",
      opciones: ["10", "30", "100"],
      correcta: 1,
    },
  },
  {
    id: 2,
    icono: "phone-call",
    titulo: "Deschide conversații",
    frase: "„10 conversații reale.”",
    contenido: [
      "Contactează personal 10 persoane din lista ta. Nu trimite un catalog de la început: mai întâi conversează.",
      "Exemplu de script: „Salut, particip la o provocare de 7 zile pentru a-mi dezvolta proiectul de wellness și venituri. Caut câteva persoane cărora să le arăt cum funcționează. Ți-ar plăcea să-ți povestesc?”",
      "Dacă răspunde afirmativ: „Perfect 😊. Îți fac o explicație foarte scurtă și tu îmi spui dacă te-ar putea interesa.”",
      "Regula de aur: întreabă → ascultă → identifică nevoia → prezintă.",
      "Misiunea zilei: 10 conversații.",
    ],
    checklist: [
      "Am contactat personal 10 persoane din lista mea.",
      "Am folosit scriptul de conversație în loc să trimit direct un catalog.",
    ],
    quiz: {
      pregunta: "Înainte de a prezenta produse sau afacerea, ce trebuie să faci mai întâi?",
      opciones: ["Să trimiți un catalog", "Să conversezi și să asculți", "Nimic, direct la vânzare"],
      correcta: 1,
    },
  },
  {
    id: 3,
    icono: "presentation",
    titulo: "Recomandă",
    frase: "„Nu vând produse. Descopăr nevoi.”",
    contenido: [
      "Astăzi conversezi pentru a descoperi: ce produs folosesc în prezent?, ce nevoie vor să rezolve?, ce produse cumpără în mod regulat?, sunt interesați să cunoască o alternativă de cumpărare?",
      "După ce ai ascultat, urmează secvența: Recomandă → Explică → Invită.",
      "Exemplu: „Spune-mi, ce produse folosești de obicei pentru îngrijirea personală sau wellness?” După ce ai ascultat: „Chiar am o alternativă care te-ar putea interesa. Vrei să-ți arăt cum funcționează?”",
      "Misiunea zilei: prezintă produse persoanelor cu o nevoie reală.",
    ],
    checklist: [
      "Am conversat pentru a descoperi nevoi reale, fără să vând la întâmplare.",
      "Am prezentat produse persoanelor la care am detectat o nevoie reală.",
    ],
    quiz: {
      pregunta: "Care este secvența corectă a Zilei 3?",
      opciones: ["Recomandă → Explică → Invită", "Vinde → Încasează → Livrează", "Invită → Vinde → Uită"],
      correcta: 0,
    },
  },
  {
    id: 4,
    icono: "users",
    titulo: "Prezintă oportunitatea",
    frase: "„Nu toți vor să cumpere. Unii vor să construiască.”",
    contenido: [
      "Caută persoane care vor: să genereze venituri adiționale, să cumpere inteligent, să recomande produse sau să construiască o afacere.",
      "Mini-prezentare în 4 întrebări: Ce este Atomy? O companie internațională de vânzare directă. Ce găsim? Produse din categorii diferite. Cum funcționează? Consumă → Recomandă → Dezvoltă clienți și echipă. Ce căutăm? Să construim o afacere printr-un sistem pe care să-l putem repeta și preda altora.",
      "Misiunea zilei: prezintă oportunitatea la minimum 3 persoane.",
    ],
    checklist: ["Am prezentat oportunitatea de afaceri la minimum 3 persoane."],
    quiz: {
      pregunta: "Ce căutăm, potrivit mini-prezentării în 4 întrebări?",
      opciones: ["Să vindem cât mai rapid posibil", "Să construim o afacere cu un sistem pe care să-l putem repeta și preda", "Să convingem fără să ascultăm"],
      correcta: 1,
    },
  },
  {
    id: 5,
    icono: "clipboard-list",
    titulo: "Urmărire",
    frase: "Averea este în urmărire.",
    contenido: [
      "Astăzi recontactezi: persoanele care au întrebat, persoanele care au văzut prezentarea, persoanele care au spus „lasă-mă să mă gândesc”, persoanele care au arătat interes.",
      "Exemplu — reluarea contactului: „Salut 😊. Voiam să știu ce părere ai despre ce am discutat zilele trecute. A fost ceva care ți-a atras atenția în mod special?”",
      "Exemplu — dacă spune „mă mai gândesc”: „Sigur, nu te grăbi. La ce parte vrei să te gândești: la produs, la investiție sau la cum funcționează afacerea?”",
      "Exemplu — dacă spune „nu am bani”: „Te înțeleg. Nu vreau să faci ceva ce nu-ți permit posibilitățile. Putem începe discutând despre model și despre cum să valorifici achizițiile pe care le faci deja de obicei.”",
      "Un mesaj trimis la timp poate deschide o mare oportunitate.",
      "Misiunea zilei: fă urmărire pentru toate conversațiile rămase deschise.",
    ],
    checklist: [
      "Am făcut urmărire pentru toate conversațiile mele rămase deschise.",
      "Am reluat contactul cu cei care au spus „lasă-mă să mă gândesc”.",
      "Am reluat contactul cu cei care au arătat interes sau au văzut prezentarea mea.",
    ],
    quiz: {
      pregunta: "Potrivit Provocării 7×7, unde se află averea?",
      opciones: ["În a vorbi doar cu oameni noi", "În urmărire", "În a trimite pur și simplu un catalog"],
      correcta: 1,
    },
  },
  {
    id: 6,
    icono: "repeat",
    titulo: "Duplică",
    frase: "„Nu o face singur.”",
    contenido: [
      "Ciclul duplicării: Eu o fac → Te învăț → Tu o faci → Tu îi înveți pe alții.",
      "Invită o persoană interesată să realizeze împreună cu tine: lista ei de contacte, primele ei conversații, prima ei prezentare, prima ei urmărire.",
      "Fiecare acțiune contează. Provocarea nu se termină: începe ciclul! Împreună ajungem mai departe.",
      "Misiunea zilei: ajută o persoană să înceapă procesul.",
    ],
    checklist: [
      "Am invitat o persoană interesată să parcurgă procesul împreună cu mine.",
      "Am ajutat-o pe acea persoană să-și înceapă propria listă, conversații, prezentare sau urmărire.",
    ],
    quiz: {
      pregunta: "Care este ciclul duplicării din Provocarea 7×7?",
      opciones: [
        "Eu o fac → Te învăț → Tu o faci → Tu îi înveți pe alții",
        "Eu vând → Tu cumperi → Final",
        "Eu decid → Tu te supui",
      ],
      correcta: 0,
    },
  },
  {
    id: 7,
    icono: "check",
    titulo: "Evaluează, încheie și repetă",
    frase: "„Rezultatele se măsoară.”",
    contenido: [
      "Astăzi revizuim: câte persoane am contactat?, câte au răspuns?, câte prezentări am făcut?, câte vânzări am obținut?, câte persoane sunt interesate de afacere?, pe cine trebuie să continui să acompaniez?",
      "Provocarea nu se termină aici: începe ciclul! Contactează → Prezintă → Recomandă → Urmărește → Încheie → Duplică → Repetă.",
      "Ce s-ar întâmpla cu afacerea ta dacă, în următoarele săptămâni, ai repeta acest proces din nou și din nou? Nu trebuie să-l faci perfect. Trebuie să-l faci.",
      "Înregistrează-ți mai jos rezultatele săptămânii și împarte-le cu sponsorul tău.",
    ],
    checklist: [
      "Am contorizat câte persoane am contactat, câte au răspuns și câte prezentări am făcut.",
      "Am identificat pe cine trebuie să continui să acompaniez.",
      "Am înțeles că ciclul Contactează → Prezintă → Recomandă → Urmărește → Încheie → Duplică → Repetă nu se termină, se repetă.",
    ],
    quiz: {
      pregunta: "La finalul Provocării 7×7, ce este de făcut?",
      opciones: ["Să te oprești, s-a terminat", "Să repeți ciclul", "Să aștepți ca alții să te contacteze pe tine"],
      correcta: 1,
    },
  },
];

const EVALUACION_8PASOS_BANDAS = [
  { min: 0, max: 10, texto: "Ești abia la început. Vizionează videoclipurile de pregătire despre cei opt pași spre succes pe măsură ce avansezi." },
  { min: 11, max: 20, texto: "Este posibil ca afacerea ta să avanseze lent. Încearcă să-ți crești pasiunea și efortul." },
  { min: 21, max: 30, texto: "Ești dedicat să fii în frunte. Acordă atenție mediului tău, ca să nu treci cu vederea nimic." },
  { min: 31, max: 40, texto: "Perfecționezi cei opt pași spre succes și servești ca model pentru sponsorul tău și partenerii de afaceri." },
];
